'use strict';

// ════════════════════════════════════════
//  SPANISH DISCOURSE CONNECTOR DRILLS
//  Practice choosing the right connector
//  in context — contrast, cause, addition,
//  concession, sequence, reformulation
// ════════════════════════════════════════

const CONNECTOR_CATEGORIES = {
  contrast: {
    id: 'contrast',
    label: 'Contrast',
    labelEs: 'Contraste',
    description: 'However, on the other hand, nevertheless — opposing or contrasting ideas.',
    descriptionEs: 'Sin embargo, en cambio, no obstante — ideas opuestas o contrastantes.',
  },
  addition: {
    id: 'addition',
    label: 'Addition',
    labelEs: 'Adición',
    description: 'Moreover, also, furthermore — adding information or reinforcing a point.',
    descriptionEs: 'Además, también, es más — añadir información o reforzar una idea.',
  },
  cause_effect: {
    id: 'cause_effect',
    label: 'Cause & Effect',
    labelEs: 'Causa y efecto',
    description: 'Therefore, so, as a result — expressing reasons and consequences.',
    descriptionEs: 'Por lo tanto, así que, por eso — expresar razones y consecuencias.',
  },
  concession: {
    id: 'concession',
    label: 'Concession',
    labelEs: 'Concesión',
    description: 'Although, despite, even so — acknowledging a point while maintaining your argument.',
    descriptionEs: 'Aunque, a pesar de, aun así — reconocer un punto sin abandonar el argumento.',
  },
  sequence: {
    id: 'sequence',
    label: 'Sequence',
    labelEs: 'Secuencia',
    description: 'First, next, finally — ordering ideas and structuring discourse.',
    descriptionEs: 'En primer lugar, a continuación, finalmente — ordenar ideas y estructurar el discurso.',
  },
  reformulation: {
    id: 'reformulation',
    label: 'Reformulation',
    labelEs: 'Reformulación',
    description: 'In other words, that is to say — rephrasing or clarifying what was said.',
    descriptionEs: 'Es decir, o sea, en otras palabras — reformular o aclarar lo dicho.',
  },
};

const CONNECTORS = [

  // ──────────────────────────────────────
  //  CONTRAST  (8 items)
  // ──────────────────────────────────────

  {
    id: 'con-1',
    category: 'contrast',
    level: 'B1',
    sentence: 'Estudié mucho para el examen. ___, no aprobé.',
    answer: 'Sin embargo',
    options: ['Sin embargo', 'Además', 'Por eso', 'Es decir'],
    explanation: '"Sin embargo" (however) introduces a result that contradicts the expectation. You studied hard, so you\'d expect to pass — but you didn\'t.',
    explanationEs: '"Sin embargo" introduce un resultado contrario a lo esperado. Estudiaste mucho, así que esperarías aprobar, pero no fue así.',
  },
  {
    id: 'con-2',
    category: 'contrast',
    level: 'B1',
    sentence: 'A mi hermano le encanta el frío. ___, yo prefiero el calor.',
    answer: 'En cambio',
    options: ['En cambio', 'Sin embargo', 'Por lo tanto', 'Incluso'],
    explanation: '"En cambio" (on the other hand) contrasts two different subjects or situations. It highlights a difference between your brother and you.',
    explanationEs: '"En cambio" contrasta dos sujetos o situaciones distintas. Resalta la diferencia entre tu hermano y tú.',
  },
  {
    id: 'con-3',
    category: 'contrast',
    level: 'B2',
    sentence: 'El proyecto tiene riesgos. ___, los beneficios superan las dificultades.',
    answer: 'No obstante',
    options: ['No obstante', 'En cambio', 'Así que', 'En primer lugar'],
    explanation: '"No obstante" (nevertheless) acknowledges a difficulty but continues the argument. More formal than "sin embargo", common in written/academic Spanish.',
    explanationEs: '"No obstante" reconoce una dificultad pero continúa el argumento. Es más formal que "sin embargo", frecuente en español escrito y académico.',
  },
  {
    id: 'con-4',
    category: 'contrast',
    level: 'B2',
    sentence: 'La propuesta es interesante. ___, debemos considerar si es viable.',
    answer: 'Ahora bien',
    options: ['Ahora bien', 'Sin embargo', 'Además', 'O sea'],
    explanation: '"Ahora bien" (now then / having said that) shifts focus to a new consideration without directly contradicting. It says: "that\'s fine, but let\'s look at this angle."',
    explanationEs: '"Ahora bien" cambia el enfoque a una nueva consideración sin contradecir directamente. Dice: "eso está bien, pero miremos este ángulo."',
  },
  {
    id: 'con-5',
    category: 'contrast',
    level: 'B2',
    sentence: 'No quiere estudiar medicina. ___, quiere ser artista.',
    answer: 'Por el contrario',
    options: ['Por el contrario', 'No obstante', 'Por consiguiente', 'Asimismo'],
    explanation: '"Por el contrario" (on the contrary) directly opposes the previous statement. It doesn\'t just contrast — it replaces one idea with its opposite.',
    explanationEs: '"Por el contrario" se opone directamente a la afirmación anterior. No solo contrasta, sino que reemplaza una idea por su opuesta.',
  },
  {
    id: 'con-6',
    category: 'contrast',
    level: 'B1',
    sentence: 'El hotel era caro. ___, la ubicación era excelente.',
    answer: 'Eso sí',
    options: ['Eso sí', 'En cambio', 'Por eso', 'Finalmente'],
    explanation: '"Eso sí" (mind you / that said) concedes a positive point after a negative one (or vice versa). Very natural in spoken Spanish.',
    explanationEs: '"Eso sí" concede un punto positivo después de uno negativo (o viceversa). Muy natural en el español hablado.',
  },
  {
    id: 'con-7',
    category: 'contrast',
    level: 'C1',
    sentence: 'Los resultados no son concluyentes. ___, aportan datos valiosos para futuras investigaciones.',
    answer: 'Con todo',
    options: ['Con todo', 'En cambio', 'Por lo tanto', 'En primer lugar'],
    explanation: '"Con todo" (all the same / even so) is a formal/literary connector meaning "despite everything." Similar to "no obstante" but more emphatic.',
    explanationEs: '"Con todo" es un conector formal/literario que significa "a pesar de todo". Similar a "no obstante" pero más enfático.',
  },
  {
    id: 'con-8',
    category: 'contrast',
    level: 'C1',
    sentence: 'La empresa afirma que no habrá despidos. ___, los empleados temen recortes.',
    answer: 'Pese a ello',
    options: ['Pese a ello', 'Ahora bien', 'Así que', 'Es más'],
    explanation: '"Pese a ello" (despite that / in spite of it) is a formal concessive-contrast connector. It acknowledges the previous claim while showing reality differs.',
    explanationEs: '"Pese a ello" es un conector formal concesivo-contrastivo. Reconoce la afirmación anterior mientras muestra que la realidad difiere.',
  },

  // ──────────────────────────────────────
  //  ADDITION  (6 items)
  // ──────────────────────────────────────

  {
    id: 'con-9',
    category: 'addition',
    level: 'B1',
    sentence: 'Habla español e inglés. ___, está aprendiendo francés.',
    answer: 'Además',
    options: ['Además', 'Sin embargo', 'En cambio', 'Por eso'],
    explanation: '"Además" (moreover / in addition) adds new information that reinforces or extends the previous point.',
    explanationEs: '"Además" añade información nueva que refuerza o amplía el punto anterior.',
  },
  {
    id: 'con-10',
    category: 'addition',
    level: 'B1',
    sentence: 'La comida estaba deliciosa. ___, el servicio fue impecable.',
    answer: 'También',
    options: ['También', 'En cambio', 'Es decir', 'Ahora bien'],
    explanation: '"También" (also) simply adds another positive point. Less emphatic than "además" — it places both items on equal footing.',
    explanationEs: '"También" simplemente añade otro punto positivo. Menos enfático que "además" — pone ambos elementos al mismo nivel.',
  },
  {
    id: 'con-11',
    category: 'addition',
    level: 'B2',
    sentence: 'El informe confirma los problemas conocidos. ___, revela nuevas irregularidades.',
    answer: 'Es más',
    options: ['Es más', 'También', 'Sin embargo', 'A continuación'],
    explanation: '"Es más" (what\'s more / furthermore) escalates — it adds something that goes beyond what was said, often stronger or more surprising.',
    explanationEs: '"Es más" escala: añade algo que va más allá de lo dicho, a menudo más fuerte o sorprendente.',
  },
  {
    id: 'con-12',
    category: 'addition',
    level: 'B2',
    sentence: 'El candidato tiene experiencia internacional. ___, domina tres idiomas.',
    answer: 'Asimismo',
    options: ['Asimismo', 'No obstante', 'Por el contrario', 'O sea'],
    explanation: '"Asimismo" (likewise / also) is a formal synonym of "también" or "además." Common in CVs, reports, and academic writing.',
    explanationEs: '"Asimismo" es un sinónimo formal de "también" o "además". Frecuente en currículos, informes y escritura académica.',
  },
  {
    id: 'con-13',
    category: 'addition',
    level: 'B2',
    sentence: 'No solo llegó tarde, sino que ___ se olvidó los documentos.',
    answer: 'encima',
    options: ['encima', 'además', 'también', 'asimismo'],
    explanation: '"Encima" (on top of that) adds a complaint or negative escalation. It expresses annoyance: "and to make matters worse..."',
    explanationEs: '"Encima" añade una queja o escalada negativa. Expresa molestia: "y para colmo..."',
  },
  {
    id: 'con-14',
    category: 'addition',
    level: 'C1',
    sentence: 'No solo ganó la carrera, ___ batió el récord mundial.',
    answer: 'sino que incluso',
    options: ['sino que incluso', 'sino que también', 'sino que encima', 'sino que además'],
    explanation: '"Sino que incluso" (but even) escalates to something unexpected and impressive. "Incluso" adds the element of surprise — beyond what anyone expected.',
    explanationEs: '"Sino que incluso" escala a algo inesperado e impresionante. "Incluso" añade el elemento de sorpresa, más allá de lo que nadie esperaba.',
  },

  // ──────────────────────────────────────
  //  CAUSE & EFFECT  (6 items)
  // ──────────────────────────────────────

  {
    id: 'con-15',
    category: 'cause_effect',
    level: 'B1',
    sentence: 'Llovió toda la noche, ___ las calles están inundadas.',
    answer: 'así que',
    options: ['así que', 'sin embargo', 'aunque', 'en cambio'],
    explanation: '"Así que" (so) introduces a natural consequence in informal/neutral register. The flooding is a direct result of the rain.',
    explanationEs: '"Así que" introduce una consecuencia natural en registro informal/neutro. La inundación es resultado directo de la lluvia.',
  },
  {
    id: 'con-16',
    category: 'cause_effect',
    level: 'B1',
    sentence: 'No había estudiado nada. ___, suspendió el examen.',
    answer: 'Por eso',
    options: ['Por eso', 'No obstante', 'Es decir', 'Además'],
    explanation: '"Por eso" (that\'s why / for that reason) points back to the cause. It emphasizes the reason behind the result.',
    explanationEs: '"Por eso" señala la causa. Enfatiza la razón detrás del resultado.',
  },
  {
    id: 'con-17',
    category: 'cause_effect',
    level: 'B2',
    sentence: 'Los costes han subido un 30%. ___, debemos revisar el presupuesto.',
    answer: 'Por lo tanto',
    options: ['Por lo tanto', 'Por eso', 'Así que', 'Eso sí'],
    explanation: '"Por lo tanto" (therefore) is the formal equivalent of "así que." Used in business, academic, and official contexts to draw a logical conclusion.',
    explanationEs: '"Por lo tanto" es el equivalente formal de "así que". Se usa en contextos empresariales, académicos y oficiales para extraer una conclusión lógica.',
  },
  {
    id: 'con-18',
    category: 'cause_effect',
    level: 'B2',
    sentence: 'La demanda supera la oferta. ___, los precios seguirán aumentando.',
    answer: 'Por consiguiente',
    options: ['Por consiguiente', 'En cambio', 'Ahora bien', 'Encima'],
    explanation: '"Por consiguiente" (consequently) is a formal cause-effect connector for logical chains. Very common in economics, law, and science.',
    explanationEs: '"Por consiguiente" es un conector formal de causa-efecto para cadenas lógicas. Muy común en economía, derecho y ciencia.',
  },
  {
    id: 'con-19',
    category: 'cause_effect',
    level: 'B2',
    sentence: 'La población ha envejecido mucho; ___ se necesitan más centros de salud.',
    answer: 'de ahí que',
    options: ['de ahí que', 'por eso', 'así que', 'por lo tanto'],
    explanation: '"De ahí que" (hence / that is why) + subjunctive is a formal connector pointing from cause to consequence. Note: it requires the subjunctive (se necesiten), though "se necesitan" is accepted colloquially.',
    explanationEs: '"De ahí que" + subjuntivo es un conector formal que señala de la causa a la consecuencia. Nota: requiere subjuntivo (se necesiten), aunque "se necesitan" se acepta coloquialmente.',
  },
  {
    id: 'con-20',
    category: 'cause_effect',
    level: 'A2',
    sentence: 'Estaba cansada, ___ se fue a dormir temprano.',
    answer: 'por eso',
    options: ['por eso', 'sin embargo', 'en cambio', 'es decir'],
    explanation: '"Por eso" (that\'s why) is the most common cause-effect connector at this level. She was tired → she went to bed early.',
    explanationEs: '"Por eso" es el conector de causa-efecto más común a este nivel. Estaba cansada → se fue a dormir temprano.',
  },

  // ──────────────────────────────────────
  //  CONCESSION  (6 items)
  // ──────────────────────────────────────

  {
    id: 'con-21',
    category: 'concession',
    level: 'B1',
    sentence: '___ llovía mucho, fuimos a la playa.',
    answer: 'Aunque',
    options: ['Aunque', 'Porque', 'Por eso', 'Además'],
    explanation: '"Aunque" (although / even though) introduces a concession — you acknowledge the rain but it didn\'t stop you. The most versatile concessive connector.',
    explanationEs: '"Aunque" introduce una concesión — reconoces la lluvia pero no te detuvo. El conector concesivo más versátil.',
  },
  {
    id: 'con-22',
    category: 'concession',
    level: 'B1',
    sentence: '___ las dificultades, lograron terminar el proyecto.',
    answer: 'A pesar de',
    options: ['A pesar de', 'Gracias a', 'Debido a', 'Además de'],
    explanation: '"A pesar de" (despite / in spite of) + noun/infinitive concedes an obstacle that was overcome. Unlike "aunque", it doesn\'t take a conjugated verb directly.',
    explanationEs: '"A pesar de" + sustantivo/infinitivo concede un obstáculo que fue superado. A diferencia de "aunque", no lleva verbo conjugado directamente.',
  },
  {
    id: 'con-23',
    category: 'concession',
    level: 'B2',
    sentence: '___ la economía ha mejorado, el desempleo sigue alto.',
    answer: 'Si bien',
    options: ['Si bien', 'Porque', 'Ya que', 'Es más'],
    explanation: '"Si bien" (although / while it\'s true that) is a formal concessive connector. It concedes the first point before introducing a counterpoint. Common in essays and journalism.',
    explanationEs: '"Si bien" es un conector concesivo formal. Concede el primer punto antes de introducir un contrapunto. Común en ensayos y periodismo.',
  },
  {
    id: 'con-24',
    category: 'concession',
    level: 'B2',
    sentence: 'El plan tiene fallos. ___, es la mejor opción disponible.',
    answer: 'Aun así',
    options: ['Aun así', 'Por eso', 'En cambio', 'Es decir'],
    explanation: '"Aun así" (even so / still) concedes the problem but maintains the conclusion. Similar to "sin embargo" but with a stronger sense of "despite that being true."',
    explanationEs: '"Aun así" concede el problema pero mantiene la conclusión. Similar a "sin embargo" pero con un sentido más fuerte de "a pesar de que eso sea cierto".',
  },
  {
    id: 'con-25',
    category: 'concession',
    level: 'C1',
    sentence: '___ reconozco su esfuerzo, no puedo aprobar el trabajo.',
    answer: 'Por más que',
    options: ['Por más que', 'Aunque', 'Si bien', 'Ya que'],
    explanation: '"Por más que" (no matter how much / however much) + subjunctive expresses strong concession — even maximum effort isn\'t enough. More emphatic than "aunque".',
    explanationEs: '"Por más que" + subjuntivo expresa concesión fuerte — incluso el máximo esfuerzo no es suficiente. Más enfático que "aunque".',
  },
  {
    id: 'con-26',
    category: 'concession',
    level: 'C1',
    sentence: '___ que el método es antiguo, sigue dando buenos resultados.',
    answer: 'Pese a',
    options: ['Pese a', 'Dado', 'Debido a', 'Gracias a'],
    explanation: '"Pese a que" (despite the fact that) is a formal synonym of "a pesar de que." Very common in academic and journalistic writing.',
    explanationEs: '"Pese a que" es un sinónimo formal de "a pesar de que". Muy común en escritura académica y periodística.',
  },

  // ──────────────────────────────────────
  //  SEQUENCE  (6 items)
  // ──────────────────────────────────────

  {
    id: 'con-27',
    category: 'sequence',
    level: 'B1',
    sentence: '___, vamos a analizar las causas del problema.',
    answer: 'En primer lugar',
    options: ['En primer lugar', 'Finalmente', 'En resumen', 'Sin embargo'],
    explanation: '"En primer lugar" (in the first place / firstly) opens a structured sequence. It signals that more points will follow.',
    explanationEs: '"En primer lugar" abre una secuencia estructurada. Señala que vendrán más puntos.',
  },
  {
    id: 'con-28',
    category: 'sequence',
    level: 'B1',
    sentence: 'Primero revisamos los datos. ___, discutimos las conclusiones.',
    answer: 'A continuación',
    options: ['A continuación', 'En primer lugar', 'Por último', 'Por eso'],
    explanation: '"A continuación" (next / then) moves to the next step in a sequence. More formal than "luego" or "después".',
    explanationEs: '"A continuación" pasa al siguiente paso de una secuencia. Más formal que "luego" o "después".',
  },
  {
    id: 'con-29',
    category: 'sequence',
    level: 'B1',
    sentence: 'Hemos visto las ventajas y desventajas. ___, quiero proponer una solución.',
    answer: 'Por último',
    options: ['Por último', 'En primer lugar', 'A continuación', 'Además'],
    explanation: '"Por último" (lastly / finally) closes a sequence. It signals this is the final point before a conclusion.',
    explanationEs: '"Por último" cierra una secuencia. Señala que este es el punto final antes de una conclusión.',
  },
  {
    id: 'con-30',
    category: 'sequence',
    level: 'B2',
    sentence: '___, los datos muestran una clara tendencia al alza.',
    answer: 'En resumen',
    options: ['En resumen', 'A continuación', 'Es más', 'No obstante'],
    explanation: '"En resumen" (in summary) wraps up a discussion by distilling the key point. It\'s a closing connector, not a sequencing one.',
    explanationEs: '"En resumen" cierra una discusión destilando el punto clave. Es un conector de cierre, no de secuencia.',
  },
  {
    id: 'con-31',
    category: 'sequence',
    level: 'B2',
    sentence: 'Hay que mejorar la comunicación. ___, necesitamos invertir en formación.',
    answer: 'En segundo lugar',
    options: ['En segundo lugar', 'En resumen', 'Por el contrario', 'Aun así'],
    explanation: '"En segundo lugar" (secondly) continues a numbered sequence after "en primer lugar." Keeps your argument organized.',
    explanationEs: '"En segundo lugar" continúa una secuencia numerada después de "en primer lugar". Mantiene el argumento organizado.',
  },
  {
    id: 'con-32',
    category: 'sequence',
    level: 'B2',
    sentence: '___, quiero agradecer a todos los participantes por su colaboración.',
    answer: 'Para concluir',
    options: ['Para concluir', 'A continuación', 'En primer lugar', 'Es más'],
    explanation: '"Para concluir" (to conclude / in closing) is a formal way to signal the end of a speech or text. Slightly more formal than "por último".',
    explanationEs: '"Para concluir" es una forma formal de señalar el final de un discurso o texto. Ligeramente más formal que "por último".',
  },

  // ──────────────────────────────────────
  //  REFORMULATION  (6 items)
  // ──────────────────────────────────────

  {
    id: 'con-33',
    category: 'reformulation',
    level: 'B1',
    sentence: 'Es omnívoro, ___, come de todo.',
    answer: 'es decir',
    options: ['es decir', 'sin embargo', 'por eso', 'además'],
    explanation: '"Es decir" (that is / in other words) restates something in simpler or clearer terms. The most common reformulation connector.',
    explanationEs: '"Es decir" reformula algo en términos más simples o claros. El conector de reformulación más común.',
  },
  {
    id: 'con-34',
    category: 'reformulation',
    level: 'B1',
    sentence: 'No viene mañana, ___, que tendremos que hacerlo solos.',
    answer: 'o sea',
    options: ['o sea', 'es decir', 'en cambio', 'asimismo'],
    explanation: '"O sea" (so / I mean) is an informal reformulation connector. Very common in spoken Spanish to clarify or draw a practical conclusion.',
    explanationEs: '"O sea" es un conector informal de reformulación. Muy común en el español hablado para aclarar o sacar una conclusión práctica.',
  },
  {
    id: 'con-35',
    category: 'reformulation',
    level: 'B2',
    sentence: 'La tasa de inflación ha bajado. ___, los precios suben más lentamente.',
    answer: 'En otras palabras',
    options: ['En otras palabras', 'Por el contrario', 'Así que', 'Encima'],
    explanation: '"En otras palabras" (in other words) reformulates a technical or abstract statement in plainer language. More formal than "o sea".',
    explanationEs: '"En otras palabras" reformula una afirmación técnica o abstracta en lenguaje más llano. Más formal que "o sea".',
  },
  {
    id: 'con-36',
    category: 'reformulation',
    level: 'B2',
    sentence: 'Hay que optimizar los recursos. ___, hacer más con menos.',
    answer: 'Dicho de otro modo',
    options: ['Dicho de otro modo', 'En resumen', 'No obstante', 'También'],
    explanation: '"Dicho de otro modo" (put another way / in other terms) is a formal reformulation connector for rephrasing a complex idea. Common in presentations and essays.',
    explanationEs: '"Dicho de otro modo" es un conector formal de reformulación para replantear una idea compleja. Común en presentaciones y ensayos.',
  },
  {
    id: 'con-37',
    category: 'reformulation',
    level: 'C1',
    sentence: 'El protocolo resultó ineficaz. ___, fue un fracaso.',
    answer: 'Esto es',
    options: ['Esto es', 'Es decir', 'O sea', 'Es más'],
    explanation: '"Esto es" (that is) is a more literary/formal equivalent of "es decir." Often used in academic writing to provide a precise restatement.',
    explanationEs: '"Esto es" es un equivalente más literario/formal de "es decir". Se usa en escritura académica para ofrecer una reformulación precisa.',
  },
  {
    id: 'con-38',
    category: 'reformulation',
    level: 'A2',
    sentence: 'Trabajo de nueve a cinco, ___, ocho horas al día.',
    answer: 'o sea',
    options: ['o sea', 'sin embargo', 'en cambio', 'por último'],
    explanation: '"O sea" (that is / so basically) restates the same fact in different terms. Here it rephrases the schedule as a number of hours.',
    explanationEs: '"O sea" reformula el mismo dato en otros términos. Aquí replantea el horario como cantidad de horas.',
  },
];
