const FOLKTALES_DATA = [
  {
    id: "folktale-llorona",
    spanishName: "La Llorona",
    englishName: "The Weeping Woman",
    content: "<p><strong>La Llorona</strong> es una de las leyendas más famosas de Latinoamérica, especialmente popular en México, Guatemala y el suroeste de Estados Unidos. Cuenta la historia de una mujer hermosa llamada María que, enloquecida por los celos o la desesperación al ser abandonada por su esposo, ahogó a sus hijos en un río. Al darse cuenta de lo que hizo, murió de dolor y su espíritu quedó condenado a vagar por la eternidad buscando a sus hijos.</p><p>Se dice que por las noches, cerca de ríos, lagos y canales, se puede escuchar su lamento desgarrador: \"¡Ay, mis hijos!\" Los padres hispanohablantes han usado esta leyenda durante generaciones para advertir a los niños que no salgan de noche ni se acerquen al agua. La leyenda tiene variantes en casi todos los países latinoamericanos, y algunos historiadores la relacionan con diosas aztecas como Cihuacóatl.</p><p>La Llorona ha sido tema de películas, canciones, obras de teatro y literatura. La versión más conocida sitúa la historia en la época colonial, cuando María era una mujer indígena o mestiza enamorada de un hombre español de clase alta que la abandonó por una mujer de su mismo nivel social.</p>",
    quiz: [
      { question: "¿Qué hizo La Llorona con sus hijos según la leyenda?", options: ["Los abandonó en el bosque", "Los ahogó en un río", "Los envió a España", "Los dejó con su abuela"], answer: "Los ahogó en un río", explanation: "Según la leyenda, La Llorona ahogó a sus hijos en un río en un momento de desesperación o locura." },
      { question: "¿Qué frase se asocia con el lamento de La Llorona?", options: ["¡Ay, mi amor!", "¡Ay, mis hijos!", "¡Ay, qué dolor!", "¡Ay, mi vida!"], answer: "¡Ay, mis hijos!", explanation: "Su lamento más conocido es '¡Ay, mis hijos!' mientras busca a sus hijos por toda la eternidad." },
      { question: "¿Con qué diosa azteca se relaciona a veces esta leyenda?", options: ["Coatlicue", "Cihuacóatl", "Tlazoltéotl", "Xochiquetzal"], answer: "Cihuacóatl", explanation: "Algunos historiadores relacionan La Llorona con Cihuacóatl, diosa azteca que lloraba por sus hijos perdidos." }
    ]
  },
  {
    id: "folktale-eldorado",
    spanishName: "El Dorado",
    englishName: "The Golden One / The City of Gold",
    content: "<p><strong>El Dorado</strong> es una de las leyendas más influyentes de la historia de las Américas. Originalmente, \"El Dorado\" (\"El Hombre Dorado\") se refería a un cacique muisca que, durante una ceremonia ritual en la laguna de Guatavita en la actual Colombia, se cubría el cuerpo con polvo de oro antes de sumergirse en las aguas sagradas como ofrenda a los dioses.</p><p>Los conquistadores españoles que escucharon esta historia la transformaron en la leyenda de una ciudad entera hecha de oro, un reino de riquezas incalculables escondido en algún lugar de Sudamérica. Esta obsesión llevó a numerosas expediciones desastrosas por las selvas de Venezuela, Colombia, Brasil y Perú. Exploradores como Gonzalo Pizarro, Francisco de Orellana y Lope de Aguirre arriesgaron todo buscando esta ciudad mítica.</p><p>Aunque la ciudad de oro nunca existió, la ceremonia muisca en Guatavita era real. En 1969 se encontró la famosa Balsa Muisca, una pieza de orfebrería precolombina que representa la ceremonia, hoy exhibida en el Museo del Oro de Bogotá. La leyenda de El Dorado se ha convertido en una metáfora universal de la búsqueda obsesiva de riqueza imposible.</p>",
    quiz: [
      { question: "¿Qué era originalmente 'El Dorado'?", options: ["Una ciudad de oro", "Un cacique cubierto de polvo de oro", "Una mina de oro", "Un templo dorado"], answer: "Un cacique cubierto de polvo de oro", explanation: "Originalmente El Dorado era un cacique muisca que se cubría de polvo de oro para una ceremonia ritual." },
      { question: "¿En qué laguna se realizaba la ceremonia muisca?", options: ["Laguna de Tota", "Laguna de Guatavita", "Lago Titicaca", "Laguna de Términos"], answer: "Laguna de Guatavita", explanation: "La ceremonia ritual del cacique dorado se realizaba en la laguna de Guatavita, en la actual Colombia." },
      { question: "¿Dónde se exhibe la Balsa Muisca?", options: ["Museo Nacional de México", "Museo del Prado en Madrid", "Museo del Oro de Bogotá", "Museo Británico de Londres"], answer: "Museo del Oro de Bogotá", explanation: "La Balsa Muisca, que representa la ceremonia de El Dorado, se exhibe en el Museo del Oro de Bogotá." }
    ]
  },
  {
    id: "folktale-chupacabra",
    spanishName: "El Chupacabra",
    englishName: "The Goat Sucker",
    content: "<p><strong>El Chupacabra</strong> es una criatura legendaria del folclore contemporáneo latinoamericano. Los primeros reportes surgieron en Puerto Rico en 1995, cuando varios animales de granja, especialmente cabras, aparecieron muertos con marcas de punción en el cuello y completamente desangrados. De ahí el nombre: \"chupa\" (succiona) + \"cabra\" (goat) = el que chupa cabras.</p><p>La descripción original del Chupacabra lo presenta como una criatura bípeda de aproximadamente un metro de altura, con ojos grandes y rojos, piel grisácea o verde, espinas dorsales y colmillos afilados. Sin embargo, en Texas y México se han reportado versiones diferentes: animales cuadrúpedos sin pelo, parecidos a coyotes o perros enfermos con sarna.</p><p>La leyenda del Chupacabra se extendió rápidamente por todo el Caribe, México, Centroamérica y el sur de Estados Unidos. Aunque los científicos atribuyen las muertes de animales a depredadores comunes o enfermedades, y los \"chupacabras\" capturados han resultado ser coyotes con sarna, la criatura se ha convertido en un ícono de la cultura popular latinoamericana, apareciendo en películas, series, cómics y videojuegos.</p>",
    quiz: [
      { question: "¿Dónde se reportaron los primeros avistamientos del Chupacabra?", options: ["México", "Puerto Rico", "Texas", "Guatemala"], answer: "Puerto Rico", explanation: "Los primeros reportes del Chupacabra surgieron en Puerto Rico en 1995." },
      { question: "¿Qué significa literalmente 'Chupacabra'?", options: ["Come cabras", "Mata cabras", "Chupa cabras (les succiona la sangre)", "Caza cabras"], answer: "Chupa cabras (les succiona la sangre)", explanation: "El nombre viene de 'chupar' (succionar) y 'cabra', porque supuestamente les succionaba la sangre." },
      { question: "¿Qué explicación dan los científicos a los supuestos chupacabras capturados?", options: ["Murciélagos gigantes", "Experimentos militares", "Coyotes con sarna", "Especies desconocidas"], answer: "Coyotes con sarna", explanation: "Los científicos han determinado que los animales identificados como chupacabras son generalmente coyotes u otros cánidos con sarna severa." }
    ]
  },
  {
    id: "folktale-lechuza",
    spanishName: "La Lechuza",
    englishName: "The Owl Witch",
    content: "<p><strong>La Lechuza</strong> es una leyenda popular en el norte de México y el sur de Texas. Según la tradición, La Lechuza es una bruja que puede transformarse en un búho o lechuza gigante con rostro de mujer. Se dice que vuela por las noches buscando víctimas, especialmente hombres borrachos que caminan solos, niños desobedientes o personas que han ofendido a una bruja.</p><p>La leyenda cuenta que cuando escuchas el sonido de una lechuza cerca de tu casa, especialmente si es persistente e inusualmente fuerte, podría ser La Lechuza buscándote. Según la tradición, si sales a investigar el sonido, La Lechuza te atrapará con sus enormes garras y te llevará. Los remedios populares contra ella incluyen rezar, hacer la señal de la cruz, colgar sal en las ventanas o insultar al ave, lo cual supuestamente rompe el hechizo.</p><p>Esta leyenda tiene raíces en las creencias prehispánicas mesoamericanas sobre las mujeres nahuales (personas capaces de transformarse en animales) y en las supersticiones europeas sobre las brujas que se transformaban en aves nocturnas. La fusión de estas tradiciones durante la época colonial creó la leyenda de La Lechuza que conocemos hoy.</p>",
    quiz: [
      { question: "¿En qué se transforma La Lechuza?", options: ["En un gato negro", "En un búho gigante con rostro de mujer", "En una serpiente", "En un murciélago"], answer: "En un búho gigante con rostro de mujer", explanation: "Según la leyenda, La Lechuza es una bruja que se transforma en un búho o lechuza gigante con rostro humano." },
      { question: "¿En qué regiones es más popular esta leyenda?", options: ["Perú y Bolivia", "Norte de México y sur de Texas", "España y Portugal", "Argentina y Chile"], answer: "Norte de México y sur de Texas", explanation: "La leyenda de La Lechuza es especialmente popular en la frontera norte de México y el sur de Texas." },
      { question: "¿Qué tradición prehispánica se relaciona con La Lechuza?", options: ["Los sacrificios aztecas", "Las creencias en nahuales", "El calendario maya", "Los rituales incas"], answer: "Las creencias en nahuales", explanation: "La leyenda tiene raíces en la creencia mesoamericana de los nahuales, personas que podían transformarse en animales." }
    ]
  },
  {
    id: "folktale-silbon",
    spanishName: "El Silbón",
    englishName: "The Whistler",
    content: "<p><strong>El Silbón</strong> es una leyenda de los llanos de Venezuela y Colombia. Cuenta la historia de un joven que mató a su padre (las razones varían según la versión: por capricho, por vengar a su madre, o por servir sus vísceras como comida) y fue maldecido por su abuelo. Condenado a vagar eternamente cargando un saco con los huesos de su padre, El Silbón anuncia su presencia con un silbido escalofriante que recorre las notas musicales.</p><p>Lo más terrorífico de esta leyenda es la lógica invertida de su silbido: cuando se escucha lejos, El Silbón está cerca; cuando se escucha cerca, está lejos. Esta inversión crea una sensación de peligro impredecible. Se dice que El Silbón busca a hombres borrachos y mujeriegos para chupar su sangre o contarles los huesos del saco, lo cual causa la muerte de la víctima.</p><p>La leyenda del Silbón es tan importante en la cultura llanera que forma parte de la identidad regional de los estados Portuguesa, Barinas y Cojedes en Venezuela. Es la versión venezolana del \"espanto\" o fantasma errante, y los llaneros la utilizan para explicar sonidos misteriosos en las vastas llanuras durante la noche.</p>",
    quiz: [
      { question: "¿Qué carga El Silbón en su saco?", options: ["Oro robado", "Los huesos de su padre", "Almas de sus víctimas", "Piedras malditas"], answer: "Los huesos de su padre", explanation: "El Silbón fue condenado a cargar eternamente un saco con los huesos de su padre, a quien asesinó." },
      { question: "¿Qué particularidad tiene el silbido de El Silbón?", options: ["Solo se escucha de día", "Cuando suena lejos está cerca, y viceversa", "Suena como una canción alegre", "Solo lo escuchan los niños"], answer: "Cuando suena lejos está cerca, y viceversa", explanation: "El silbido tiene una lógica invertida: suena lejos cuando está cerca y cerca cuando está lejos." },
      { question: "¿En qué región es popular esta leyenda?", options: ["Los Andes peruanos", "Los llanos de Venezuela y Colombia", "La selva amazónica", "La Patagonia argentina"], answer: "Los llanos de Venezuela y Colombia", explanation: "El Silbón es una leyenda típica de los llanos venezolanos y colombianos." }
    ]
  },
  {
    id: "folktale-quijote",
    spanishName: "Don Quijote de la Mancha",
    englishName: "Don Quixote of La Mancha",
    content: "<p><strong>Don Quijote de la Mancha</strong>, escrito por Miguel de Cervantes y publicado en dos partes (1605 y 1615), es considerada la primera novela moderna y una de las obras más importantes de la literatura universal. La historia sigue a Alonso Quijano, un hidalgo manchego que enloquece de tanto leer novelas de caballerías y decide convertirse en caballero andante bajo el nombre de Don Quijote.</p><p>Acompañado por su fiel escudero Sancho Panza, un campesino práctico y sensato, Don Quijote recorre España buscando aventuras. Su episodio más famoso es la lucha contra los molinos de viento, que él confunde con gigantes. Mientras Don Quijote ve el mundo a través de su locura idealista, Sancho lo ve con pragmatismo terrenal. Esta dualidad entre idealismo y realismo es el corazón de la novela.</p><p>Don Quijote ha dado al español muchas expresiones: \"luchar contra molinos de viento\" (luchar contra enemigos imaginarios), \"quijotesco\" (idealista de forma impráctica), y \"la realidad supera la ficción\". La novela explora temas universales como la locura y la cordura, la realidad y la fantasía, la justicia y el amor idealizado, representado por Dulcinea del Toboso, la dama imaginaria de Don Quijote.</p>",
    quiz: [
      { question: "¿Quién escribió Don Quijote de la Mancha?", options: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Calderón de la Barca"], answer: "Miguel de Cervantes", explanation: "Miguel de Cervantes Saavedra escribió Don Quijote, publicado en 1605 (primera parte) y 1615 (segunda parte)." },
      { question: "¿Qué confunde Don Quijote con gigantes?", options: ["Árboles", "Castillos", "Molinos de viento", "Montañas"], answer: "Molinos de viento", explanation: "El episodio más famoso es cuando Don Quijote ataca los molinos de viento creyendo que son gigantes." },
      { question: "¿Cómo se llama el escudero de Don Quijote?", options: ["Sancho Panza", "Rocinante", "Dulcinea", "Alonso Quijano"], answer: "Sancho Panza", explanation: "Sancho Panza es el fiel escudero campesino que acompaña a Don Quijote en sus aventuras." }
    ]
  },
  {
    id: "folktale-cuco",
    spanishName: "El Cuco",
    englishName: "The Boogeyman",
    content: "<p><strong>El Cuco</strong> (también llamado El Coco, El Cucuy o El Cocó según la región) es la versión hispanohablante del \"hombre del saco\", una figura terrorífica usada tradicionalmente para asustar a los niños y hacer que se porten bien o se duerman. La frase clásica es: \"¡Duérmete, niño, que viene el Cuco!\"</p><p>A diferencia de otras criaturas del folclore hispano, El Cuco no tiene una apariencia definida. Es una presencia oscura, amorfa, que se esconde debajo de la cama, en el armario o en las sombras. Esto es parte de su poder: al no tener forma fija, cada niño imagina su propia versión del monstruo, lo que lo hace aún más aterrador. Algunas tradiciones lo describen como una figura encapuchada, un ser con ojos brillantes o simplemente una sombra.</p><p>La tradición del Cuco existe en España y en toda Latinoamérica, con variantes regionales. En España, la canción de cuna \"Duérmete, niño\" menciona al Coco. En México se le conoce más como El Cucuy. En Brasil es el Bicho-Papão. Aunque hoy los psicólogos infantiles desaconsejan usar el miedo como herramienta educativa, El Cuco sigue siendo una figura reconocible en la cultura hispana.</p>",
    quiz: [
      { question: "¿Para qué se usa la figura del Cuco tradicionalmente?", options: ["Para entretener a los niños", "Para asustar a los niños y que se porten bien o duerman", "Para enseñar historia", "Para celebrar fiestas"], answer: "Para asustar a los niños y que se porten bien o duerman", explanation: "El Cuco es una figura usada para asustar a los niños y hacer que obedezcan o se duerman." },
      { question: "¿Qué característica especial tiene la apariencia del Cuco?", options: ["Tiene cuernos rojos", "No tiene apariencia definida", "Es un animal grande", "Tiene alas"], answer: "No tiene apariencia definida", explanation: "El Cuco no tiene forma fija, lo que permite que cada niño imagine su propia versión aterradora." },
      { question: "¿Cómo se llama El Cuco en México?", options: ["El Coco", "El Cucuy", "El Coquito", "El Chucho"], answer: "El Cucuy", explanation: "En México, la versión del Cuco se conoce como El Cucuy." }
    ]
  },
  {
    id: "folktale-popolvuh",
    spanishName: "El Popol Vuh",
    englishName: "The Popol Vuh (Book of the Community)",
    content: "<p><strong>El Popol Vuh</strong> es el libro sagrado de los mayas quichés de Guatemala, considerado una de las obras literarias más importantes de la América precolombina. Contiene los mitos de creación del mundo, la historia de los dioses gemelos Hunahpú e Ixbalanqué, y la genealogía de los linajes quichés. Fue escrito en lengua quiché con caracteres latinos después de la conquista española.</p><p>Según el Popol Vuh, los dioses crearon a los seres humanos en varios intentos. Primero intentaron con barro, pero se deshacía. Luego con madera, pero los seres no tenían alma ni corazón. Finalmente, crearon a los humanos con maíz, el alimento sagrado mesoamericano. Esta creación a partir del maíz refleja la importancia central de este cultivo en la civilización maya y mesoamericana en general.</p><p>La parte más emocionante del Popol Vuh narra las aventuras de los Héroes Gemelos en Xibalbá, el inframundo maya. Hunahpú e Ixbalanqué vencen a los señores de la muerte mediante su astucia e inteligencia, no con fuerza bruta. El manuscrito fue descubierto por el fraile dominico Francisco Ximénez a principios del siglo XVIII en Chichicastenango, Guatemala, quien lo transcribió y tradujo al español.</p>",
    quiz: [
      { question: "¿De qué material fueron creados los humanos definitivos según el Popol Vuh?", options: ["De barro", "De madera", "De maíz", "De piedra"], answer: "De maíz", explanation: "Según el Popol Vuh, los dioses crearon exitosamente a los humanos a partir del maíz, alimento sagrado mesoamericano." },
      { question: "¿Cómo se llaman los Héroes Gemelos del Popol Vuh?", options: ["Quetzalcóatl y Tezcatlipoca", "Hunahpú e Ixbalanqué", "Kukulkán y Chaac", "Itzamná y Ix Chel"], answer: "Hunahpú e Ixbalanqué", explanation: "Los Héroes Gemelos son Hunahpú e Ixbalanqué, quienes descienden al inframundo Xibalbá." },
      { question: "¿Qué es Xibalbá en la mitología maya?", options: ["El cielo", "El inframundo", "Un volcán sagrado", "Un templo"], answer: "El inframundo", explanation: "Xibalbá es el inframundo maya, el reino de los muertos gobernado por los señores de la muerte." }
    ]
  },
  {
    id: "folktale-ciguapa",
    spanishName: "La Ciguapa",
    englishName: "The Ciguapa",
    content: "<p><strong>La Ciguapa</strong> es una criatura legendaria del folclore dominicano. Se describe como una mujer hermosa de largo cabello negro que le cubre todo el cuerpo como un manto, piel morena o azulada, y una característica única: sus pies están al revés, con los dedos apuntando hacia atrás. Esta peculiaridad hace imposible rastrearla, ya que sus huellas siempre apuntan en la dirección contraria a la que camina.</p><p>Las ciguapas habitan en las montañas y bosques profundos de la República Dominicana. Son criaturas nocturnas, tímidas y esquivas que bajan de las montañas por la noche para buscar comida o para observar a los humanos. Se dice que emiten un suave gemido o llanto, y que pueden hechizar a los hombres con su belleza. Según la leyenda, la única forma de capturar una ciguapa es durante la noche de luna llena, usando un perro cinqueño (un perro con dedos extra).</p><p>La Ciguapa es una de las figuras más queridas del folclore dominicano y simboliza la conexión del pueblo dominicano con la naturaleza de su isla. Algunos investigadores relacionan la leyenda con tradiciones taínas precolombinas, mientras que otros ven influencias africanas traídas durante la época colonial.</p>",
    quiz: [
      { question: "¿Qué característica única tienen los pies de La Ciguapa?", options: ["Son muy grandes", "Están al revés, con los dedos hacia atrás", "Son invisibles", "Tienen garras"], answer: "Están al revés, con los dedos hacia atrás", explanation: "Los pies de la Ciguapa apuntan hacia atrás, haciendo imposible rastrearla por sus huellas." },
      { question: "¿De qué país es originaria esta leyenda?", options: ["Cuba", "Puerto Rico", "República Dominicana", "Haití"], answer: "República Dominicana", explanation: "La Ciguapa es una criatura del folclore dominicano, asociada con las montañas y bosques de la isla." },
      { question: "¿Cómo se puede capturar a una Ciguapa según la leyenda?", options: ["Con una trampa de oro", "Con un perro cinqueño en luna llena", "Con sal bendita", "Con música de tambores"], answer: "Con un perro cinqueño en luna llena", explanation: "La tradición dice que solo se puede capturar una ciguapa durante la luna llena usando un perro cinqueño (con dedos extra)." }
    ]
  },
  {
    id: "folktale-cadejo",
    spanishName: "El Cadejo",
    englishName: "The Cadejo",
    content: "<p><strong>El Cadejo</strong> es una leyenda popular en Centroamérica, especialmente en Guatemala, El Salvador, Honduras, Nicaragua y Costa Rica. Se trata de dos perros sobrenaturales: uno blanco y uno negro. El Cadejo blanco es un espíritu protector que cuida a los viajeros nocturnos, borrachos y personas perdidas, guiándolos a casa seguros. El Cadejo negro, en cambio, es una criatura maligna que busca robar el alma de sus víctimas.</p><p>Se dice que los Cadejos aparecen en caminos solitarios durante la noche. El Cadejo blanco tiene ojos azules bondadosos y un aura de paz, mientras que el Cadejo negro tiene ojos rojos ardientes, cadenas arrastrándose, olor a azufre y un aura de terror. Cuando ambos cadejos aparecen juntos, luchan entre sí por el alma del viajero, representando la eterna batalla entre el bien y el mal.</p><p>La leyenda del Cadejo tiene raíces tanto en las tradiciones indígenas mesoamericanas como en el cristianismo colonial. El concepto de espíritus animales protectores es común en las culturas maya y náhuatl, mientras que la dualidad blanco/negro y la lucha entre el bien y el mal reflejan la influencia cristiana. En El Salvador, el Cadejo es tan importante culturalmente que una marca de cerveza y un equipo de fútbol llevan su nombre.</p>",
    quiz: [
      { question: "¿Qué diferencia hay entre el Cadejo blanco y el negro?", options: ["Son del mismo tamaño pero diferente color", "El blanco protege y el negro es maligno", "El blanco es más grande", "El negro es más rápido"], answer: "El blanco protege y el negro es maligno", explanation: "El Cadejo blanco es protector y guía a los viajeros, mientras que el negro es maligno y busca robar almas." },
      { question: "¿En qué región es más popular la leyenda del Cadejo?", options: ["Sudamérica", "Centroamérica", "El Caribe", "España"], answer: "Centroamérica", explanation: "El Cadejo es una leyenda popular en Guatemala, El Salvador, Honduras, Nicaragua y Costa Rica." },
      { question: "¿A quiénes suele aparecer el Cadejo?", options: ["A los niños durante el día", "A los viajeros nocturnos y personas perdidas", "A los sacerdotes", "A las mujeres embarazadas"], answer: "A los viajeros nocturnos y personas perdidas", explanation: "Los Cadejos aparecen a viajeros nocturnos, personas perdidas y borrachos en caminos solitarios." }
    ]
  },
  {
    id: "folktale-quetzalcoatl",
    spanishName: "Quetzalcóatl - La Serpiente Emplumada",
    englishName: "Quetzalcoatl - The Feathered Serpent",
    content: "<p><strong>Quetzalcóatl</strong>, la Serpiente Emplumada, es una de las deidades más importantes de Mesoamérica. Su nombre viene del náhuatl: \"quetzal\" (un ave de plumaje precioso) y \"cóatl\" (serpiente). Era el dios del viento, del conocimiento, de la estrella de la mañana y era considerado el creador de la humanidad. Su culto se extendió por toda Mesoamérica bajo diferentes nombres: Kukulkán para los mayas y Gucumatz para los quichés.</p><p>Según la leyenda azteca, Quetzalcóatl fue un dios-rey que gobernó la legendaria ciudad de Tula con sabiduría y bondad. Se opuso a los sacrificios humanos y enseñó a los hombres la agricultura, el calendario, las artes y la escritura. Sin embargo, su rival Tezcatlipoca lo engañó haciéndolo emborracharse y cometer actos vergonzosos. Avergonzado, Quetzalcóatl partió hacia el este en una balsa de serpientes, prometiendo regresar algún día.</p><p>Esta promesa de retorno tuvo consecuencias históricas enormes. Cuando Hernán Cortés llegó a México en 1519 desde el este, algunos creen que el emperador Moctezuma lo confundió con el regreso de Quetzalcóatl, lo que facilitó la conquista española. Aunque esta interpretación es debatida por los historiadores modernos, la leyenda de Quetzalcóatl sigue siendo fundamental para entender la mitología y la historia de México.</p>",
    quiz: [
      { question: "¿Qué significa 'Quetzalcóatl' en náhuatl?", options: ["Dios del sol", "Serpiente emplumada", "Águila dorada", "Guerrero sagrado"], answer: "Serpiente emplumada", explanation: "'Quetzal' es un ave de plumaje precioso y 'cóatl' significa serpiente, formando 'Serpiente Emplumada'." },
      { question: "¿Cómo se llamaba Quetzalcóatl entre los mayas?", options: ["Chaac", "Kukulkán", "Itzamná", "Hunab Ku"], answer: "Kukulkán", explanation: "Los mayas conocían a la Serpiente Emplumada como Kukulkán." },
      { question: "¿Qué prometió Quetzalcóatl al partir hacia el este?", options: ["Destruir el mundo", "Regresar algún día", "Enviar lluvia", "Crear nuevos dioses"], answer: "Regresar algún día", explanation: "Quetzalcóatl prometió regresar, una profecía que algunos creen influyó en la reacción azteca ante la llegada de Cortés." }
    ]
  },
  {
    id: "folktale-sombreron",
    spanishName: "El Sombrerón",
    englishName: "The Man with the Big Hat",
    content: "<p><strong>El Sombrerón</strong> es una de las leyendas más populares de Guatemala, aunque también se conoce en otros países centroamericanos y en México. Se describe como un hombre muy pequeño, vestido todo de negro, con un enorme sombrero negro, botas con espuelas y una guitarra plateada. Monta un caballo negro o una mula y va acompañado de cuatro mulas cargadas con tesoros.</p><p>Según la leyenda, El Sombrerón se enamora de mujeres jóvenes de ojos grandes y cabello largo y negro. Cuando encuentra a una que le gusta, les trenza el cabello a ellas y a sus mulas durante la noche, les canta serenatas con su guitarra y les espolvorea tierra en la comida para que no puedan comer y se debiliten. Las víctimas del Sombrerón pierden el apetito, no pueden dormir y se enferman de tristeza y melancolía.</p><p>El remedio tradicional contra El Sombrerón es cortarle el cabello a la mujer afectada (ya que él se enamora del cabello largo) o mudarse a otra ciudad. En la cultura guatemalteca, El Sombrerón es una figura ambigua: es aterrador pero también romántico y trágico. Su historia ha sido tema de canciones, obras de teatro y es parte integral de las tradiciones orales de La Antigua Guatemala, donde se dice que sus serenatas aún se escuchan en las calles coloniales.</p>",
    quiz: [
      { question: "¿Cómo se describe físicamente al Sombrerón?", options: ["Alto y rubio", "Pequeño, vestido de negro con un gran sombrero", "Grande y musculoso", "Viejo con barba blanca"], answer: "Pequeño, vestido de negro con un gran sombrero", explanation: "El Sombrerón es un hombre muy pequeño vestido de negro con un enorme sombrero negro y una guitarra plateada." },
      { question: "¿Qué les hace a las mujeres que le gustan?", options: ["Las secuestra", "Les trenza el cabello y les canta serenatas", "Les regala oro", "Las convierte en animales"], answer: "Les trenza el cabello y les canta serenatas", explanation: "El Sombrerón trenza el cabello de las mujeres, les canta serenatas y les pone tierra en la comida para que no coman." },
      { question: "¿Cuál es el remedio tradicional contra El Sombrerón?", options: ["Rezar tres rosarios", "Cortarle el cabello a la mujer afectada", "Quemar incienso", "Poner ajo en las ventanas"], answer: "Cortarle el cabello a la mujer afectada", explanation: "Como El Sombrerón se enamora del cabello largo, cortarlo rompe su encantamiento." }
    ]
  }
];
