const FOLKTALES_DATA = [
  {
    id: "folktale-llorona",
    spanishName: "La Llorona",
    englishName: "The Weeping Woman",
    content: "<p><strong>La Llorona</strong> es una de las leyendas más famosas de Latinoamérica, especialmente popular en México, Guatemala y el suroeste de Estados Unidos. Cuenta la historia de una mujer hermosa llamada María que, enloquecida por los celos o la desesperación al ser abandonada por su esposo, ahogó a sus hijos en un río. Al darse cuenta de lo que hizo, murió de dolor y su espíritu quedó condenado a vagar por la eternidad buscando a sus hijos.</p><p>Se dice que por las noches, cerca de ríos, lagos y canales, se puede escuchar su lamento desgarrador: \"¡Ay, mis hijos!\" Los padres hispanohablantes han usado esta leyenda durante generaciones para advertir a los niños que no salgan de noche ni se acerquen al agua. La leyenda tiene variantes en casi todos los países latinoamericanos, y algunos historiadores la relacionan con diosas aztecas como Cihuacóatl.</p><p>La Llorona ha sido tema de películas, canciones, obras de teatro y literatura. La versión más conocida sitúa la historia en la época colonial, cuando María era una mujer indígena o mestiza enamorada de un hombre español de clase alta que la abandonó por una mujer de su mismo nivel social.</p>",
    quiz: [
      { question: "¿Qué hizo La Llorona con sus hijos según la leyenda?", options: ["Los abandonó en el bosque", "Los ahogó en un río", "Los envió a España", "Los dejó con su abuela"], answer: "Los ahogó en un río", explanation: "The drowning is the central act that condemns her spirit. It reflects a common motif in Latin American folklore where extreme emotional acts—driven by jealousy or abandonment—lead to eternal supernatural punishment." },
      { question: "¿Qué frase se asocia con el lamento de La Llorona?", options: ["¡Ay, mi amor!", "¡Ay, mis hijos!", "¡Ay, qué dolor!", "¡Ay, mi vida!"], answer: "¡Ay, mis hijos!", explanation: "The cry '¡Ay, mis hijos!' ('Oh, my children!') is a direct expression of maternal grief. This phrase is so iconic that hearing it near water at night is considered an omen throughout Latin America." },
      { question: "¿Con qué diosa azteca se relaciona a veces esta leyenda?", options: ["Coatlicue", "Cihuacóatl", "Tlazoltéotl", "Xochiquetzal"], answer: "Cihuacóatl", explanation: "Cihuacóatl was an Aztec goddess associated with motherhood and loss who was said to wail at night—a striking parallel. This connection suggests the La Llorona legend may predate Spanish colonization and blend indigenous and colonial traditions." }
    ]
  },
  {
    id: "folktale-eldorado",
    spanishName: "El Dorado",
    englishName: "The Golden One / The City of Gold",
    content: "<p><strong>El Dorado</strong> es una de las leyendas más influyentes de la historia de las Américas. Originalmente, \"El Dorado\" (\"El Hombre Dorado\") se refería a un cacique muisca que, durante una ceremonia ritual en la laguna de Guatavita en la actual Colombia, se cubría el cuerpo con polvo de oro antes de sumergirse en las aguas sagradas como ofrenda a los dioses.</p><p>Los conquistadores españoles que escucharon esta historia la transformaron en la leyenda de una ciudad entera hecha de oro, un reino de riquezas incalculables escondido en algún lugar de Sudamérica. Esta obsesión llevó a numerosas expediciones desastrosas por las selvas de Venezuela, Colombia, Brasil y Perú. Exploradores como Gonzalo Pizarro, Francisco de Orellana y Lope de Aguirre arriesgaron todo buscando esta ciudad mítica.</p><p>Aunque la ciudad de oro nunca existió, la ceremonia muisca en Guatavita era real. En 1969 se encontró la famosa Balsa Muisca, una pieza de orfebrería precolombina que representa la ceremonia, hoy exhibida en el Museo del Oro de Bogotá. La leyenda de El Dorado se ha convertido en una metáfora universal de la búsqueda obsesiva de riqueza imposible.</p>",
    quiz: [
      { question: "¿Qué era originalmente 'El Dorado'?", options: ["Una ciudad de oro", "Un cacique cubierto de polvo de oro", "Una mina de oro", "Un templo dorado"], answer: "Un cacique cubierto de polvo de oro", explanation: "The Spanish conquistadors misunderstood the Muisca ritual: 'El Dorado' originally meant 'The Golden Man,' not a golden city. The Muisca cacique covered himself in gold dust as a religious offering, but the Spanish transformed this into a myth of an entire city of gold." },
      { question: "¿En qué laguna se realizaba la ceremonia muisca?", options: ["Laguna de Tota", "Laguna de Guatavita", "Lago Titicaca", "Laguna de Términos"], answer: "Laguna de Guatavita", explanation: "Lake Guatavita, located in the highlands near Bogota, Colombia, was sacred to the Muisca people. Multiple attempts have been made to drain the lake to recover gold offerings from its bottom, including one by the Spanish in the 1500s." },
      { question: "¿Dónde se exhibe la Balsa Muisca?", options: ["Museo Nacional de México", "Museo del Prado en Madrid", "Museo del Oro de Bogotá", "Museo Británico de Londres"], answer: "Museo del Oro de Bogotá", explanation: "The Muisca Raft is a pre-Columbian gold artifact discovered in 1969 that physically depicts the El Dorado ceremony. The Museo del Oro in Bogota holds over 55,000 gold pieces, making it one of the most important pre-Columbian collections in the world." }
    ]
  },
  {
    id: "folktale-chupacabra",
    spanishName: "El Chupacabra",
    englishName: "The Goat Sucker",
    content: "<p><strong>El Chupacabra</strong> es una criatura legendaria del folclore contemporáneo latinoamericano. Los primeros reportes surgieron en Puerto Rico en 1995, cuando varios animales de granja, especialmente cabras, aparecieron muertos con marcas de punción en el cuello y completamente desangrados. De ahí el nombre: \"chupa\" (succiona) + \"cabra\" (goat) = el que chupa cabras.</p><p>La descripción original del Chupacabra lo presenta como una criatura bípeda de aproximadamente un metro de altura, con ojos grandes y rojos, piel grisácea o verde, espinas dorsales y colmillos afilados. Sin embargo, en Texas y México se han reportado versiones diferentes: animales cuadrúpedos sin pelo, parecidos a coyotes o perros enfermos con sarna.</p><p>La leyenda del Chupacabra se extendió rápidamente por todo el Caribe, México, Centroamérica y el sur de Estados Unidos. Aunque los científicos atribuyen las muertes de animales a depredadores comunes o enfermedades, y los \"chupacabras\" capturados han resultado ser coyotes con sarna, la criatura se ha convertido en un ícono de la cultura popular latinoamericana, apareciendo en películas, series, cómics y videojuegos.</p>",
    quiz: [
      { question: "¿Dónde se reportaron los primeros avistamientos del Chupacabra?", options: ["México", "Puerto Rico", "Texas", "Guatemala"], answer: "Puerto Rico", explanation: "The Chupacabra legend began in Puerto Rico in 1995 when livestock were found drained of blood with puncture wounds. Unlike most Latin American folklore, this is a modern legend—making it one of the few cryptid myths to originate in the late 20th century." },
      { question: "¿Qué significa literalmente 'Chupacabra'?", options: ["Come cabras", "Mata cabras", "Chupa cabras (les succiona la sangre)", "Caza cabras"], answer: "Chupa cabras (les succiona la sangre)", explanation: "The name is a compound word: 'chupar' (to suck/drain) + 'cabra' (goat). This is a great example of how Spanish forms descriptive compound words—the verb stem plus the noun it acts upon, similar to 'espantapájaros' (scarecrow) or 'rascacielos' (skyscraper)." },
      { question: "¿Qué explicación dan los científicos a los supuestos chupacabras capturados?", options: ["Murciélagos gigantes", "Experimentos militares", "Coyotes con sarna", "Especies desconocidas"], answer: "Coyotes con sarna", explanation: "Sarcoptic mange causes severe hair loss and skin thickening in canids, making them look alien and unrecognizable. Every 'chupacabra' specimen that has been scientifically examined has turned out to be a coyote, dog, or raccoon suffering from this parasitic disease." }
    ]
  },
  {
    id: "folktale-lechuza",
    spanishName: "La Lechuza",
    englishName: "The Owl Witch",
    content: "<p><strong>La Lechuza</strong> es una leyenda popular en el norte de México y el sur de Texas. Según la tradición, La Lechuza es una bruja que puede transformarse en un búho o lechuza gigante con rostro de mujer. Se dice que vuela por las noches buscando víctimas, especialmente hombres borrachos que caminan solos, niños desobedientes o personas que han ofendido a una bruja.</p><p>La leyenda cuenta que cuando escuchas el sonido de una lechuza cerca de tu casa, especialmente si es persistente e inusualmente fuerte, podría ser La Lechuza buscándote. Según la tradición, si sales a investigar el sonido, La Lechuza te atrapará con sus enormes garras y te llevará. Los remedios populares contra ella incluyen rezar, hacer la señal de la cruz, colgar sal en las ventanas o insultar al ave, lo cual supuestamente rompe el hechizo.</p><p>Esta leyenda tiene raíces en las creencias prehispánicas mesoamericanas sobre las mujeres nahuales (personas capaces de transformarse en animales) y en las supersticiones europeas sobre las brujas que se transformaban en aves nocturnas. La fusión de estas tradiciones durante la época colonial creó la leyenda de La Lechuza que conocemos hoy.</p>",
    quiz: [
      { question: "¿En qué se transforma La Lechuza?", options: ["En un gato negro", "En un búho gigante con rostro de mujer", "En una serpiente", "En un murciélago"], answer: "En un búho gigante con rostro de mujer", explanation: "The human face on an owl body makes La Lechuza a shapeshifter that retains traces of her human identity. This detail connects to the Mesoamerican belief in nahuales—people who could transform into animals while keeping part of their human essence." },
      { question: "¿En qué regiones es más popular esta leyenda?", options: ["Perú y Bolivia", "Norte de México y sur de Texas", "España y Portugal", "Argentina y Chile"], answer: "Norte de México y sur de Texas", explanation: "This border region has a rich tradition of shared folklore between Mexican and Mexican-American communities. La Lechuza thrives in this cultural zone where rural isolation, bilingualism, and blended indigenous-Catholic beliefs keep oral traditions alive." },
      { question: "¿Qué tradición prehispánica se relaciona con La Lechuza?", options: ["Los sacrificios aztecas", "Las creencias en nahuales", "El calendario maya", "Los rituales incas"], answer: "Las creencias en nahuales", explanation: "Nahualism is a pre-Columbian Mesoamerican belief that certain people possess the power to shapeshift into animal forms. The word 'nahual' comes from Nahuatl, and this belief system merged with European witchcraft traditions during colonization to produce legends like La Lechuza." }
    ]
  },
  {
    id: "folktale-silbon",
    spanishName: "El Silbón",
    englishName: "The Whistler",
    content: "<p><strong>El Silbón</strong> es una leyenda de los llanos de Venezuela y Colombia. Cuenta la historia de un joven que mató a su padre (las razones varían según la versión: por capricho, por vengar a su madre, o por servir sus vísceras como comida) y fue maldecido por su abuelo. Condenado a vagar eternamente cargando un saco con los huesos de su padre, El Silbón anuncia su presencia con un silbido escalofriante que recorre las notas musicales.</p><p>Lo más terrorífico de esta leyenda es la lógica invertida de su silbido: cuando se escucha lejos, El Silbón está cerca; cuando se escucha cerca, está lejos. Esta inversión crea una sensación de peligro impredecible. Se dice que El Silbón busca a hombres borrachos y mujeriegos para chupar su sangre o contarles los huesos del saco, lo cual causa la muerte de la víctima.</p><p>La leyenda del Silbón es tan importante en la cultura llanera que forma parte de la identidad regional de los estados Portuguesa, Barinas y Cojedes en Venezuela. Es la versión venezolana del \"espanto\" o fantasma errante, y los llaneros la utilizan para explicar sonidos misteriosos en las vastas llanuras durante la noche.</p>",
    quiz: [
      { question: "¿Qué carga El Silbón en su saco?", options: ["Oro robado", "Los huesos de su padre", "Almas de sus víctimas", "Piedras malditas"], answer: "Los huesos de su padre", explanation: "Carrying his father's bones is both his punishment and his identity—the bag of bones rattling is one of the warning signs of his approach. This motif of a murderer eternally bound to the evidence of their crime appears across many folklore traditions." },
      { question: "¿Qué particularidad tiene el silbido de El Silbón?", options: ["Solo se escucha de día", "Cuando suena lejos está cerca, y viceversa", "Suena como una canción alegre", "Solo lo escuchan los niños"], answer: "Cuando suena lejos está cerca, y viceversa", explanation: "This inverted logic—hearing the whistle far away means danger is near—creates a uniquely terrifying effect because your instincts betray you. It reflects the unpredictable dangers of traveling the vast, isolated Venezuelan and Colombian plains at night." },
      { question: "¿En qué región es popular esta leyenda?", options: ["Los Andes peruanos", "Los llanos de Venezuela y Colombia", "La selva amazónica", "La Patagonia argentina"], answer: "Los llanos de Venezuela y Colombia", explanation: "The llanos are vast tropical grasslands stretching across Venezuela and Colombia. Their flat, open landscape and isolation make them a perfect setting for this legend, as sounds travel unpredictably across the plains and travelers are vulnerable at night." }
    ]
  },
  {
    id: "folktale-quijote",
    spanishName: "Don Quijote de la Mancha",
    englishName: "Don Quixote of La Mancha",
    content: "<p><strong>Don Quijote de la Mancha</strong>, escrito por Miguel de Cervantes y publicado en dos partes (1605 y 1615), es considerada la primera novela moderna y una de las obras más importantes de la literatura universal. La historia sigue a Alonso Quijano, un hidalgo manchego que enloquece de tanto leer novelas de caballerías y decide convertirse en caballero andante bajo el nombre de Don Quijote.</p><p>Acompañado por su fiel escudero Sancho Panza, un campesino práctico y sensato, Don Quijote recorre España buscando aventuras. Su episodio más famoso es la lucha contra los molinos de viento, que él confunde con gigantes. Mientras Don Quijote ve el mundo a través de su locura idealista, Sancho lo ve con pragmatismo terrenal. Esta dualidad entre idealismo y realismo es el corazón de la novela.</p><p>Don Quijote ha dado al español muchas expresiones: \"luchar contra molinos de viento\" (luchar contra enemigos imaginarios), \"quijotesco\" (idealista de forma impráctica), y \"la realidad supera la ficción\". La novela explora temas universales como la locura y la cordura, la realidad y la fantasía, la justicia y el amor idealizado, representado por Dulcinea del Toboso, la dama imaginaria de Don Quijote.</p>",
    quiz: [
      { question: "¿Quién escribió Don Quijote de la Mancha?", options: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Calderón de la Barca"], answer: "Miguel de Cervantes", explanation: "Cervantes published the two parts a decade apart (1605 and 1615), and the novel is widely considered the first modern novel in Western literature. Cervantes wrote it partly as a satire of the chivalric romances that were wildly popular in his era." },
      { question: "¿Qué confunde Don Quijote con gigantes?", options: ["Árboles", "Castillos", "Molinos de viento", "Montañas"], answer: "Molinos de viento", explanation: "This scene is so iconic that 'tilting at windmills' has become an idiom in many languages meaning to fight imaginary enemies. In Spanish, 'luchar contra molinos de viento' carries the same meaning and is one of many everyday expressions that originated from this novel." },
      { question: "¿Cómo se llama el escudero de Don Quijote?", options: ["Sancho Panza", "Rocinante", "Dulcinea", "Alonso Quijano"], answer: "Sancho Panza", explanation: "Sancho Panza represents earthy pragmatism as a counterpoint to Don Quijote's idealism. Their dynamic—dreamer versus realist—is one of the most influential character pairings in world literature. Note: 'Rocinante' is Don Quijote's horse, and 'Dulcinea' is his imagined lady love." }
    ]
  },
  {
    id: "folktale-cuco",
    spanishName: "El Cuco",
    englishName: "The Boogeyman",
    content: "<p><strong>El Cuco</strong> (también llamado El Coco, El Cucuy o El Cocó según la región) es la versión hispanohablante del \"hombre del saco\", una figura terrorífica usada tradicionalmente para asustar a los niños y hacer que se porten bien o se duerman. La frase clásica es: \"¡Duérmete, niño, que viene el Cuco!\"</p><p>A diferencia de otras criaturas del folclore hispano, El Cuco no tiene una apariencia definida. Es una presencia oscura, amorfa, que se esconde debajo de la cama, en el armario o en las sombras. Esto es parte de su poder: al no tener forma fija, cada niño imagina su propia versión del monstruo, lo que lo hace aún más aterrador. Algunas tradiciones lo describen como una figura encapuchada, un ser con ojos brillantes o simplemente una sombra.</p><p>La tradición del Cuco existe en España y en toda Latinoamérica, con variantes regionales. En España, la canción de cuna \"Duérmete, niño\" menciona al Coco. En México se le conoce más como El Cucuy. En Brasil es el Bicho-Papão. Aunque hoy los psicólogos infantiles desaconsejan usar el miedo como herramienta educativa, El Cuco sigue siendo una figura reconocible en la cultura hispana.</p>",
    quiz: [
      { question: "¿Para qué se usa la figura del Cuco tradicionalmente?", options: ["Para entretener a los niños", "Para asustar a los niños y que se porten bien o duerman", "Para enseñar historia", "Para celebrar fiestas"], answer: "Para asustar a los niños y que se porten bien o duerman", explanation: "El Cuco serves the same social function as the Boogeyman in English-speaking cultures—an authority figure parents invoke to enforce bedtime and good behavior. The classic lullaby threat 'Duermete, nino, que viene el Cuco' has been passed down for centuries across the Spanish-speaking world." },
      { question: "¿Qué característica especial tiene la apariencia del Cuco?", options: ["Tiene cuernos rojos", "No tiene apariencia definida", "Es un animal grande", "Tiene alas"], answer: "No tiene apariencia definida", explanation: "The lack of a defined form is psychologically powerful—each child projects their own deepest fears onto El Cuco. This ambiguity distinguishes El Cuco from other folklore creatures that have specific physical descriptions, making it arguably more frightening." },
      { question: "¿Cómo se llama El Cuco en México?", options: ["El Coco", "El Cucuy", "El Coquito", "El Chucho"], answer: "El Cucuy", explanation: "Regional name variations reflect how Spanish dialects diverge across countries: 'El Cuco' in the Caribbean, 'El Cucuy' in Mexico, 'El Coco' in Spain, and 'Bicho-Papao' in Portuguese-speaking Brazil. These variations show how a shared cultural concept adapts linguistically across regions." }
    ]
  },
  {
    id: "folktale-popolvuh",
    spanishName: "El Popol Vuh",
    englishName: "The Popol Vuh (Book of the Community)",
    content: "<p><strong>El Popol Vuh</strong> es el libro sagrado de los mayas quichés de Guatemala, considerado una de las obras literarias más importantes de la América precolombina. Contiene los mitos de creación del mundo, la historia de los dioses gemelos Hunahpú e Ixbalanqué, y la genealogía de los linajes quichés. Fue escrito en lengua quiché con caracteres latinos después de la conquista española.</p><p>Según el Popol Vuh, los dioses crearon a los seres humanos en varios intentos. Primero intentaron con barro, pero se deshacía. Luego con madera, pero los seres no tenían alma ni corazón. Finalmente, crearon a los humanos con maíz, el alimento sagrado mesoamericano. Esta creación a partir del maíz refleja la importancia central de este cultivo en la civilización maya y mesoamericana en general.</p><p>La parte más emocionante del Popol Vuh narra las aventuras de los Héroes Gemelos en Xibalbá, el inframundo maya. Hunahpú e Ixbalanqué vencen a los señores de la muerte mediante su astucia e inteligencia, no con fuerza bruta. El manuscrito fue descubierto por el fraile dominico Francisco Ximénez a principios del siglo XVIII en Chichicastenango, Guatemala, quien lo transcribió y tradujo al español.</p>",
    quiz: [
      { question: "¿De qué material fueron creados los humanos definitivos según el Popol Vuh?", options: ["De barro", "De madera", "De maíz", "De piedra"], answer: "De maíz", explanation: "Maize was not just food but the foundation of Mesoamerican civilization—it was domesticated from wild teosinte over thousands of years. The Maya believed humans were literally made of corn, reflecting how central this crop was to their identity, economy, and spirituality." },
      { question: "¿Cómo se llaman los Héroes Gemelos del Popol Vuh?", options: ["Quetzalcóatl y Tezcatlipoca", "Hunahpú e Ixbalanqué", "Kukulkán y Chaac", "Itzamná y Ix Chel"], answer: "Hunahpú e Ixbalanqué", explanation: "Hunahpu and Ixbalanque defeated the Lords of Death through cleverness rather than brute force, making them trickster heroes. The other options are Aztec deities (Quetzalcoatl, Tezcatlipoca) or Maya gods (Kukulkan, Chaac, Itzamna, Ix Chel) from different mythological traditions." },
      { question: "¿Qué es Xibalbá en la mitología maya?", options: ["El cielo", "El inframundo", "Un volcán sagrado", "Un templo"], answer: "El inframundo", explanation: "Xibalba (roughly meaning 'place of fright') was the Maya underworld, a dangerous multi-level realm ruled by death gods. Unlike the Christian concept of hell, Xibalba could be visited by the living and its lords could be outwitted, as the Hero Twins demonstrated." }
    ]
  },
  {
    id: "folktale-ciguapa",
    spanishName: "La Ciguapa",
    englishName: "The Ciguapa",
    content: "<p><strong>La Ciguapa</strong> es una criatura legendaria del folclore dominicano. Se describe como una mujer hermosa de largo cabello negro que le cubre todo el cuerpo como un manto, piel morena o azulada, y una característica única: sus pies están al revés, con los dedos apuntando hacia atrás. Esta peculiaridad hace imposible rastrearla, ya que sus huellas siempre apuntan en la dirección contraria a la que camina.</p><p>Las ciguapas habitan en las montañas y bosques profundos de la República Dominicana. Son criaturas nocturnas, tímidas y esquivas que bajan de las montañas por la noche para buscar comida o para observar a los humanos. Se dice que emiten un suave gemido o llanto, y que pueden hechizar a los hombres con su belleza. Según la leyenda, la única forma de capturar una ciguapa es durante la noche de luna llena, usando un perro cinqueño (un perro con dedos extra).</p><p>La Ciguapa es una de las figuras más queridas del folclore dominicano y simboliza la conexión del pueblo dominicano con la naturaleza de su isla. Algunos investigadores relacionan la leyenda con tradiciones taínas precolombinas, mientras que otros ven influencias africanas traídas durante la época colonial.</p>",
    quiz: [
      { question: "¿Qué característica única tienen los pies de La Ciguapa?", options: ["Son muy grandes", "Están al revés, con los dedos hacia atrás", "Son invisibles", "Tienen garras"], answer: "Están al revés, con los dedos hacia atrás", explanation: "The backward feet are a clever mythological detail: anyone trying to track a Ciguapa by her footprints would walk in the opposite direction. This feature makes her fundamentally elusive and symbolizes the untameable mystery of the Dominican wilderness." },
      { question: "¿De qué país es originaria esta leyenda?", options: ["Cuba", "Puerto Rico", "República Dominicana", "Haití"], answer: "República Dominicana", explanation: "The Ciguapa is uniquely Dominican and is one of the country's most cherished folklore figures. Some scholars trace her origins to Taino indigenous traditions, while others see African influences—reflecting the Dominican Republic's blended cultural heritage." },
      { question: "¿Cómo se puede capturar a una Ciguapa según la leyenda?", options: ["Con una trampa de oro", "Con un perro cinqueño en luna llena", "Con sal bendita", "Con música de tambores"], answer: "Con un perro cinqueño en luna llena", explanation: "A 'perro cinqueño' is a dog born with extra toes (polydactyly), considered to have supernatural tracking abilities in Dominican folk belief. The full-moon requirement adds to the difficulty, reinforcing the idea that Ciguapas are nearly impossible to catch." }
    ]
  },
  {
    id: "folktale-cadejo",
    spanishName: "El Cadejo",
    englishName: "The Cadejo",
    content: "<p><strong>El Cadejo</strong> es una leyenda popular en Centroamérica, especialmente en Guatemala, El Salvador, Honduras, Nicaragua y Costa Rica. Se trata de dos perros sobrenaturales: uno blanco y uno negro. El Cadejo blanco es un espíritu protector que cuida a los viajeros nocturnos, borrachos y personas perdidas, guiándolos a casa seguros. El Cadejo negro, en cambio, es una criatura maligna que busca robar el alma de sus víctimas.</p><p>Se dice que los Cadejos aparecen en caminos solitarios durante la noche. El Cadejo blanco tiene ojos azules bondadosos y un aura de paz, mientras que el Cadejo negro tiene ojos rojos ardientes, cadenas arrastrándose, olor a azufre y un aura de terror. Cuando ambos cadejos aparecen juntos, luchan entre sí por el alma del viajero, representando la eterna batalla entre el bien y el mal.</p><p>La leyenda del Cadejo tiene raíces tanto en las tradiciones indígenas mesoamericanas como en el cristianismo colonial. El concepto de espíritus animales protectores es común en las culturas maya y náhuatl, mientras que la dualidad blanco/negro y la lucha entre el bien y el mal reflejan la influencia cristiana. En El Salvador, el Cadejo es tan importante culturalmente que una marca de cerveza y un equipo de fútbol llevan su nombre.</p>",
    quiz: [
      { question: "¿Qué diferencia hay entre el Cadejo blanco y el negro?", options: ["Son del mismo tamaño pero diferente color", "El blanco protege y el negro es maligno", "El blanco es más grande", "El negro es más rápido"], answer: "El blanco protege y el negro es maligno", explanation: "This duality reflects the blending of indigenous Mesoamerican spirit-animal beliefs with Christian good-versus-evil symbolism brought by colonizers. When both Cadejos appear together, they literally fight each other for the traveler's soul, dramatizing the moral struggle between protection and temptation." },
      { question: "¿En qué región es más popular la leyenda del Cadejo?", options: ["Sudamérica", "Centroamérica", "El Caribe", "España"], answer: "Centroamérica", explanation: "The Cadejo spans five Central American nations, making it one of the region's most widespread shared legends. In El Salvador, the Cadejo is so culturally significant that a popular beer brand and a football team are named after it." },
      { question: "¿A quiénes suele aparecer el Cadejo?", options: ["A los niños durante el día", "A los viajeros nocturnos y personas perdidas", "A los sacerdotes", "A las mujeres embarazadas"], answer: "A los viajeros nocturnos y personas perdidas", explanation: "The Cadejo's targets—night travelers, drunkards, and the lost—reflect the real dangers of rural Central American roads after dark. The legend served as a social warning against risky nighttime behavior while also offering comfort that a protective spirit might be watching." }
    ]
  },
  {
    id: "folktale-quetzalcoatl",
    spanishName: "Quetzalcóatl - La Serpiente Emplumada",
    englishName: "Quetzalcoatl - The Feathered Serpent",
    content: "<p><strong>Quetzalcóatl</strong>, la Serpiente Emplumada, es una de las deidades más importantes de Mesoamérica. Su nombre viene del náhuatl: \"quetzal\" (un ave de plumaje precioso) y \"cóatl\" (serpiente). Era el dios del viento, del conocimiento, de la estrella de la mañana y era considerado el creador de la humanidad. Su culto se extendió por toda Mesoamérica bajo diferentes nombres: Kukulkán para los mayas y Gucumatz para los quichés.</p><p>Según la leyenda azteca, Quetzalcóatl fue un dios-rey que gobernó la legendaria ciudad de Tula con sabiduría y bondad. Se opuso a los sacrificios humanos y enseñó a los hombres la agricultura, el calendario, las artes y la escritura. Sin embargo, su rival Tezcatlipoca lo engañó haciéndolo emborracharse y cometer actos vergonzosos. Avergonzado, Quetzalcóatl partió hacia el este en una balsa de serpientes, prometiendo regresar algún día.</p><p>Esta promesa de retorno tuvo consecuencias históricas enormes. Cuando Hernán Cortés llegó a México en 1519 desde el este, algunos creen que el emperador Moctezuma lo confundió con el regreso de Quetzalcóatl, lo que facilitó la conquista española. Aunque esta interpretación es debatida por los historiadores modernos, la leyenda de Quetzalcóatl sigue siendo fundamental para entender la mitología y la historia de México.</p>",
    quiz: [
      { question: "¿Qué significa 'Quetzalcóatl' en náhuatl?", options: ["Dios del sol", "Serpiente emplumada", "Águila dorada", "Guerrero sagrado"], answer: "Serpiente emplumada", explanation: "The quetzal bird, with its brilliant emerald-green tail feathers, was sacred to Mesoamerican peoples—its feathers were more valuable than gold. Combining it with 'coatl' (serpent) created a deity that unified sky and earth, making Quetzalcoatl one of the most important gods across multiple civilizations." },
      { question: "¿Cómo se llamaba Quetzalcóatl entre los mayas?", options: ["Chaac", "Kukulkán", "Itzamná", "Hunab Ku"], answer: "Kukulkán", explanation: "The fact that this deity appears under different names across Mesoamerica—Quetzalcoatl (Aztec/Nahuatl), Kukulkan (Maya), and Gucumatz (K'iche' Maya)—shows how deeply interconnected these civilizations were despite their distinct languages and cultures." },
      { question: "¿Qué prometió Quetzalcóatl al partir hacia el este?", options: ["Destruir el mundo", "Regresar algún día", "Enviar lluvia", "Crear nuevos dioses"], answer: "Regresar algún día", explanation: "This promise of return from the east had enormous historical consequences: when Hernan Cortes arrived from the east in 1519, some accounts claim Moctezuma hesitated to fight because he feared it was Quetzalcoatl's return. Modern historians debate whether this account was exaggerated after the fact to justify the conquest." }
    ]
  },
  {
    id: "folktale-sombreron",
    spanishName: "El Sombrerón",
    englishName: "The Man with the Big Hat",
    content: "<p><strong>El Sombrerón</strong> es una de las leyendas más populares de Guatemala, aunque también se conoce en otros países centroamericanos y en México. Se describe como un hombre muy pequeño, vestido todo de negro, con un enorme sombrero negro, botas con espuelas y una guitarra plateada. Monta un caballo negro o una mula y va acompañado de cuatro mulas cargadas con tesoros.</p><p>Según la leyenda, El Sombrerón se enamora de mujeres jóvenes de ojos grandes y cabello largo y negro. Cuando encuentra a una que le gusta, les trenza el cabello a ellas y a sus mulas durante la noche, les canta serenatas con su guitarra y les espolvorea tierra en la comida para que no puedan comer y se debiliten. Las víctimas del Sombrerón pierden el apetito, no pueden dormir y se enferman de tristeza y melancolía.</p><p>El remedio tradicional contra El Sombrerón es cortarle el cabello a la mujer afectada (ya que él se enamora del cabello largo) o mudarse a otra ciudad. En la cultura guatemalteca, El Sombrerón es una figura ambigua: es aterrador pero también romántico y trágico. Su historia ha sido tema de canciones, obras de teatro y es parte integral de las tradiciones orales de La Antigua Guatemala, donde se dice que sus serenatas aún se escuchan en las calles coloniales.</p>",
    quiz: [
      { question: "¿Cómo se describe físicamente al Sombrerón?", options: ["Alto y rubio", "Pequeño, vestido de negro con un gran sombrero", "Grande y musculoso", "Viejo con barba blanca"], answer: "Pequeño, vestido de negro con un gran sombrero", explanation: "El Sombreron's distinctive appearance—tiny stature, all black clothing, oversized hat, silver guitar, and jingling spurs—makes him one of the most visually specific characters in Central American folklore. His small size contrasts with his enormous supernatural power, a common motif in Guatemalan legends." },
      { question: "¿Qué les hace a las mujeres que le gustan?", options: ["Las secuestra", "Les trenza el cabello y les canta serenatas", "Les regala oro", "Las convierte en animales"], answer: "Les trenza el cabello y les canta serenatas", explanation: "His methods are a dark twist on courtship rituals: serenades and hair-braiding are romantic gestures, but sprinkling dirt on food to cause wasting illness reveals sinister obsession. The legend serves as a cautionary tale about the dangers of consuming romantic attention from the wrong source." },
      { question: "¿Cuál es el remedio tradicional contra El Sombrerón?", options: ["Rezar tres rosarios", "Cortarle el cabello a la mujer afectada", "Quemar incienso", "Poner ajo en las ventanas"], answer: "Cortarle el cabello a la mujer afectada", explanation: "Since El Sombreron's obsession is specifically with long, dark hair, cutting it removes the source of his attraction and breaks the spell. This practical remedy reflects folk logic: remove what the supernatural entity desires, and it loses its power over you." }
    ]
  }
];
