'use strict';

// ════════════════════════════════════════
//  SPANISH MINIMAL PAIR DISTINCTION DRILLS
//  45+ items across 3 categories, A1-C2
// ════════════════════════════════════════

const MINIMAL_PAIR_CATEGORIES = {
  ser_estar: {
    id: 'ser_estar',
    label: 'Ser vs Estar',
    labelEs: 'Ser contra Estar',
    description: 'Distinguish between inherent qualities (ser) and states/conditions (estar).',
    descriptionEs: 'Distingue entre cualidades inherentes (ser) y estados/condiciones (estar).',
    optionLabels: ['ser', 'estar'],
  },
  por_para: {
    id: 'por_para',
    label: 'Por vs Para',
    labelEs: 'Por contra Para',
    description: 'Distinguish between cause/means (por) and purpose/destination (para).',
    descriptionEs: 'Distingue entre causa/medio (por) y finalidad/destino (para).',
    optionLabels: ['por', 'para'],
  },
  pret_imp: {
    id: 'pret_imp',
    label: 'Pretérito vs Imperfecto',
    labelEs: 'Pretérito contra Imperfecto',
    description: 'Distinguish between completed actions (pretérito) and ongoing/habitual past (imperfecto).',
    descriptionEs: 'Distingue entre acciones completadas (pretérito) y acciones continuas/habituales en el pasado (imperfecto).',
    optionLabels: ['pretérito', 'imperfecto'],
  },
};

const MINIMAL_PAIRS = [

  // ──────────────────────────────────────
  //  SER vs ESTAR  (18 items)
  // ──────────────────────────────────────

  // A1 — Basic inherent quality
  {
    id: 'mp-1',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'Mi hermano ___ alto.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for inherent physical traits. Height is a permanent characteristic.',
    explanationEs: 'Usa SER para rasgos físicos inherentes. La estatura es una característica permanente.',
    contrast: "Compare: 'Mi hermano ESTÁ cansado' — ESTAR for a temporary physical state.",
  },
  // A1 — Basic temporary state
  {
    id: 'mp-2',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'El café ___ caliente.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'Use ESTAR for temporary states. The coffee is hot right now but will cool down.',
    explanationEs: 'Usa ESTAR para estados temporales. El café está caliente ahora, pero se enfriará.',
    contrast: "Compare: 'El café ES colombiano' — SER for origin or inherent type.",
  },
  // A1 — Nationality/origin
  {
    id: 'mp-3',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'Ellos ___ de México.',
    answer: 'son',
    wrongAnswer: 'están',
    options: ['son', 'están'],
    explanation: 'Use SER for origin and nationality. Where someone is from never changes.',
    explanationEs: 'Usa SER para el origen y la nacionalidad. El lugar de procedencia no cambia.',
    contrast: "Compare: 'Ellos ESTÁN en México' — ESTAR for current location.",
  },
  // A1 — Location of people/things
  {
    id: 'mp-4',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'Los libros ___ en la mesa.',
    answer: 'están',
    wrongAnswer: 'son',
    options: ['son', 'están'],
    explanation: 'Use ESTAR for the physical location of objects and people.',
    explanationEs: 'Usa ESTAR para la ubicación física de objetos y personas.',
    contrast: "Compare: 'Los libros SON interesantes' — SER for an inherent quality.",
  },
  // A2 — Profession/identity
  {
    id: 'mp-5',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Mi madre ___ profesora.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for professions and identity. It defines who she is.',
    explanationEs: 'Usa SER para profesiones e identidad. Define quién es ella.',
    contrast: "Compare: 'Mi madre ESTÁ ocupada' — ESTAR for a current condition.",
  },
  // A2 — Emotional state
  {
    id: 'mp-6',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Los niños ___ contentos hoy.',
    answer: 'están',
    wrongAnswer: 'son',
    options: ['son', 'están'],
    explanation: 'Use ESTAR for emotions and moods. "Hoy" confirms this is a temporary state.',
    explanationEs: 'Usa ESTAR para emociones y estados de ánimo. "Hoy" confirma que es temporal.',
    contrast: "Compare: 'Los niños SON alegres' — SER for personality (they are cheerful people).",
  },
  // A2 — Time and date
  {
    id: 'mp-7',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Hoy ___ martes.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for telling the time, date, and day of the week.',
    explanationEs: 'Usa SER para decir la hora, la fecha y el día de la semana.',
    contrast: "Compare: 'Hoy ESTÁ lloviendo' — ESTAR for weather conditions in progress.",
  },
  // A2 — Progressive tense (estar + gerund)
  {
    id: 'mp-8',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Yo ___ estudiando español.',
    answer: 'estoy',
    wrongAnswer: 'soy',
    options: ['soy', 'estoy'],
    explanation: 'Use ESTAR + gerund (-ando/-iendo) to form the progressive tense.',
    explanationEs: 'Usa ESTAR + gerundio (-ando/-iendo) para formar el tiempo progresivo.',
    contrast: "Compare: 'Yo SOY estudiante' — SER to define what you are (identity).",
  },
  // B1 — Event location (tricky: SER for events!)
  {
    id: 'mp-9',
    category: 'ser_estar',
    level: 'B1',
    sentence: 'La fiesta ___ en mi casa.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for the location of events. "La fiesta" is an event, not a physical object.',
    explanationEs: 'Usa SER para la ubicación de eventos. "La fiesta" es un acontecimiento, no un objeto.',
    contrast: "Compare: 'Mi casa ESTÁ en la calle Mayor' — ESTAR for the location of a building.",
  },
  // B1 — Adjective meaning changes: listo
  {
    id: 'mp-10',
    category: 'ser_estar',
    level: 'B1',
    sentence: '¿Ya ___ listo para el examen?',
    answer: 'estás',
    wrongAnswer: 'eres',
    options: ['eres', 'estás'],
    explanation: 'ESTAR listo = ready (temporary). SER listo = clever (inherent trait).',
    explanationEs: 'ESTAR listo = preparado (temporal). SER listo = inteligente (rasgo permanente).',
    contrast: "Compare: 'Ella ES muy lista' — SER listo means she is a clever person.",
  },
  // B1 — Adjective meaning changes: aburrido
  {
    id: 'mp-11',
    category: 'ser_estar',
    level: 'B1',
    sentence: 'La película ___ aburrida.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'SER aburrido = the movie is boring (inherent quality of the film).',
    explanationEs: 'SER aburrido = la película es aburrida (cualidad inherente de la película).',
    contrast: "Compare: 'Yo ESTOY aburrido' — ESTAR aburrido means I am bored (temporary feeling).",
  },
  // B1 — Marital status
  {
    id: 'mp-12',
    category: 'ser_estar',
    level: 'B1',
    sentence: 'Mi tía ___ casada desde hace veinte años.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'Use ESTAR for marital status in Spanish. Marriage is treated as a state, not identity.',
    explanationEs: 'Usa ESTAR para el estado civil. El matrimonio se considera un estado, no una identidad.',
    contrast: "Compare: 'Mi tía ES una mujer independiente' — SER for defining who she is.",
  },
  // B2 — Passive with SER (action)
  {
    id: 'mp-13',
    category: 'ser_estar',
    level: 'B2',
    sentence: 'La casa ___ construida por un arquitecto famoso.',
    answer: 'fue',
    wrongAnswer: 'estuvo',
    options: ['fue', 'estuvo'],
    explanation: 'SER + participle = passive voice, emphasizing the action and who did it.',
    explanationEs: 'SER + participio = voz pasiva, enfatizando la acción y quién la realizó.',
    contrast: "Compare: 'La casa ESTÁ construida' — ESTAR + participle for the resulting state (it is built).",
  },
  // B2 — Resultant state with ESTAR
  {
    id: 'mp-14',
    category: 'ser_estar',
    level: 'B2',
    sentence: 'La puerta ___ abierta.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR + participle describes a resulting state. The door is open (someone opened it).',
    explanationEs: 'ESTAR + participio describe un estado resultante. La puerta está abierta (alguien la abrió).',
    contrast: "Compare: 'La puerta FUE abierta por el portero' — SER + participle for the action itself.",
  },
  // B2 — Dead (result of dying)
  {
    id: 'mp-15',
    category: 'ser_estar',
    level: 'B2',
    sentence: 'El paciente ___ muerto.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR muerto = the patient is dead (result of dying). Death is a resulting state.',
    explanationEs: 'ESTAR muerto = el paciente está muerto (resultado de morir). La muerte es un estado resultante.',
    contrast: "Compare: 'SER mortal' — SER for an inherent quality (being mortal is a permanent trait).",
  },
  // C1 — Adjective meaning changes: malo
  {
    id: 'mp-16',
    category: 'ser_estar',
    level: 'C1',
    sentence: 'El niño ___ malo; tiene fiebre.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR malo = to be sick/ill. The semiclause about fever confirms a temporary condition.',
    explanationEs: 'ESTAR malo = estar enfermo. La mención de la fiebre confirma un estado temporal.',
    contrast: "Compare: 'El niño ES malo' — SER malo means the child is bad/naughty (character trait).",
  },
  // C1 — SER with material
  {
    id: 'mp-17',
    category: 'ser_estar',
    level: 'C1',
    sentence: 'La mesa ___ de madera.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER + de to describe what something is made of. Material is an inherent property.',
    explanationEs: 'Usa SER + de para indicar el material. El material es una propiedad inherente.',
    contrast: "Compare: 'La mesa ESTÁ sucia' — ESTAR for the current condition of the table.",
  },
  // C1 — "Ser joven" vs "Estar joven"
  {
    id: 'mp-18',
    category: 'ser_estar',
    level: 'C1',
    sentence: 'Mi abuela tiene 80 años, pero ___ muy joven para su edad.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR joven = to look/seem young (subjective perception). "Para su edad" signals comparison.',
    explanationEs: 'ESTAR joven = parecer joven (percepción subjetiva). "Para su edad" indica una comparación.',
    contrast: "Compare: 'Ella ES joven' — SER joven states an objective fact about age.",
  },

  // ──────────────────────────────────────
  //  POR vs PARA  (17 items)
  // ──────────────────────────────────────

  // A1 — Fixed expression: por favor
  {
    id: 'mp-19',
    category: 'por_para',
    level: 'A1',
    sentence: '¿Me pasas el agua, ___ favor?',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: '"Por favor" is a fixed expression meaning "please." Always use POR.',
    explanationEs: '"Por favor" es una expresión fija. Siempre se usa POR.',
    contrast: "Compare: 'PARA mí, un agua' — PARA to indicate the recipient of an order.",
  },
  // A1 — Recipient
  {
    id: 'mp-20',
    category: 'por_para',
    level: 'A1',
    sentence: 'Este regalo es ___ ti.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to indicate the intended recipient of something.',
    explanationEs: 'Usa PARA para indicar el destinatario de algo.',
    contrast: "Compare: 'Gracias POR el regalo' — POR to express the cause of gratitude.",
  },
  // A2 — Purpose/goal
  {
    id: 'mp-21',
    category: 'por_para',
    level: 'A2',
    sentence: 'Estudio español ___ viajar a España.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA + infinitive to express purpose or goal (in order to).',
    explanationEs: 'Usa PARA + infinitivo para expresar finalidad (con el fin de).',
    contrast: "Compare: 'Viajo POR trabajo' — POR for the cause/reason behind an action.",
  },
  // A2 — Cause/reason
  {
    id: 'mp-22',
    category: 'por_para',
    level: 'A2',
    sentence: 'No fui a clase ___ la lluvia.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to express the cause or reason. The rain caused the absence.',
    explanationEs: 'Usa POR para expresar la causa o el motivo. La lluvia causó la ausencia.',
    contrast: "Compare: 'Llevo paraguas PARA la lluvia' — PARA for purpose (to prepare for rain).",
  },
  // A2 — Destination
  {
    id: 'mp-23',
    category: 'por_para',
    level: 'A2',
    sentence: 'Mañana salimos ___ Barcelona.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to indicate a destination. They are heading toward Barcelona.',
    explanationEs: 'Usa PARA para indicar un destino. Se dirigen hacia Barcelona.',
    contrast: "Compare: 'Paseamos POR Barcelona' — POR for movement through/around a place.",
  },
  // A2 — Movement through
  {
    id: 'mp-24',
    category: 'por_para',
    level: 'A2',
    sentence: 'Caminamos ___ el parque.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR for movement through or along a place.',
    explanationEs: 'Usa POR para indicar movimiento a través de un lugar.',
    contrast: "Compare: 'Caminamos PARA llegar al parque' — PARA for the goal of reaching the park.",
  },
  // A2 — Time of day
  {
    id: 'mp-25',
    category: 'por_para',
    level: 'A2',
    sentence: 'Prefiero estudiar ___ la mañana.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR with parts of the day: por la mañana, por la tarde, por la noche.',
    explanationEs: 'Usa POR con las partes del día: por la mañana, por la tarde, por la noche.',
    contrast: "Compare: 'Lo necesito PARA mañana' — PARA for a deadline (by tomorrow).",
  },
  // B1 — Deadline
  {
    id: 'mp-26',
    category: 'por_para',
    level: 'B1',
    sentence: 'Necesito el informe ___ el viernes.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to express a deadline (by a certain date).',
    explanationEs: 'Usa PARA para expresar una fecha límite.',
    contrast: "Compare: 'Trabajo POR la noche' — POR for a general time period.",
  },
  // B1 — Duration
  {
    id: 'mp-27',
    category: 'por_para',
    level: 'B1',
    sentence: 'Viví en Madrid ___ tres años.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to express duration of time (for a period).',
    explanationEs: 'Usa POR para expresar duración en el tiempo.',
    contrast: "Compare: 'Me mudo a Madrid PARA tres años' — PARA would imply a planned stay with a purpose.",
  },
  // B1 — Exchange/payment
  {
    id: 'mp-28',
    category: 'por_para',
    level: 'B1',
    sentence: 'Pagué cien euros ___ este abrigo.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR for exchange or payment. You traded money for the coat.',
    explanationEs: 'Usa POR para intercambios o pagos. Cambiaste dinero por el abrigo.',
    contrast: "Compare: 'Compré este abrigo PARA el invierno' — PARA for the intended purpose.",
  },
  // B1 — On behalf of / in favor of
  {
    id: 'mp-29',
    category: 'por_para',
    level: 'B1',
    sentence: 'Voto ___ la democracia.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to mean "in favor of" or "in support of."',
    explanationEs: 'Usa POR con el significado de "a favor de" o "en apoyo de."',
    contrast: "Compare: 'Trabajo PARA una ONG' — PARA to indicate who you work for (employer).",
  },
  // B1 — Employer
  {
    id: 'mp-30',
    category: 'por_para',
    level: 'B1',
    sentence: 'Mi padre trabaja ___ una empresa internacional.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to indicate the employer or entity you work for.',
    explanationEs: 'Usa PARA para indicar la empresa o entidad para la que trabajas.',
    contrast: "Compare: 'Trabaja POR necesidad' — POR for the reason/cause behind working.",
  },
  // B2 — Fixed expression: por ejemplo
  {
    id: 'mp-31',
    category: 'por_para',
    level: 'B2',
    sentence: 'Hay muchas opciones, ___ ejemplo, el tren.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: '"Por ejemplo" is a fixed expression meaning "for example."',
    explanationEs: '"Por ejemplo" es una expresión fija que significa "for example."',
    contrast: "Compare: 'PARA empezar, tomemos el tren' — PARA in the fixed phrase 'para empezar' (to begin with).",
  },
  // B2 — Fixed expression: para siempre
  {
    id: 'mp-32',
    category: 'por_para',
    level: 'B2',
    sentence: 'Te querré ___ siempre.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: '"Para siempre" is a fixed expression meaning "forever."',
    explanationEs: '"Para siempre" es una expresión fija que significa "forever."',
    contrast: "Compare: 'POR ahora, todo está bien' — POR in the fixed phrase 'por ahora' (for now).",
  },
  // B2 — Means/method
  {
    id: 'mp-33',
    category: 'por_para',
    level: 'B2',
    sentence: 'Envié el documento ___ correo electrónico.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to indicate the means or method of communication or transport.',
    explanationEs: 'Usa POR para indicar el medio de comunicación o transporte.',
    contrast: "Compare: 'El documento es PARA el director' — PARA for the intended recipient.",
  },
  // C1 — Considering / in spite of
  {
    id: 'mp-34',
    category: 'por_para',
    level: 'C1',
    sentence: '___ ser tan joven, habla con mucha madurez.',
    answer: 'Para',
    wrongAnswer: 'Por',
    options: ['Por', 'Para'],
    explanation: 'PARA + infinitive can mean "considering" or "for (someone who is...)." It expresses a surprising contrast.',
    explanationEs: 'PARA + infinitivo puede significar "teniendo en cuenta que." Expresa un contraste sorprendente.',
    contrast: "Compare: 'POR ser tan joven, no lo contrataron' — POR for cause (because he was so young).",
  },
  // C1 — "Estar por" vs "estar para"
  {
    id: 'mp-35',
    category: 'por_para',
    level: 'C1',
    sentence: 'El tren está ___ salir.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Estar PARA + infinitive = about to do something (imminent action).',
    explanationEs: 'Estar PARA + infinitivo = estar a punto de hacer algo (acción inminente).',
    contrast: "Compare: 'Está POR verse' — estar POR + infinitive = remains to be (done/seen).",
  },

  // ──────────────────────────────────────
  //  PRETÉRITO vs IMPERFECTO  (18 items)
  // ──────────────────────────────────────

  // A2 — Completed single action
  {
    id: 'mp-36',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Ayer ___ una película. (ver, yo)',
    answer: 'vi',
    wrongAnswer: 'veía',
    options: ['vi', 'veía'],
    explanation: 'Use the PRETERITE for a completed action at a specific time. "Ayer" marks a finished event.',
    explanationEs: 'Usa el PRETÉRITO para una acción terminada en un momento concreto. "Ayer" marca un evento finalizado.',
    contrast: "Compare: 'De niño, VEÍA películas todos los sábados' — IMPERFECT for habitual past actions.",
  },
  // A2 — Habitual action
  {
    id: 'mp-37',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Cuando era niño, ___ al parque todos los días. (ir, yo)',
    answer: 'iba',
    wrongAnswer: 'fui',
    options: ['fui', 'iba'],
    explanation: 'Use the IMPERFECT for habitual or repeated actions in the past. "Todos los días" is the key marker.',
    explanationEs: 'Usa el IMPERFECTO para acciones habituales en el pasado. "Todos los días" es la clave.',
    contrast: "Compare: 'Ayer FUI al parque' — PRETERITE for a single completed visit.",
  },
  // A2 — Description in the past (weather)
  {
    id: 'mp-38',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Aquella tarde ___ mucho sol. (hacer)',
    answer: 'hacía',
    wrongAnswer: 'hizo',
    options: ['hizo', 'hacía'],
    explanation: 'Use the IMPERFECT for background descriptions: weather, setting, atmosphere.',
    explanationEs: 'Usa el IMPERFECTO para descripciones de fondo: clima, ambiente, escenario.',
    contrast: "Compare: 'Ayer HIZO mucho frío' — PRETERITE when reporting weather as a completed fact of the day.",
  },
  // A2 — Age in the past
  {
    id: 'mp-39',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Cuando ___ diez años, me mudé a otra ciudad. (tener, yo)',
    answer: 'tenía',
    wrongAnswer: 'tuve',
    options: ['tuve', 'tenía'],
    explanation: 'Use the IMPERFECT for age in the past. Age is background information, not an event.',
    explanationEs: 'Usa el IMPERFECTO para la edad en el pasado. La edad es información de fondo, no un evento.',
    contrast: "Compare: 'TUVE un accidente a los diez años' — PRETERITE for the event that happened at that age.",
  },
  // A2 — Time in the past
  {
    id: 'mp-40',
    category: 'pret_imp',
    level: 'A2',
    sentence: '___ las tres de la tarde cuando llegaron. (ser)',
    answer: 'Eran',
    wrongAnswer: 'Fueron',
    options: ['Fueron', 'Eran'],
    explanation: 'Use the IMPERFECT for telling time in the past. It sets the scene.',
    explanationEs: 'Usa el IMPERFECTO para decir la hora en el pasado. Establece el escenario.',
    contrast: "Compare: 'La reunión FUE a las tres' — PRETERITE for a scheduled event that took place.",
  },
  // B1 — Interruption pattern
  {
    id: 'mp-41',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'Mientras yo ___, sonó el teléfono. (dormir)',
    answer: 'dormía',
    wrongAnswer: 'dormí',
    options: ['dormí', 'dormía'],
    explanation: 'IMPERFECT for the ongoing background action that gets interrupted. "Mientras" signals duration.',
    explanationEs: 'IMPERFECTO para la acción de fondo que se interrumpe. "Mientras" indica duración.',
    contrast: "Compare: 'Anoche DORMÍ ocho horas' — PRETERITE for a completed duration of sleep.",
  },
  // B1 — The interrupting action
  {
    id: 'mp-42',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'Leía un libro cuando alguien ___ a la puerta. (llamar)',
    answer: 'llamó',
    wrongAnswer: 'llamaba',
    options: ['llamó', 'llamaba'],
    explanation: 'PRETERITE for the sudden interrupting action that breaks into the background scene.',
    explanationEs: 'PRETÉRITO para la acción repentina que interrumpe el escenario de fondo.',
    contrast: "Compare: 'Siempre LLAMABA antes de venir' — IMPERFECT for a habitual action (he always used to call).",
  },
  // B1 — Specific time marker: "una vez"
  {
    id: 'mp-43',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'Una vez ___ a un famoso en la calle. (ver, yo)',
    answer: 'vi',
    wrongAnswer: 'veía',
    options: ['vi', 'veía'],
    explanation: '"Una vez" (once) marks a single, specific event. Use the PRETERITE.',
    explanationEs: '"Una vez" marca un evento único y concreto. Usa el PRETÉRITO.',
    contrast: "Compare: 'Siempre lo VEÍA en la televisión' — IMPERFECT for something habitual.",
  },
  // B1 — Ongoing emotion in the past
  {
    id: 'mp-44',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'De joven, ___ mucho a mis abuelos. (querer, yo)',
    answer: 'quería',
    wrongAnswer: 'quise',
    options: ['quise', 'quería'],
    explanation: 'IMPERFECT for ongoing emotional states in the past. Loving grandparents was continuous.',
    explanationEs: 'IMPERFECTO para estados emocionales continuos en el pasado. Querer a los abuelos era algo constante.',
    contrast: "Compare: 'QUISE llamarlos, pero no pude' — PRETERITE quise = I tried/wanted to (at a specific moment).",
  },
  // B2 — Meaning change: conocer (met vs knew)
  {
    id: 'mp-45',
    category: 'pret_imp',
    level: 'B2',
    sentence: '___ a mi esposa en la universidad. (conocer, yo)',
    answer: 'Conocí',
    wrongAnswer: 'Conocía',
    options: ['Conocí', 'Conocía'],
    explanation: 'PRETERITE of conocer = "met" (the beginning of knowing). It marks the first encounter.',
    explanationEs: 'PRETÉRITO de conocer = "conocí" (el inicio de conocer). Marca el primer encuentro.',
    contrast: "Compare: 'Ya CONOCÍA a tu hermano' — IMPERFECT conocía = already knew (ongoing state).",
  },
  // B2 — Meaning change: saber (found out vs knew)
  {
    id: 'mp-46',
    category: 'pret_imp',
    level: 'B2',
    sentence: '___ la verdad cuando leí la carta. (saber, yo)',
    answer: 'Supe',
    wrongAnswer: 'Sabía',
    options: ['Supe', 'Sabía'],
    explanation: 'PRETERITE of saber = "found out" (the moment of learning). The letter triggered the discovery.',
    explanationEs: 'PRETÉRITO de saber = "me enteré" (el momento de descubrirlo). La carta desencadenó el descubrimiento.',
    contrast: "Compare: 'Ya SABÍA la verdad' — IMPERFECT sabía = already knew (prior knowledge).",
  },
  // B2 — Meaning change: poder (managed vs could)
  {
    id: 'mp-47',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'Después de mucho esfuerzo, ___ abrir la puerta. (poder, yo)',
    answer: 'pude',
    wrongAnswer: 'podía',
    options: ['pude', 'podía'],
    explanation: 'PRETERITE of poder = "managed to / succeeded in." The effort led to a completed result.',
    explanationEs: 'PRETÉRITO de poder = "logré." El esfuerzo llevó a un resultado concreto.',
    contrast: "Compare: 'De niño, PODÍA correr muy rápido' — IMPERFECT podía = had the ability to (general capacity).",
  },
  // B2 — Emotional state change
  {
    id: 'mp-48',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'Cuando vi el accidente, ___ mucho miedo. (tener, yo)',
    answer: 'tuve',
    wrongAnswer: 'tenía',
    options: ['tuve', 'tenía'],
    explanation: 'PRETERITE for a sudden onset of emotion triggered by a specific event.',
    explanationEs: 'PRETÉRITO para una emoción repentina provocada por un evento concreto.',
    contrast: "Compare: 'De niño, TENÍA miedo a la oscuridad' — IMPERFECT for an ongoing emotional state.",
  },
  // B2 — Narration vs description
  {
    id: 'mp-49',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'La mujer ___ un vestido rojo y llevaba un sombrero. (llevar)',
    answer: 'llevaba',
    wrongAnswer: 'llevó',
    options: ['llevó', 'llevaba'],
    explanation: 'IMPERFECT for physical descriptions of people in a past narrative. It paints the scene.',
    explanationEs: 'IMPERFECTO para descripciones físicas en una narración pasada. Pinta la escena.',
    contrast: "Compare: 'Se LLEVÓ el vestido rojo' — PRETERITE for the completed action of taking the dress.",
  },
  // B2 — Two simultaneous ongoing actions
  {
    id: 'mp-50',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'Mientras ella ___, él preparaba la cena. (estudiar)',
    answer: 'estudiaba',
    wrongAnswer: 'estudió',
    options: ['estudió', 'estudiaba'],
    explanation: 'IMPERFECT for two actions happening simultaneously in the past. "Mientras" connects them.',
    explanationEs: 'IMPERFECTO para dos acciones simultáneas en el pasado. "Mientras" las conecta.',
    contrast: "Compare: 'ESTUDIÓ toda la noche y luego se durmió' — PRETERITE for sequential completed actions.",
  },
  // C1 — Sequence of completed events
  {
    id: 'mp-51',
    category: 'pret_imp',
    level: 'C1',
    sentence: 'Se levantó, se vistió y ___ de casa. (salir)',
    answer: 'salió',
    wrongAnswer: 'salía',
    options: ['salió', 'salía'],
    explanation: 'PRETERITE for a chain of sequential completed actions. Each one follows the previous.',
    explanationEs: 'PRETÉRITO para una cadena de acciones completadas en secuencia. Cada una sigue a la anterior.',
    contrast: "Compare: 'Cada mañana SALÍA de casa a las ocho' — IMPERFECT for a repeated daily routine.",
  },
  // C1 — "Querer" meaning change
  {
    id: 'mp-52',
    category: 'pret_imp',
    level: 'C1',
    sentence: '___ decírtelo, pero no encontré el momento. (querer, yo)',
    answer: 'Quise',
    wrongAnswer: 'Quería',
    options: ['Quise', 'Quería'],
    explanation: 'PRETERITE quise = "I tried to" (attempted but failed). The second clause confirms failure.',
    explanationEs: 'PRETÉRITO quise = "intenté" (lo intenté pero no pude). La segunda parte confirma el fracaso.',
    contrast: "Compare: 'QUERÍA decírtelo' — IMPERFECT quería = I wanted to (ongoing desire, no attempt implied).",
  },
  // C1 — Politeness / softened request (imperfect)
  {
    id: 'mp-53',
    category: 'pret_imp',
    level: 'C1',
    sentence: '___ pedirte un favor. (querer, yo)',
    answer: 'Quería',
    wrongAnswer: 'Quise',
    options: ['Quise', 'Quería'],
    explanation: 'IMPERFECT quería is used for polite, softened requests in the present. It sounds less direct.',
    explanationEs: 'IMPERFECTO quería se usa para peticiones suaves en el presente. Suena menos directo.',
    contrast: "Compare: 'QUISE pedirte un favor, pero no me atreví' — PRETERITE quise = tried to ask (and failed).",
  },
];
