'use strict';

// ════════════════════════════════════════
//  SPANISH MINIMAL PAIR DISTINCTION DRILLS
//  151 items across 9 categories, A1-C2
// ════════════════════════════════════════

const MINIMAL_PAIR_CATEGORIES = {
  ser_estar: {
    id: 'ser_estar',
    label: 'Ser vs Estar',
    labelEs: 'Ser contra Estar',
    description: 'Distinguish between inherent qualities (ser) and states/conditions (estar).',
    descriptionEs: 'Distingue entre cualidades inherentes (ser) y estados/condiciones (estar).',
    optionLabels: ['ser', 'estar'],
  },
  por_para: {
    id: 'por_para',
    label: 'Por vs Para',
    labelEs: 'Por contra Para',
    description: 'Distinguish between cause/means (por) and purpose/destination (para).',
    descriptionEs: 'Distingue entre causa/medio (por) y finalidad/destino (para).',
    optionLabels: ['por', 'para'],
  },
  pret_imp: {
    id: 'pret_imp',
    label: 'Pretérito vs Imperfecto',
    labelEs: 'Pretérito contra Imperfecto',
    description: 'Distinguish between completed actions (pretérito) and ongoing/habitual past (imperfecto).',
    descriptionEs: 'Distingue entre acciones completadas (pretérito) y acciones continuas/habituales en el pasado (imperfecto).',
    optionLabels: ['pretérito', 'imperfecto'],
  },
  false_cognates: {
    id: 'false_cognates',
    label: 'False Cognates',
    labelEs: 'Falsos Amigos',
    description: 'Avoid common false friends — Spanish words that look like English words but have different meanings.',
    descriptionEs: 'Evita los falsos amigos — palabras españolas que se parecen a palabras inglesas pero tienen significados diferentes.',
    optionLabels: ['falso amigo', 'correcta'],
  },
  dual_gender: {
    id: 'dual_gender',
    label: 'Dual-Gender Nouns',
    labelEs: 'Sustantivos de género común',
    description: 'Choose the correct article (el/la) for nouns that can be either gender depending on the person.',
    descriptionEs: 'Elige el artículo correcto (el/la) para sustantivos que cambian de género según la persona.',
    optionLabels: ['el', 'la'],
  },
  gendered_pairs: {
    id: 'gendered_pairs',
    label: 'False-Friend Gender Pairs',
    labelEs: 'Pares de género engañosos',
    description: 'Words ending in -o vs -a that look like masculine/feminine forms but have completely different meanings.',
    descriptionEs: 'Palabras terminadas en -o/-a que parecen masculino/femenino pero significan cosas totalmente distintas.',
    optionLabels: ['-o', '-a'],
  },
  near_miss: {
    id: 'near_miss',
    label: 'Near-Miss Words',
    labelEs: 'Palabras casi iguales',
    description: 'Words one letter apart from gendered pairs but with completely different meanings.',
    descriptionEs: 'Palabras a una letra de diferencia de pares de género, pero con significados completamente distintos.',
    optionLabels: [],
  },
  diphthong_hiatus: {
    id: 'diphthong_hiatus',
    label: 'Diphthong vs Hiatus',
    labelEs: 'Diptongo contra Hiato',
    description: 'Identify whether two adjacent vowels form a diphthong (one syllable) or a hiatus (two syllables).',
    descriptionEs: 'Identifica si dos vocales seguidas forman un diptongo (una sílaba) o un hiato (dos sílabas).',
    optionLabels: ['diptongo', 'hiato'],
  },
  stress_tilde: {
    id: 'stress_tilde',
    label: 'Tilde Rules',
    labelEs: 'Reglas de la tilde',
    description: 'Determine whether a word needs a written accent mark (tilde) based on Spanish stress rules: agudas, llanas, esdrújulas.',
    descriptionEs: 'Determina si una palabra necesita tilde según las reglas de acentuación: agudas, llanas, esdrújulas.',
    optionLabels: ['necesita tilde', 'no necesita tilde'],
  },
};

const MINIMAL_PAIRS = [

  // ──────────────────────────────────────
  //  SER vs ESTAR  (18 items)
  // ──────────────────────────────────────

  // A1 — Basic inherent quality
  {
    id: 'mp-1',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'Mi hermano ___ alto.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for inherent physical traits. Height is a permanent characteristic.',
    explanationEs: 'Usa SER para rasgos físicos inherentes. La estatura es una característica permanente.',
    contrast: "Compare: 'Mi hermano ESTÁ cansado' — ESTAR for a temporary physical state.",
  },
  // A1 — Basic temporary state
  {
    id: 'mp-2',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'El café ___ caliente.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'Use ESTAR for temporary states. The coffee is hot right now but will cool down.',
    explanationEs: 'Usa ESTAR para estados temporales. El café está caliente ahora, pero se enfriará.',
    contrast: "Compare: 'El café ES colombiano' — SER for origin or inherent type.",
  },
  // A1 — Nationality/origin
  {
    id: 'mp-3',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'Ellos ___ de México.',
    answer: 'son',
    wrongAnswer: 'están',
    options: ['son', 'están'],
    explanation: 'Use SER for origin and nationality. Where someone is from never changes.',
    explanationEs: 'Usa SER para el origen y la nacionalidad. El lugar de procedencia no cambia.',
    contrast: "Compare: 'Ellos ESTÁN en México' — ESTAR for current location.",
  },
  // A1 — Location of people/things
  {
    id: 'mp-4',
    category: 'ser_estar',
    level: 'A1',
    sentence: 'Los libros ___ en la mesa.',
    answer: 'están',
    wrongAnswer: 'son',
    options: ['son', 'están'],
    explanation: 'Use ESTAR for the physical location of objects and people.',
    explanationEs: 'Usa ESTAR para la ubicación física de objetos y personas.',
    contrast: "Compare: 'Los libros SON interesantes' — SER for an inherent quality.",
  },
  // A2 — Profession/identity
  {
    id: 'mp-5',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Mi madre ___ profesora.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for professions and identity. It defines who she is.',
    explanationEs: 'Usa SER para profesiones e identidad. Define quién es ella.',
    contrast: "Compare: 'Mi madre ESTÁ ocupada' — ESTAR for a current condition.",
  },
  // A2 — Emotional state
  {
    id: 'mp-6',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Los niños ___ contentos hoy.',
    answer: 'están',
    wrongAnswer: 'son',
    options: ['son', 'están'],
    explanation: 'Use ESTAR for emotions and moods. "Hoy" confirms this is a temporary state.',
    explanationEs: 'Usa ESTAR para emociones y estados de ánimo. "Hoy" confirma que es temporal.',
    contrast: "Compare: 'Los niños SON alegres' — SER for personality (they are cheerful people).",
  },
  // A2 — Time and date
  {
    id: 'mp-7',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Hoy ___ martes.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for telling the time, date, and day of the week.',
    explanationEs: 'Usa SER para decir la hora, la fecha y el día de la semana.',
    contrast: "Compare: 'Hoy ESTÁ lloviendo' — ESTAR for weather conditions in progress.",
  },
  // A2 — Progressive tense (estar + gerund)
  {
    id: 'mp-8',
    category: 'ser_estar',
    level: 'A2',
    sentence: 'Yo ___ estudiando español.',
    answer: 'estoy',
    wrongAnswer: 'soy',
    options: ['soy', 'estoy'],
    explanation: 'Use ESTAR + gerund (-ando/-iendo) to form the progressive tense.',
    explanationEs: 'Usa ESTAR + gerundio (-ando/-iendo) para formar el tiempo progresivo.',
    contrast: "Compare: 'Yo SOY estudiante' — SER to define what you are (identity).",
  },
  // B1 — Event location (tricky: SER for events!)
  {
    id: 'mp-9',
    category: 'ser_estar',
    level: 'B1',
    sentence: 'La fiesta ___ en mi casa.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER for the location of events. "La fiesta" is an event, not a physical object.',
    explanationEs: 'Usa SER para la ubicación de eventos. "La fiesta" es un acontecimiento, no un objeto.',
    contrast: "Compare: 'Mi casa ESTÁ en la calle Mayor' — ESTAR for the location of a building.",
  },
  // B1 — Adjective meaning changes: listo
  {
    id: 'mp-10',
    category: 'ser_estar',
    level: 'B1',
    sentence: '¿Ya ___ listo para el examen?',
    answer: 'estás',
    wrongAnswer: 'eres',
    options: ['eres', 'estás'],
    explanation: 'ESTAR listo = ready (temporary). SER listo = clever (inherent trait).',
    explanationEs: 'ESTAR listo = preparado (temporal). SER listo = inteligente (rasgo permanente).',
    contrast: "Compare: 'Ella ES muy lista' — SER listo means she is a clever person.",
  },
  // B1 — Adjective meaning changes: aburrido
  {
    id: 'mp-11',
    category: 'ser_estar',
    level: 'B1',
    sentence: 'La película ___ aburrida.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'SER aburrido = the movie is boring (inherent quality of the film).',
    explanationEs: 'SER aburrido = la película es aburrida (cualidad inherente de la película).',
    contrast: "Compare: 'Yo ESTOY aburrido' — ESTAR aburrido means I am bored (temporary feeling).",
  },
  // B1 — Marital status
  {
    id: 'mp-12',
    category: 'ser_estar',
    level: 'B1',
    sentence: 'Mi tía ___ casada desde hace veinte años.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'Use ESTAR for marital status in Spanish. Marriage is treated as a state, not identity.',
    explanationEs: 'Usa ESTAR para el estado civil. El matrimonio se considera un estado, no una identidad.',
    contrast: "Compare: 'Mi tía ES una mujer independiente' — SER for defining who she is.",
  },
  // B2 — Passive with SER (action)
  {
    id: 'mp-13',
    category: 'ser_estar',
    level: 'B2',
    sentence: 'La casa ___ construida por un arquitecto famoso.',
    answer: 'fue',
    wrongAnswer: 'estuvo',
    options: ['fue', 'estuvo'],
    explanation: 'SER + participle = passive voice, emphasizing the action and who did it.',
    explanationEs: 'SER + participio = voz pasiva, enfatizando la acción y quién la realizó.',
    contrast: "Compare: 'La casa ESTÁ construida' — ESTAR + participle for the resulting state (it is built).",
  },
  // B2 — Resultant state with ESTAR
  {
    id: 'mp-14',
    category: 'ser_estar',
    level: 'B2',
    sentence: 'La puerta ___ abierta.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR + participle describes a resulting state. The door is open (someone opened it).',
    explanationEs: 'ESTAR + participio describe un estado resultante. La puerta está abierta (alguien la abrió).',
    contrast: "Compare: 'La puerta FUE abierta por el portero' — SER + participle for the action itself.",
  },
  // B2 — Dead (result of dying)
  {
    id: 'mp-15',
    category: 'ser_estar',
    level: 'B2',
    sentence: 'El paciente ___ muerto.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR muerto = the patient is dead (result of dying). Death is a resulting state.',
    explanationEs: 'ESTAR muerto = el paciente está muerto (resultado de morir). La muerte es un estado resultante.',
    contrast: "Compare: 'SER mortal' — SER for an inherent quality (being mortal is a permanent trait).",
  },
  // C1 — Adjective meaning changes: malo
  {
    id: 'mp-16',
    category: 'ser_estar',
    level: 'C1',
    sentence: 'El niño ___ malo; tiene fiebre.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR malo = to be sick/ill. The semiclause about fever confirms a temporary condition.',
    explanationEs: 'ESTAR malo = estar enfermo. La mención de la fiebre confirma un estado temporal.',
    contrast: "Compare: 'El niño ES malo' — SER malo means the child is bad/naughty (character trait).",
  },
  // C1 — SER with material
  {
    id: 'mp-17',
    category: 'ser_estar',
    level: 'C1',
    sentence: 'La mesa ___ de madera.',
    answer: 'es',
    wrongAnswer: 'está',
    options: ['es', 'está'],
    explanation: 'Use SER + de to describe what something is made of. Material is an inherent property.',
    explanationEs: 'Usa SER + de para indicar el material. El material es una propiedad inherente.',
    contrast: "Compare: 'La mesa ESTÁ sucia' — ESTAR for the current condition of the table.",
  },
  // C1 — "Ser joven" vs "Estar joven"
  {
    id: 'mp-18',
    category: 'ser_estar',
    level: 'C1',
    sentence: 'Mi abuela tiene 80 años, pero ___ muy joven para su edad.',
    answer: 'está',
    wrongAnswer: 'es',
    options: ['es', 'está'],
    explanation: 'ESTAR joven = to look/seem young (subjective perception). "Para su edad" signals comparison.',
    explanationEs: 'ESTAR joven = parecer joven (percepción subjetiva). "Para su edad" indica una comparación.',
    contrast: "Compare: 'Ella ES joven' — SER joven states an objective fact about age.",
  },

  // ──────────────────────────────────────
  //  POR vs PARA  (17 items)
  // ──────────────────────────────────────

  // A1 — Fixed expression: por favor
  {
    id: 'mp-19',
    category: 'por_para',
    level: 'A1',
    sentence: '¿Me pasas el agua, ___ favor?',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: '"Por favor" is a fixed expression meaning "please." Always use POR.',
    explanationEs: '"Por favor" es una expresión fija. Siempre se usa POR.',
    contrast: "Compare: 'PARA mí, un agua' — PARA to indicate the recipient of an order.",
  },
  // A1 — Recipient
  {
    id: 'mp-20',
    category: 'por_para',
    level: 'A1',
    sentence: 'Este regalo es ___ ti.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to indicate the intended recipient of something.',
    explanationEs: 'Usa PARA para indicar el destinatario de algo.',
    contrast: "Compare: 'Gracias POR el regalo' — POR to express the cause of gratitude.",
  },
  // A2 — Purpose/goal
  {
    id: 'mp-21',
    category: 'por_para',
    level: 'A2',
    sentence: 'Estudio español ___ viajar a España.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA + infinitive to express purpose or goal (in order to).',
    explanationEs: 'Usa PARA + infinitivo para expresar finalidad (con el fin de).',
    contrast: "Compare: 'Viajo POR trabajo' — POR for the cause/reason behind an action.",
  },
  // A2 — Cause/reason
  {
    id: 'mp-22',
    category: 'por_para',
    level: 'A2',
    sentence: 'No fui a clase ___ la lluvia.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to express the cause or reason. The rain caused the absence.',
    explanationEs: 'Usa POR para expresar la causa o el motivo. La lluvia causó la ausencia.',
    contrast: "Compare: 'Llevo paraguas PARA la lluvia' — PARA for purpose (to prepare for rain).",
  },
  // A2 — Destination
  {
    id: 'mp-23',
    category: 'por_para',
    level: 'A2',
    sentence: 'Mañana salimos ___ Barcelona.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to indicate a destination. They are heading toward Barcelona.',
    explanationEs: 'Usa PARA para indicar un destino. Se dirigen hacia Barcelona.',
    contrast: "Compare: 'Paseamos POR Barcelona' — POR for movement through/around a place.",
  },
  // A2 — Movement through
  {
    id: 'mp-24',
    category: 'por_para',
    level: 'A2',
    sentence: 'Caminamos ___ el parque.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR for movement through or along a place.',
    explanationEs: 'Usa POR para indicar movimiento a través de un lugar.',
    contrast: "Compare: 'Caminamos PARA llegar al parque' — PARA for the goal of reaching the park.",
  },
  // A2 — Time of day
  {
    id: 'mp-25',
    category: 'por_para',
    level: 'A2',
    sentence: 'Prefiero estudiar ___ la mañana.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR with parts of the day: por la mañana, por la tarde, por la noche.',
    explanationEs: 'Usa POR con las partes del día: por la mañana, por la tarde, por la noche.',
    contrast: "Compare: 'Lo necesito PARA mañana' — PARA for a deadline (by tomorrow).",
  },
  // B1 — Deadline
  {
    id: 'mp-26',
    category: 'por_para',
    level: 'B1',
    sentence: 'Necesito el informe ___ el viernes.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to express a deadline (by a certain date).',
    explanationEs: 'Usa PARA para expresar una fecha límite.',
    contrast: "Compare: 'Trabajo POR la noche' — POR for a general time period.",
  },
  // B1 — Duration
  {
    id: 'mp-27',
    category: 'por_para',
    level: 'B1',
    sentence: 'Viví en Madrid ___ tres años.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to express duration of time (for a period).',
    explanationEs: 'Usa POR para expresar duración en el tiempo.',
    contrast: "Compare: 'Me mudo a Madrid PARA tres años' — PARA would imply a planned stay with a purpose.",
  },
  // B1 — Exchange/payment
  {
    id: 'mp-28',
    category: 'por_para',
    level: 'B1',
    sentence: 'Pagué cien euros ___ este abrigo.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR for exchange or payment. You traded money for the coat.',
    explanationEs: 'Usa POR para intercambios o pagos. Cambiaste dinero por el abrigo.',
    contrast: "Compare: 'Compré este abrigo PARA el invierno' — PARA for the intended purpose.",
  },
  // B1 — On behalf of / in favor of
  {
    id: 'mp-29',
    category: 'por_para',
    level: 'B1',
    sentence: 'Voto ___ la democracia.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to mean "in favor of" or "in support of."',
    explanationEs: 'Usa POR con el significado de "a favor de" o "en apoyo de."',
    contrast: "Compare: 'Trabajo PARA una ONG' — PARA to indicate who you work for (employer).",
  },
  // B1 — Employer
  {
    id: 'mp-30',
    category: 'por_para',
    level: 'B1',
    sentence: 'Mi padre trabaja ___ una empresa internacional.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Use PARA to indicate the employer or entity you work for.',
    explanationEs: 'Usa PARA para indicar la empresa o entidad para la que trabajas.',
    contrast: "Compare: 'Trabaja POR necesidad' — POR for the reason/cause behind working.",
  },
  // B2 — Fixed expression: por ejemplo
  {
    id: 'mp-31',
    category: 'por_para',
    level: 'B2',
    sentence: 'Hay muchas opciones, ___ ejemplo, el tren.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: '"Por ejemplo" is a fixed expression meaning "for example."',
    explanationEs: '"Por ejemplo" es una expresión fija que significa "for example."',
    contrast: "Compare: 'PARA empezar, tomemos el tren' — PARA in the fixed phrase 'para empezar' (to begin with).",
  },
  // B2 — Fixed expression: para siempre
  {
    id: 'mp-32',
    category: 'por_para',
    level: 'B2',
    sentence: 'Te querré ___ siempre.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: '"Para siempre" is a fixed expression meaning "forever."',
    explanationEs: '"Para siempre" es una expresión fija que significa "forever."',
    contrast: "Compare: 'POR ahora, todo está bien' — POR in the fixed phrase 'por ahora' (for now).",
  },
  // B2 — Means/method
  {
    id: 'mp-33',
    category: 'por_para',
    level: 'B2',
    sentence: 'Envié el documento ___ correo electrónico.',
    answer: 'por',
    wrongAnswer: 'para',
    options: ['por', 'para'],
    explanation: 'Use POR to indicate the means or method of communication or transport.',
    explanationEs: 'Usa POR para indicar el medio de comunicación o transporte.',
    contrast: "Compare: 'El documento es PARA el director' — PARA for the intended recipient.",
  },
  // C1 — Considering / in spite of
  {
    id: 'mp-34',
    category: 'por_para',
    level: 'C1',
    sentence: '___ ser tan joven, habla con mucha madurez.',
    answer: 'Para',
    wrongAnswer: 'Por',
    options: ['Por', 'Para'],
    explanation: 'PARA + infinitive can mean "considering" or "for (someone who is...)." It expresses a surprising contrast.',
    explanationEs: 'PARA + infinitivo puede significar "teniendo en cuenta que." Expresa un contraste sorprendente.',
    contrast: "Compare: 'POR ser tan joven, no lo contrataron' — POR for cause (because he was so young).",
  },
  // C1 — "Estar por" vs "estar para"
  {
    id: 'mp-35',
    category: 'por_para',
    level: 'C1',
    sentence: 'El tren está ___ salir.',
    answer: 'para',
    wrongAnswer: 'por',
    options: ['por', 'para'],
    explanation: 'Estar PARA + infinitive = about to do something (imminent action).',
    explanationEs: 'Estar PARA + infinitivo = estar a punto de hacer algo (acción inminente).',
    contrast: "Compare: 'Está POR verse' — estar POR + infinitive = remains to be (done/seen).",
  },

  // ──────────────────────────────────────
  //  PRETÉRITO vs IMPERFECTO  (18 items)
  // ──────────────────────────────────────

  // A2 — Completed single action
  {
    id: 'mp-36',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Ayer ___ una película. (ver, yo)',
    answer: 'vi',
    wrongAnswer: 'veía',
    options: ['vi', 'veía'],
    explanation: 'Use the PRETERITE for a completed action at a specific time. "Ayer" marks a finished event.',
    explanationEs: 'Usa el PRETÉRITO para una acción terminada en un momento concreto. "Ayer" marca un evento finalizado.',
    contrast: "Compare: 'De niño, VEÍA películas todos los sábados' — IMPERFECT for habitual past actions.",
  },
  // A2 — Habitual action
  {
    id: 'mp-37',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Cuando era niño, ___ al parque todos los días. (ir, yo)',
    answer: 'iba',
    wrongAnswer: 'fui',
    options: ['fui', 'iba'],
    explanation: 'Use the IMPERFECT for habitual or repeated actions in the past. "Todos los días" is the key marker.',
    explanationEs: 'Usa el IMPERFECTO para acciones habituales en el pasado. "Todos los días" es la clave.',
    contrast: "Compare: 'Ayer FUI al parque' — PRETERITE for a single completed visit.",
  },
  // A2 — Description in the past (weather)
  {
    id: 'mp-38',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Aquella tarde ___ mucho sol. (hacer)',
    answer: 'hacía',
    wrongAnswer: 'hizo',
    options: ['hizo', 'hacía'],
    explanation: 'Use the IMPERFECT for background descriptions: weather, setting, atmosphere.',
    explanationEs: 'Usa el IMPERFECTO para descripciones de fondo: clima, ambiente, escenario.',
    contrast: "Compare: 'Ayer HIZO mucho frío' — PRETERITE when reporting weather as a completed fact of the day.",
  },
  // A2 — Age in the past
  {
    id: 'mp-39',
    category: 'pret_imp',
    level: 'A2',
    sentence: 'Cuando ___ diez años, me mudé a otra ciudad. (tener, yo)',
    answer: 'tenía',
    wrongAnswer: 'tuve',
    options: ['tuve', 'tenía'],
    explanation: 'Use the IMPERFECT for age in the past. Age is background information, not an event.',
    explanationEs: 'Usa el IMPERFECTO para la edad en el pasado. La edad es información de fondo, no un evento.',
    contrast: "Compare: 'TUVE un accidente a los diez años' — PRETERITE for the event that happened at that age.",
  },
  // A2 — Time in the past
  {
    id: 'mp-40',
    category: 'pret_imp',
    level: 'A2',
    sentence: '___ las tres de la tarde cuando llegaron. (ser)',
    answer: 'Eran',
    wrongAnswer: 'Fueron',
    options: ['Fueron', 'Eran'],
    explanation: 'Use the IMPERFECT for telling time in the past. It sets the scene.',
    explanationEs: 'Usa el IMPERFECTO para decir la hora en el pasado. Establece el escenario.',
    contrast: "Compare: 'La reunión FUE a las tres' — PRETERITE for a scheduled event that took place.",
  },
  // B1 — Interruption pattern
  {
    id: 'mp-41',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'Mientras yo ___, sonó el teléfono. (dormir)',
    answer: 'dormía',
    wrongAnswer: 'dormí',
    options: ['dormí', 'dormía'],
    explanation: 'IMPERFECT for the ongoing background action that gets interrupted. "Mientras" signals duration.',
    explanationEs: 'IMPERFECTO para la acción de fondo que se interrumpe. "Mientras" indica duración.',
    contrast: "Compare: 'Anoche DORMÍ ocho horas' — PRETERITE for a completed duration of sleep.",
  },
  // B1 — The interrupting action
  {
    id: 'mp-42',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'Leía un libro cuando alguien ___ a la puerta. (llamar)',
    answer: 'llamó',
    wrongAnswer: 'llamaba',
    options: ['llamó', 'llamaba'],
    explanation: 'PRETERITE for the sudden interrupting action that breaks into the background scene.',
    explanationEs: 'PRETÉRITO para la acción repentina que interrumpe el escenario de fondo.',
    contrast: "Compare: 'Siempre LLAMABA antes de venir' — IMPERFECT for a habitual action (he always used to call).",
  },
  // B1 — Specific time marker: "una vez"
  {
    id: 'mp-43',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'Una vez ___ a un famoso en la calle. (ver, yo)',
    answer: 'vi',
    wrongAnswer: 'veía',
    options: ['vi', 'veía'],
    explanation: '"Una vez" (once) marks a single, specific event. Use the PRETERITE.',
    explanationEs: '"Una vez" marca un evento único y concreto. Usa el PRETÉRITO.',
    contrast: "Compare: 'Siempre lo VEÍA en la televisión' — IMPERFECT for something habitual.",
  },
  // B1 — Ongoing emotion in the past
  {
    id: 'mp-44',
    category: 'pret_imp',
    level: 'B1',
    sentence: 'De joven, ___ mucho a mis abuelos. (querer, yo)',
    answer: 'quería',
    wrongAnswer: 'quise',
    options: ['quise', 'quería'],
    explanation: 'IMPERFECT for ongoing emotional states in the past. Loving grandparents was continuous.',
    explanationEs: 'IMPERFECTO para estados emocionales continuos en el pasado. Querer a los abuelos era algo constante.',
    contrast: "Compare: 'QUISE llamarlos, pero no pude' — PRETERITE quise = I tried/wanted to (at a specific moment).",
  },
  // B2 — Meaning change: conocer (met vs knew)
  {
    id: 'mp-45',
    category: 'pret_imp',
    level: 'B2',
    sentence: '___ a mi esposa en la universidad. (conocer, yo)',
    answer: 'Conocí',
    wrongAnswer: 'Conocía',
    options: ['Conocí', 'Conocía'],
    explanation: 'PRETERITE of conocer = "met" (the beginning of knowing). It marks the first encounter.',
    explanationEs: 'PRETÉRITO de conocer = "conocí" (el inicio de conocer). Marca el primer encuentro.',
    contrast: "Compare: 'Ya CONOCÍA a tu hermano' — IMPERFECT conocía = already knew (ongoing state).",
  },
  // B2 — Meaning change: saber (found out vs knew)
  {
    id: 'mp-46',
    category: 'pret_imp',
    level: 'B2',
    sentence: '___ la verdad cuando leí la carta. (saber, yo)',
    answer: 'Supe',
    wrongAnswer: 'Sabía',
    options: ['Supe', 'Sabía'],
    explanation: 'PRETERITE of saber = "found out" (the moment of learning). The letter triggered the discovery.',
    explanationEs: 'PRETÉRITO de saber = "me enteré" (el momento de descubrirlo). La carta desencadenó el descubrimiento.',
    contrast: "Compare: 'Ya SABÍA la verdad' — IMPERFECT sabía = already knew (prior knowledge).",
  },
  // B2 — Meaning change: poder (managed vs could)
  {
    id: 'mp-47',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'Después de mucho esfuerzo, ___ abrir la puerta. (poder, yo)',
    answer: 'pude',
    wrongAnswer: 'podía',
    options: ['pude', 'podía'],
    explanation: 'PRETERITE of poder = "managed to / succeeded in." The effort led to a completed result.',
    explanationEs: 'PRETÉRITO de poder = "logré." El esfuerzo llevó a un resultado concreto.',
    contrast: "Compare: 'De niño, PODÍA correr muy rápido' — IMPERFECT podía = had the ability to (general capacity).",
  },
  // B2 — Emotional state change
  {
    id: 'mp-48',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'Cuando vi el accidente, ___ mucho miedo. (tener, yo)',
    answer: 'tuve',
    wrongAnswer: 'tenía',
    options: ['tuve', 'tenía'],
    explanation: 'PRETERITE for a sudden onset of emotion triggered by a specific event.',
    explanationEs: 'PRETÉRITO para una emoción repentina provocada por un evento concreto.',
    contrast: "Compare: 'De niño, TENÍA miedo a la oscuridad' — IMPERFECT for an ongoing emotional state.",
  },
  // B2 — Narration vs description
  {
    id: 'mp-49',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'La mujer ___ un vestido rojo y llevaba un sombrero. (llevar)',
    answer: 'llevaba',
    wrongAnswer: 'llevó',
    options: ['llevó', 'llevaba'],
    explanation: 'IMPERFECT for physical descriptions of people in a past narrative. It paints the scene.',
    explanationEs: 'IMPERFECTO para descripciones físicas en una narración pasada. Pinta la escena.',
    contrast: "Compare: 'Se LLEVÓ el vestido rojo' — PRETERITE for the completed action of taking the dress.",
  },
  // B2 — Two simultaneous ongoing actions
  {
    id: 'mp-50',
    category: 'pret_imp',
    level: 'B2',
    sentence: 'Mientras ella ___, él preparaba la cena. (estudiar)',
    answer: 'estudiaba',
    wrongAnswer: 'estudió',
    options: ['estudió', 'estudiaba'],
    explanation: 'IMPERFECT for two actions happening simultaneously in the past. "Mientras" connects them.',
    explanationEs: 'IMPERFECTO para dos acciones simultáneas en el pasado. "Mientras" las conecta.',
    contrast: "Compare: 'ESTUDIÓ toda la noche y luego se durmió' — PRETERITE for sequential completed actions.",
  },
  // C1 — Sequence of completed events
  {
    id: 'mp-51',
    category: 'pret_imp',
    level: 'C1',
    sentence: 'Se levantó, se vistió y ___ de casa. (salir)',
    answer: 'salió',
    wrongAnswer: 'salía',
    options: ['salió', 'salía'],
    explanation: 'PRETERITE for a chain of sequential completed actions. Each one follows the previous.',
    explanationEs: 'PRETÉRITO para una cadena de acciones completadas en secuencia. Cada una sigue a la anterior.',
    contrast: "Compare: 'Cada mañana SALÍA de casa a las ocho' — IMPERFECT for a repeated daily routine.",
  },
  // C1 — "Querer" meaning change
  {
    id: 'mp-52',
    category: 'pret_imp',
    level: 'C1',
    sentence: '___ decírtelo, pero no encontré el momento. (querer, yo)',
    answer: 'Quise',
    wrongAnswer: 'Quería',
    options: ['Quise', 'Quería'],
    explanation: 'PRETERITE quise = "I tried to" (attempted but failed). The second clause confirms failure.',
    explanationEs: 'PRETÉRITO quise = "intenté" (lo intenté pero no pude). La segunda parte confirma el fracaso.',
    contrast: "Compare: 'QUERÍA decírtelo' — IMPERFECT quería = I wanted to (ongoing desire, no attempt implied).",
  },
  // C1 — Politeness / softened request (imperfect)
  {
    id: 'mp-53',
    category: 'pret_imp',
    level: 'C1',
    sentence: '___ pedirte un favor. (querer, yo)',
    answer: 'Quería',
    wrongAnswer: 'Quise',
    options: ['Quise', 'Quería'],
    explanation: 'IMPERFECT quería is used for polite, softened requests in the present. It sounds less direct.',
    explanationEs: 'IMPERFECTO quería se usa para peticiones suaves en el presente. Suena menos directo.',
    contrast: "Compare: 'QUISE pedirte un favor, pero no me atreví' — PRETERITE quise = tried to ask (and failed).",
  },

  // ──────────────────────────────────────
  //  FALSE COGNATES / Falsos Amigos  (40 items)
  // ──────────────────────────────────────

  // A1 — embarazado ≠ embarrassed
  {
    id: 'mp-54',
    category: 'false_cognates',
    level: 'A1',
    sentence: 'Estoy muy ___; dije algo tonto delante de todos.',
    answer: 'avergonzado',
    wrongAnswer: 'embarazado',
    options: ['embarazado', 'avergonzado'],
    explanation: '"Embarazado" means pregnant, NOT embarrassed. Use "avergonzado" for embarrassed.',
    explanationEs: '"Embarazado" significa pregnant en inglés. Usa "avergonzado" para expresar vergüenza.',
    contrast: "False friend: 'embarazado' looks like 'embarrassed' but means 'pregnant.'",
  },
  // A1 — librería ≠ library
  {
    id: 'mp-55',
    category: 'false_cognates',
    level: 'A1',
    sentence: 'Voy a la ___ a devolver unos libros prestados.',
    answer: 'biblioteca',
    wrongAnswer: 'librería',
    options: ['librería', 'biblioteca'],
    explanation: '"Librería" means bookstore, NOT library. A "biblioteca" is where you borrow books.',
    explanationEs: '"Librería" es donde se compran libros. "Biblioteca" es donde se prestan.',
    contrast: "False friend: 'librería' looks like 'library' but means 'bookstore.'",
  },

  // A2 — actualmente ≠ actually
  {
    id: 'mp-56',
    category: 'false_cognates',
    level: 'A2',
    sentence: '___, prefiero el té al café.',
    answer: 'En realidad',
    wrongAnswer: 'Actualmente',
    options: ['Actualmente', 'En realidad'],
    explanation: '"Actualmente" means currently/nowadays, NOT actually. Use "en realidad" for actually.',
    explanationEs: '"Actualmente" significa currently. Usa "en realidad" para decir actually.',
    contrast: "False friend: 'actualmente' looks like 'actually' but means 'currently/nowadays.'",
  },
  // A2 — éxito ≠ exit
  {
    id: 'mp-57',
    category: 'false_cognates',
    level: 'A2',
    sentence: 'Busco la ___ para salir del edificio.',
    answer: 'salida',
    wrongAnswer: 'éxito',
    options: ['éxito', 'salida'],
    explanation: '"Éxito" means success, NOT exit. Use "salida" for exit.',
    explanationEs: '"Éxito" significa success. "Salida" es the exit.',
    contrast: "False friend: 'éxito' looks like 'exit' but means 'success.'",
  },
  // A2 — sensible ≠ sensible
  {
    id: 'mp-58',
    category: 'false_cognates',
    level: 'A2',
    sentence: 'Ella es muy ___; siempre toma decisiones lógicas.',
    answer: 'sensata',
    wrongAnswer: 'sensible',
    options: ['sensible', 'sensata'],
    explanation: '"Sensible" in Spanish means sensitive, NOT sensible/reasonable. Use "sensato/a."',
    explanationEs: '"Sensible" en español significa sensitive. Usa "sensato/a" para reasonable.',
    contrast: "False friend: Spanish 'sensible' looks like English 'sensible' but means 'sensitive.'",
  },
  // A2 — carpeta ≠ carpet
  {
    id: 'mp-59',
    category: 'false_cognates',
    level: 'A2',
    sentence: 'La ___ del salón es de color azul.',
    answer: 'alfombra',
    wrongAnswer: 'carpeta',
    options: ['carpeta', 'alfombra'],
    explanation: '"Carpeta" means folder/binder, NOT carpet. Use "alfombra" for carpet/rug.',
    explanationEs: '"Carpeta" significa folder. Usa "alfombra" para carpet.',
    contrast: "False friend: 'carpeta' looks like 'carpet' but means 'folder.'",
  },

  // B1 — realizar ≠ to realize
  {
    id: 'mp-60',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'No me ___ de que era tan tarde.',
    answer: 'di cuenta',
    wrongAnswer: 'realicé',
    options: ['realicé', 'di cuenta'],
    explanation: '"Realizar" means to carry out/accomplish, NOT to realize. Use "darse cuenta de."',
    explanationEs: '"Realizar" significa to carry out. Usa "darse cuenta de" para to realize.',
    contrast: "False friend: 'realizar' looks like 'to realize' but means 'to carry out/accomplish.'",
  },
  // B1 — largo ≠ large
  {
    id: 'mp-61',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'Su casa es muy ___; tiene diez habitaciones.',
    answer: 'grande',
    wrongAnswer: 'larga',
    options: ['larga', 'grande'],
    explanation: '"Largo" means long, NOT large. A spacious house with many rooms is "grande."',
    explanationEs: '"Largo" significa long. Una casa espaciosa con muchas habitaciones es "grande."',
    contrast: "False friend: 'largo' looks like 'large' but means 'long.'",
  },
  // B1 — recordar ≠ to record
  {
    id: 'mp-62',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'Quiero ___ esta canción en el estudio.',
    answer: 'grabar',
    wrongAnswer: 'recordar',
    options: ['recordar', 'grabar'],
    explanation: '"Recordar" means to remember, NOT to record. Use "grabar" for to record.',
    explanationEs: '"Recordar" significa to remember. Usa "grabar" para to record.',
    contrast: "False friend: 'recordar' looks like 'to record' but means 'to remember.'",
  },
  // B1 — constipado ≠ constipated
  {
    id: 'mp-63',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'No puedo ir al baño; creo que estoy ___.',
    answer: 'estreñido',
    wrongAnswer: 'constipado',
    options: ['constipado', 'estreñido'],
    explanation: '"Constipado" means having a cold, NOT constipated. Use "estreñido" for constipated.',
    explanationEs: '"Constipado" significa having a cold. Usa "estreñido" para constipated.',
    contrast: "False friend: 'constipado' looks like 'constipated' but means 'having a cold.'",
  },
  // B1 — atender ≠ to attend / asistir ≠ to assist
  {
    id: 'mp-64',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'Mañana voy a ___ a una conferencia sobre tecnología.',
    answer: 'asistir',
    wrongAnswer: 'atender',
    options: ['atender', 'asistir'],
    explanation: '"Atender" means to serve/assist, NOT to attend. Use "asistir a" for to attend.',
    explanationEs: '"Atender" significa to serve. Usa "asistir a" para to attend.',
    contrast: "Double false friend: 'asistir' = to attend (not to assist); 'atender' = to serve (not to attend).",
  },

  // B2 — excitado ≠ excited
  {
    id: 'mp-65',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'Estoy muy ___ por el viaje de mañana.',
    answer: 'emocionado',
    wrongAnswer: 'excitado',
    options: ['excitado', 'emocionado'],
    explanation: '"Excitado" has a sexual connotation in Spanish. Use "emocionado" for excited/thrilled.',
    explanationEs: '"Excitado" tiene connotación sexual. Usa "emocionado" para excited.',
    contrast: "False friend: 'excitado' looks like 'excited' but implies sexual arousal in Spanish.",
  },
  // B2 — introducir ≠ to introduce (a person)
  {
    id: 'mp-66',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'Quiero ___ a mi amiga María.',
    answer: 'presentarte',
    wrongAnswer: 'introducirte',
    options: ['introducirte', 'presentarte'],
    explanation: '"Introducir" means to insert or put in, NOT to introduce a person. Use "presentar."',
    explanationEs: '"Introducir" significa to insert. Usa "presentar" para introduce a person.',
    contrast: "False friend: 'introducir' looks like 'to introduce' but means 'to insert/put in.'",
  },
  // B2 — pretender ≠ to pretend
  {
    id: 'mp-67',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'El niño ___ estar enfermo para no ir al colegio.',
    answer: 'fingió',
    wrongAnswer: 'pretendió',
    options: ['pretendió', 'fingió'],
    explanation: '"Pretender" means to intend/attempt, NOT to pretend/fake. Use "fingir" for to pretend.',
    explanationEs: '"Pretender" significa to intend. Usa "fingir" para to pretend.',
    contrast: "False friend: 'pretender' looks like 'to pretend' but means 'to intend/attempt.'",
  },
  // B2 — suceso ≠ success
  {
    id: 'mp-68',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'Su nuevo libro ha sido un gran ___.',
    answer: 'éxito',
    wrongAnswer: 'suceso',
    options: ['suceso', 'éxito'],
    explanation: '"Suceso" means event/incident, NOT success. Use "éxito" for success.',
    explanationEs: '"Suceso" significa event/incident. Usa "éxito" para success.',
    contrast: "False friend: 'suceso' looks like 'success' but means 'event/incident.'",
  },

  // C1 — eventualmente ≠ eventually
  {
    id: 'mp-69',
    category: 'false_cognates',
    level: 'C1',
    sentence: '___, después de muchos intentos, lo consiguió.',
    answer: 'Finalmente',
    wrongAnswer: 'Eventualmente',
    options: ['Eventualmente', 'Finalmente'],
    explanation: '"Eventualmente" means possibly/by chance, NOT eventually. Use "finalmente."',
    explanationEs: '"Eventualmente" significa possibly. Usa "finalmente" para eventually.',
    contrast: "False friend: 'eventualmente' looks like 'eventually' but means 'possibly/by chance.'",
  },
  // C1 — comprensivo ≠ comprehensive
  {
    id: 'mp-70',
    category: 'false_cognates',
    level: 'C1',
    sentence: 'El informe es muy ___; cubre todos los aspectos del tema.',
    answer: 'exhaustivo',
    wrongAnswer: 'comprensivo',
    options: ['comprensivo', 'exhaustivo'],
    explanation: '"Comprensivo" means understanding/sympathetic, NOT comprehensive. Use "exhaustivo."',
    explanationEs: '"Comprensivo" significa understanding. Usa "exhaustivo" para comprehensive.',
    contrast: "False friend: 'comprensivo' looks like 'comprehensive' but means 'understanding/sympathetic.'",
  },
  // C1 — soportar ≠ to support
  {
    id: 'mp-71',
    category: 'false_cognates',
    level: 'C1',
    sentence: 'Siempre puedo contar contigo; tú me ___ en todo.',
    answer: 'apoyas',
    wrongAnswer: 'soportas',
    options: ['soportas', 'apoyas'],
    explanation: '"Soportar" means to tolerate/endure, NOT to support. Use "apoyar" for to support.',
    explanationEs: '"Soportar" significa to tolerate. Usa "apoyar" para to support.',
    contrast: "False friend: 'soportar' looks like 'to support' but means 'to tolerate/endure.'",
  },

  // A1 — ropa ≠ rope
  {
    id: 'mp-72',
    category: 'false_cognates',
    level: 'A1',
    sentence: 'Necesito una ___ para atar la caja.',
    answer: 'cuerda',
    wrongAnswer: 'ropa',
    options: ['ropa', 'cuerda'],
    explanation: '"Ropa" means clothes, NOT rope. Use "cuerda" for rope.',
    explanationEs: '"Ropa" significa clothes. Usa "cuerda" para rope.',
    contrast: "False friend: 'ropa' looks like 'rope' but means 'clothes.'",
  },
  // A1 — sopa ≠ soap
  {
    id: 'mp-73',
    category: 'false_cognates',
    level: 'A1',
    sentence: 'Necesito ___ para lavarme las manos.',
    answer: 'jabón',
    wrongAnswer: 'sopa',
    options: ['sopa', 'jabón'],
    explanation: '"Sopa" means soup, NOT soap. Use "jabón" for soap.',
    explanationEs: '"Sopa" significa soup. Usa "jabón" para soap.',
    contrast: "False friend: 'sopa' looks like 'soap' but means 'soup.'",
  },

  // A2 — fábrica ≠ fabric
  {
    id: 'mp-74',
    category: 'false_cognates',
    level: 'A2',
    sentence: 'Esta ___ es muy suave; perfecta para hacer una camisa.',
    answer: 'tela',
    wrongAnswer: 'fábrica',
    options: ['fábrica', 'tela'],
    explanation: '"Fábrica" means factory, NOT fabric. Use "tela" for fabric/cloth.',
    explanationEs: '"Fábrica" significa factory. Usa "tela" para fabric.',
    contrast: "False friend: 'fábrica' looks like 'fabric' but means 'factory.'",
  },
  // A2 — pie ≠ pie
  {
    id: 'mp-75',
    category: 'false_cognates',
    level: 'A2',
    sentence: 'De postre quiero un ___ de manzana.',
    answer: 'pastel',
    wrongAnswer: 'pie',
    options: ['pie', 'pastel'],
    explanation: '"Pie" in Spanish means foot, NOT the dessert. Use "pastel" or "tarta" for pie.',
    explanationEs: '"Pie" significa foot. Usa "pastel" o "tarta" para the dessert pie.',
    contrast: "False friend: 'pie' looks like English 'pie' but means 'foot.'",
  },
  // A2 — contestar ≠ to contest
  {
    id: 'mp-76',
    category: 'false_cognates',
    level: 'A2',
    sentence: 'El abogado va a ___ la decisión del juez.',
    answer: 'impugnar',
    wrongAnswer: 'contestar',
    options: ['contestar', 'impugnar'],
    explanation: '"Contestar" means to answer/reply, NOT to contest. Use "impugnar" for to contest.',
    explanationEs: '"Contestar" significa to answer. Usa "impugnar" para to contest.',
    contrast: "False friend: 'contestar' looks like 'to contest' but means 'to answer.'",
  },
  // A2 — molestar ≠ to molest
  {
    id: 'mp-77',
    category: 'false_cognates',
    level: 'A2',
    sentence: 'El ruido de la calle me ___; no puedo dormir.',
    answer: 'molesta',
    wrongAnswer: 'none',
    options: ['molesta', 'irrita'],
    explanation: '"Molestar" means to annoy/bother, NOT to molest. It is perfectly innocent in Spanish.',
    explanationEs: '"Molestar" significa to annoy/bother. Es una palabra inocente en español.',
    contrast: "False friend: 'molestar' looks like 'to molest' but simply means 'to annoy/bother.'",
  },

  // B1 — delito ≠ delight
  {
    id: 'mp-78',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'Comer chocolate es un verdadero ___.',
    answer: 'deleite',
    wrongAnswer: 'delito',
    options: ['delito', 'deleite'],
    explanation: '"Delito" means crime/offense, NOT delight. Use "deleite" for delight.',
    explanationEs: '"Delito" significa crime. Usa "deleite" para delight.',
    contrast: "False friend: 'delito' looks like 'delight' but means 'crime.'",
  },
  // B1 — pariente ≠ parent
  {
    id: 'mp-79',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'Mis ___ vienen a cenar esta noche; mi madre cocina.',
    answer: 'padres',
    wrongAnswer: 'parientes',
    options: ['parientes', 'padres'],
    explanation: '"Pariente" means relative, NOT parent. Use "padres" for parents.',
    explanationEs: '"Pariente" significa relative. Usa "padres" para parents.',
    contrast: "False friend: 'pariente' looks like 'parent' but means 'relative.'",
  },
  // B1 — colegio ≠ college
  {
    id: 'mp-80',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'Mi hermana estudia medicina en la ___.',
    answer: 'universidad',
    wrongAnswer: 'colegio',
    options: ['colegio', 'universidad'],
    explanation: '"Colegio" means school (K-12), NOT college/university. Use "universidad."',
    explanationEs: '"Colegio" es una escuela primaria o secundaria. Usa "universidad" para college.',
    contrast: "False friend: 'colegio' looks like 'college' but means 'school.'",
  },
  // B1 — carta ≠ card
  {
    id: 'mp-81',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'Le envié una ___ de cumpleaños por correo.',
    answer: 'tarjeta',
    wrongAnswer: 'carta',
    options: ['carta', 'tarjeta'],
    explanation: '"Carta" means letter (written message), NOT card. Use "tarjeta" for card.',
    explanationEs: '"Carta" significa letter. Usa "tarjeta" para card.',
    contrast: "False friend: 'carta' looks like 'card' but means 'letter.'",
  },
  // B1 — disgusto ≠ disgust
  {
    id: 'mp-82',
    category: 'false_cognates',
    level: 'B1',
    sentence: 'La comida podrida me da mucho ___.',
    answer: 'asco',
    wrongAnswer: 'disgusto',
    options: ['disgusto', 'asco'],
    explanation: '"Disgusto" means annoyance/upset, NOT disgust. Use "asco" for disgust.',
    explanationEs: '"Disgusto" significa annoyance/upset. Usa "asco" para disgust.',
    contrast: "False friend: 'disgusto' looks like 'disgust' but means 'annoyance/displeasure.'",
  },

  // B2 — lectura ≠ lecture
  {
    id: 'mp-83',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'El profesor dio una ___ muy interesante sobre historia.',
    answer: 'conferencia',
    wrongAnswer: 'lectura',
    options: ['lectura', 'conferencia'],
    explanation: '"Lectura" means reading, NOT lecture. Use "conferencia" or "charla" for lecture.',
    explanationEs: '"Lectura" significa reading. Usa "conferencia" o "charla" para lecture.',
    contrast: "False friend: 'lectura' looks like 'lecture' but means 'reading.'",
  },
  // B2 — enviar ≠ to envy
  {
    id: 'mp-84',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'Yo ___ a los que pueden viajar tanto.',
    answer: 'envidio',
    wrongAnswer: 'envío',
    options: ['envío', 'envidio'],
    explanation: '"Enviar" means to send, NOT to envy. Use "envidiar" for to envy.',
    explanationEs: '"Enviar" significa to send. Usa "envidiar" para to envy.',
    contrast: "False friend: 'enviar' looks like 'to envy' but means 'to send.'",
  },
  // B2 — vaso ≠ vase
  {
    id: 'mp-85',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'Pon las flores en el ___ con agua.',
    answer: 'jarrón',
    wrongAnswer: 'vaso',
    options: ['vaso', 'jarrón'],
    explanation: '"Vaso" means drinking glass, NOT vase. Use "jarrón" or "florero" for vase.',
    explanationEs: '"Vaso" significa drinking glass. Usa "jarrón" o "florero" para vase.',
    contrast: "False friend: 'vaso' looks like 'vase' but means 'drinking glass.'",
  },
  // B2 — parada ≠ parade
  {
    id: 'mp-86',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'El ___ del Día de la Independencia fue espectacular.',
    answer: 'desfile',
    wrongAnswer: 'parada',
    options: ['parada', 'desfile'],
    explanation: '"Parada" means stop (e.g. bus stop), NOT parade. Use "desfile" for parade.',
    explanationEs: '"Parada" significa stop. Usa "desfile" para parade.',
    contrast: "False friend: 'parada' looks like 'parade' but means 'stop.'",
  },
  // B2 — tuna ≠ tuna (fish)
  {
    id: 'mp-87',
    category: 'false_cognates',
    level: 'B2',
    sentence: 'Quiero un sándwich de ___.',
    answer: 'atún',
    wrongAnswer: 'tuna',
    options: ['tuna', 'atún'],
    explanation: '"Tuna" in Spanish means prickly pear (cactus fruit), NOT tuna fish. Use "atún."',
    explanationEs: '"Tuna" es la fruta del nopal. Usa "atún" para tuna fish.',
    contrast: "False friend: 'tuna' looks like English 'tuna' but means 'prickly pear.'",
  },

  // C1 — bizarro ≠ bizarre
  {
    id: 'mp-88',
    category: 'false_cognates',
    level: 'C1',
    sentence: 'Ese cuadro es muy ___; no lo entiendo.',
    answer: 'extraño',
    wrongAnswer: 'bizarro',
    options: ['bizarro', 'extraño'],
    explanation: '"Bizarro" traditionally means brave/dashing, NOT bizarre. Use "extraño" for bizarre.',
    explanationEs: '"Bizarro" tradicionalmente significa brave/gallant. Usa "extraño" para bizarre.',
    contrast: "False friend: 'bizarro' looks like 'bizarre' but traditionally means 'brave/gallant.'",
  },
  // C1 — compromiso ≠ compromise
  {
    id: 'mp-89',
    category: 'false_cognates',
    level: 'C1',
    sentence: 'Después de mucho debate, llegaron a un ___.',
    answer: 'acuerdo',
    wrongAnswer: 'compromiso',
    options: ['compromiso', 'acuerdo'],
    explanation: '"Compromiso" means commitment/obligation, NOT compromise. Use "acuerdo" for compromise.',
    explanationEs: '"Compromiso" significa commitment/obligation. Usa "acuerdo" para compromise.',
    contrast: "False friend: 'compromiso' looks like 'compromise' but means 'commitment/obligation.'",
  },
  // C1 — desgracia ≠ disgrace
  {
    id: 'mp-90',
    category: 'false_cognates',
    level: 'C1',
    sentence: 'Su comportamiento fue una ___; toda la familia lo rechazó.',
    answer: 'vergüenza',
    wrongAnswer: 'desgracia',
    options: ['desgracia', 'vergüenza'],
    explanation: '"Desgracia" means misfortune, NOT disgrace. Use "vergüenza" for disgrace.',
    explanationEs: '"Desgracia" significa misfortune. Usa "vergüenza" para disgrace.',
    contrast: "False friend: 'desgracia' looks like 'disgrace' but means 'misfortune.'",
  },
  // C1 — preservativo ≠ preservative
  {
    id: 'mp-91',
    category: 'false_cognates',
    level: 'C1',
    sentence: 'Este alimento no contiene ___ artificiales.',
    answer: 'conservantes',
    wrongAnswer: 'preservativos',
    options: ['preservativos', 'conservantes'],
    explanation: '"Preservativo" means condom, NOT preservative. Use "conservante" for food preservative.',
    explanationEs: '"Preservativo" significa condom. Usa "conservante" para food preservative.',
    contrast: "False friend: 'preservativo' looks like 'preservative' but means 'condom.'",
  },

  // C2 — casualidad ≠ casualty
  {
    id: 'mp-92',
    category: 'false_cognates',
    level: 'C2',
    sentence: 'El accidente causó muchas ___.',
    answer: 'víctimas',
    wrongAnswer: 'casualidades',
    options: ['casualidades', 'víctimas'],
    explanation: '"Casualidad" means coincidence, NOT casualty. Use "víctima" for casualty.',
    explanationEs: '"Casualidad" significa coincidence. Usa "víctima" para casualty.',
    contrast: "False friend: 'casualidad' looks like 'casualty' but means 'coincidence.'",
  },
  // C2 — últimamente ≠ ultimately
  {
    id: 'mp-93',
    category: 'false_cognates',
    level: 'C2',
    sentence: '___, la decisión depende de ti.',
    answer: 'Al final',
    wrongAnswer: 'Últimamente',
    options: ['Últimamente', 'Al final'],
    explanation: '"Últimamente" means recently/lately, NOT ultimately. Use "al final" for ultimately.',
    explanationEs: '"Últimamente" significa recently. Usa "al final" para ultimately.',
    contrast: "False friend: 'últimamente' looks like 'ultimately' but means 'recently/lately.'",
  },

  // ──────────────────────────────────────
  //  DUAL-GENDER NOUNS  (12 items)
  //  Nouns that take el or la depending
  //  on the person's gender
  // ──────────────────────────────────────

  // A1
  {
    id: 'mp-94',
    category: 'dual_gender',
    level: 'A1',
    sentence: 'María es ___ mejor estudiante de la clase.',
    answer: 'la',
    wrongAnswer: 'el',
    options: ['el', 'la'],
    explanation: '"Estudiante" can be masculine or feminine. María is female, so use "la."',
    explanationEs: '"Estudiante" puede ser masculino o femenino. María es mujer, así que se usa "la."',
    contrast: 'If it were Pedro: "Pedro es EL mejor estudiante de la clase."',
  },
  {
    id: 'mp-95',
    category: 'dual_gender',
    level: 'A1',
    sentence: 'Mi abuelo es ___ artista más famoso del pueblo.',
    answer: 'el',
    wrongAnswer: 'la',
    options: ['el', 'la'],
    explanation: '"Artista" is dual-gender. "Abuelo" (grandfather) is male, so use "el."',
    explanationEs: '"Artista" es de género común. "Abuelo" es masculino, así que se usa "el."',
    contrast: 'With a female referent: "Mi abuela es LA artista más famosa del pueblo."',
  },
  {
    id: 'mp-96',
    category: 'dual_gender',
    level: 'A1',
    sentence: 'La señora López es ___ turista más entusiasta del grupo.',
    answer: 'la',
    wrongAnswer: 'el',
    options: ['el', 'la'],
    explanation: '"Turista" takes the article matching the person\'s gender. La señora López is female.',
    explanationEs: '"Turista" adopta el artículo según el género de la persona. La señora López es mujer.',
    contrast: 'With a male referent: "El señor López es EL turista más entusiasta del grupo."',
  },
  {
    id: 'mp-97',
    category: 'dual_gender',
    level: 'A1',
    sentence: 'Mi hermana quiere ser ___ dentista como mi madre.',
    answer: 'la',
    wrongAnswer: 'el',
    options: ['el', 'la'],
    explanation: '"Dentista" is dual-gender. "Hermana" and "madre" are female, so use "la."',
    explanationEs: '"Dentista" es de género común. "Hermana" y "madre" son femeninos, así que se usa "la."',
    contrast: 'With a male referent: "Mi hermano quiere ser EL dentista como mi padre."',
  },
  // A2
  {
    id: 'mp-98',
    category: 'dual_gender',
    level: 'A2',
    sentence: 'Don Carlos fue ___ periodista más respetado del país.',
    answer: 'el',
    wrongAnswer: 'la',
    options: ['el', 'la'],
    explanation: '"Periodista" is dual-gender. "Don Carlos" is male, so use "el."',
    explanationEs: '"Periodista" es de género común. "Don Carlos" es masculino, así que se usa "el."',
    contrast: 'With a female referent: "Doña Carmen fue LA periodista más respetada del país."',
  },
  {
    id: 'mp-99',
    category: 'dual_gender',
    level: 'A2',
    sentence: 'Sofía es ___ pianista del conservatorio.',
    answer: 'la',
    wrongAnswer: 'el',
    options: ['el', 'la'],
    explanation: '"Pianista" is dual-gender. Sofía is a female name, so use "la."',
    explanationEs: '"Pianista" es de género común. Sofía es nombre de mujer, así que se usa "la."',
    contrast: 'With a male referent: "Andrés es EL pianista del conservatorio."',
  },
  {
    id: 'mp-100',
    category: 'dual_gender',
    level: 'A2',
    sentence: 'Mi hijo es ___ ciclista más joven del equipo.',
    answer: 'el',
    wrongAnswer: 'la',
    options: ['el', 'la'],
    explanation: '"Ciclista" is dual-gender. "Hijo" (son) is male, so use "el."',
    explanationEs: '"Ciclista" es de género común. "Hijo" es masculino, así que se usa "el."',
    contrast: 'With a female referent: "Mi hija es LA ciclista más joven del equipo."',
  },
  {
    id: 'mp-101',
    category: 'dual_gender',
    level: 'A2',
    sentence: 'Ella es ___ atleta más rápida de su generación.',
    answer: 'la',
    wrongAnswer: 'el',
    options: ['el', 'la'],
    explanation: '"Atleta" is dual-gender. "Ella" (she) is female, so use "la."',
    explanationEs: '"Atleta" es de género común. "Ella" es femenino, así que se usa "la."',
    contrast: 'With a male referent: "Él es EL atleta más rápido de su generación."',
  },
  {
    id: 'mp-102',
    category: 'dual_gender',
    level: 'A2',
    sentence: 'Marta es ___ futbolista que marcó el gol.',
    answer: 'la',
    wrongAnswer: 'el',
    options: ['el', 'la'],
    explanation: '"Futbolista" is dual-gender. Marta is a female name, so use "la."',
    explanationEs: '"Futbolista" es de género común. Marta es nombre de mujer, así que se usa "la."',
    contrast: 'With a male referent: "Diego es EL futbolista que marcó el gol."',
  },
  {
    id: 'mp-103',
    category: 'dual_gender',
    level: 'A2',
    sentence: 'El capitán es ___ piloto con más experiencia.',
    answer: 'el',
    wrongAnswer: 'la',
    options: ['el', 'la'],
    explanation: '"Piloto" is dual-gender. "Capitán" is masculine, so use "el."',
    explanationEs: '"Piloto" es de género común. "Capitán" es masculino, así que se usa "el."',
    contrast: 'With a female referent: "La capitana es LA piloto con más experiencia."',
  },
  {
    id: 'mp-104',
    category: 'dual_gender',
    level: 'A2',
    sentence: 'Ana es ___ colega que me ayudó con el proyecto.',
    answer: 'la',
    wrongAnswer: 'el',
    options: ['el', 'la'],
    explanation: '"Colega" is dual-gender. Ana is a female name, so use "la."',
    explanationEs: '"Colega" es de género común. Ana es nombre de mujer, así que se usa "la."',
    contrast: 'With a male referent: "Juan es EL colega que me ayudó con el proyecto."',
  },
  {
    id: 'mp-105',
    category: 'dual_gender',
    level: 'A1',
    sentence: '___ joven del vestido rojo es mi prima.',
    answer: 'La',
    wrongAnswer: 'El',
    options: ['El', 'La'],
    explanation: '"Joven" is dual-gender. "Prima" (female cousin) tells us the person is female, so use "La."',
    explanationEs: '"Joven" es de género común. "Prima" indica que es mujer, así que se usa "La."',
    contrast: 'With a male referent: "EL joven de la camisa azul es mi primo."',
  },

  // ──────────────────────────────────────
  //  FALSE-FRIEND GENDER PAIRS  (12 items)
  //  -o / -a words that are NOT just
  //  masc/fem of the same word
  // ──────────────────────────────────────

  // A2
  {
    id: 'mp-106',
    category: 'gendered_pairs',
    level: 'A2',
    sentence: 'Perdí mi ___ con las llaves y la billetera dentro.',
    answer: 'bolso',
    wrongAnswer: 'bolsa',
    options: ['bolso', 'bolsa'],
    explanation: '"Bolso" is a purse/handbag. "Bolsa" is a bag (shopping bag) or the stock market.',
    explanationEs: '"Bolso" es un bolso de mano. "Bolsa" es una bolsa de compras o la bolsa de valores.',
    contrast: 'Compare: "La BOLSA de valores cayó un 5%" — the stock market.',
  },
  {
    id: 'mp-107',
    category: 'gendered_pairs',
    level: 'A2',
    sentence: 'Fui al ___ a sacar dinero del cajero automático.',
    answer: 'banco',
    wrongAnswer: 'banca',
    options: ['banco', 'banca'],
    explanation: '"Banco" is a physical bank (or bench). "Banca" is the banking sector/industry.',
    explanationEs: '"Banco" es el banco físico (o un asiento). "Banca" es el sector bancario.',
    contrast: 'Compare: "La BANCA electrónica facilita las transferencias" — the banking industry.',
  },
  {
    id: 'mp-108',
    category: 'gendered_pairs',
    level: 'A2',
    sentence: 'Hay un ___ de Picasso en el museo.',
    answer: 'cuadro',
    wrongAnswer: 'cuadra',
    options: ['cuadro', 'cuadra'],
    explanation: '"Cuadro" is a painting or picture frame. "Cuadra" is a city block (Latin America) or stable.',
    explanationEs: '"Cuadro" es una pintura o marco. "Cuadra" es una manzana (Latinoamérica) o un establo.',
    contrast: 'Compare: "El supermercado está a dos CUADRAS de aquí" — two blocks away.',
  },
  {
    id: 'mp-109',
    category: 'gendered_pairs',
    level: 'A2',
    sentence: 'Necesito comprar ___ nuevo para la lluvia.',
    answer: 'calzado',
    wrongAnswer: 'calzada',
    options: ['calzado', 'calzada'],
    explanation: '"Calzado" means footwear/shoes. "Calzada" is a road or lane.',
    explanationEs: '"Calzado" significa zapatos. "Calzada" es una vía o carretera.',
    contrast: 'Compare: "La CALZADA estaba mojada después de la lluvia" — the road surface.',
  },
  {
    id: 'mp-110',
    category: 'gendered_pairs',
    level: 'A2',
    sentence: 'La ___ del cuchillo está muy afilada.',
    answer: 'punta',
    wrongAnswer: 'punto',
    options: ['punto', 'punta'],
    explanation: '"Punta" is a tip or point (physical end). "Punto" is a point (score, period, argument).',
    explanationEs: '"Punta" es el extremo o punta física. "Punto" es un punto (puntuación, signo, argumento).',
    contrast: 'Compare: "No entiendo tu PUNTO" — I don\'t understand your point (argument).',
  },
  {
    id: 'mp-111',
    category: 'gendered_pairs',
    level: 'A2',
    sentence: 'El barco llegó al ___ a las seis de la mañana.',
    answer: 'puerto',
    wrongAnswer: 'puerta',
    options: ['puerto', 'puerta'],
    explanation: '"Puerto" is a port/harbor. "Puerta" is a door or gate.',
    explanationEs: '"Puerto" es un puerto marítimo. "Puerta" es una puerta o entrada.',
    contrast: 'Compare: "Cierra la PUERTA, por favor" — close the door.',
  },
  // B1
  {
    id: 'mp-112',
    category: 'gendered_pairs',
    level: 'B1',
    sentence: 'La ___ del zapato está desgastada.',
    answer: 'suela',
    wrongAnswer: 'suelo',
    options: ['suelo', 'suela'],
    explanation: '"Suela" is the sole (of a shoe). "Suelo" is the floor or ground.',
    explanationEs: '"Suela" es la suela del zapato. "Suelo" es el piso o la tierra.',
    contrast: 'Compare: "El SUELO de la cocina está limpio" — the kitchen floor.',
  },
  {
    id: 'mp-113',
    category: 'gendered_pairs',
    level: 'B1',
    sentence: 'La ___ este año es llevar colores brillantes.',
    answer: 'moda',
    wrongAnswer: 'modo',
    options: ['modo', 'moda'],
    explanation: '"Moda" is fashion/trend. "Modo" is a way/manner of doing something.',
    explanationEs: '"Moda" es la tendencia o estilo. "Modo" es la manera o forma de hacer algo.',
    contrast: 'Compare: "De este MODO resolveremos el problema" — in this way.',
  },
  {
    id: 'mp-114',
    category: 'gendered_pairs',
    level: 'B1',
    sentence: 'En ___ de emergencia, llama al 112.',
    answer: 'caso',
    wrongAnswer: 'casa',
    options: ['caso', 'casa'],
    explanation: '"Caso" means case/event. "Casa" means house/home.',
    explanationEs: '"Caso" significa situación o evento. "Casa" significa hogar o vivienda.',
    contrast: 'Compare: "Vamos a CASA" — let\'s go home.',
  },
  {
    id: 'mp-115',
    category: 'gendered_pairs',
    level: 'B1',
    sentence: 'La ___ de esta región es deliciosa.',
    answer: 'fruta',
    wrongAnswer: 'fruto',
    options: ['fruto', 'fruta'],
    explanation: '"Fruta" is edible fruit (the food). "Fruto" is a fruit in the botanical or figurative sense (result/outcome).',
    explanationEs: '"Fruta" es la fruta comestible. "Fruto" es el fruto botánico o figurado (resultado).',
    contrast: 'Compare: "El éxito es el FRUTO de mucho trabajo" — the fruit (result) of hard work.',
  },
  {
    id: 'mp-116',
    category: 'gendered_pairs',
    level: 'B1',
    sentence: 'Necesitamos más ___ para la chimenea.',
    answer: 'leña',
    wrongAnswer: 'leño',
    options: ['leño', 'leña'],
    explanation: '"Leña" is firewood (collective, what you burn). "Leño" is a single log or piece of wood.',
    explanationEs: '"Leña" es la madera para quemar (colectivo). "Leño" es un tronco individual.',
    contrast: 'Compare: "Pon otro LEÑO en el fuego" — put another log on the fire.',
  },
  {
    id: 'mp-117',
    category: 'gendered_pairs',
    level: 'B1',
    sentence: 'Pon la ropa sucia en ___ de mimbre.',
    answer: 'el cesto',
    wrongAnswer: 'la cesta',
    options: ['el cesto', 'la cesta'],
    explanation: '"Cesto" is a large basket (laundry hamper, wastebasket). "Cesta" is a smaller, handled basket.',
    explanationEs: '"Cesto" es un cesto grande (para ropa, basura). "Cesta" es una cesta más pequeña con asa.',
    contrast: 'Compare: "Llevó una CESTA de picnic al parque" — a picnic basket.',
  },

  // ──────────────────────────────────────
  //  NEAR-MISS WORDS  (10 items)
  //  Words one letter apart with
  //  completely different meanings
  // ──────────────────────────────────────

  // A1
  {
    id: 'mp-118',
    category: 'near_miss',
    level: 'A1',
    sentence: 'Tengo ___ hermanos en total.',
    answer: 'nueve',
    wrongAnswer: 'nuevo',
    options: ['nuevo', 'nueva', 'nueve'],
    explanation: '"Nueve" is the number 9. "Nuevo/nueva" means new (masc/fem). Numbers don\'t change for gender.',
    explanationEs: '"Nueve" es el número 9. "Nuevo/nueva" significa new. Los números no cambian de género.',
    contrast: 'Compare: "Tengo un coche NUEVO" (a new car) vs. "Tengo NUEVE coches" (nine cars).',
  },
  {
    id: 'mp-119',
    category: 'near_miss',
    level: 'A1',
    sentence: '___ libro es muy interesante.',
    answer: 'Este',
    wrongAnswer: 'Esto',
    options: ['Esto', 'Esta', 'Este'],
    explanation: '"Este" (masc. demonstrative) goes before masculine nouns. "Esta" before feminine. "Esto" is neuter — never before a noun.',
    explanationEs: '"Este" (demostrativo masc.) va antes de sustantivos masculinos. "Esta" antes de femeninos. "Esto" es neutro, nunca va antes de un sustantivo.',
    contrast: 'Compare: "¿Qué es ESTO?" (What is this?) — neuter pronoun, no noun follows.',
  },
  {
    id: 'mp-120',
    category: 'near_miss',
    level: 'A1',
    sentence: '¿Qué es ___? No lo entiendo.',
    answer: 'esto',
    wrongAnswer: 'este',
    options: ['esto', 'esta', 'este'],
    explanation: '"Esto" is the neuter demonstrative pronoun — used when not referring to a specific noun. "Este/esta" are adjectives that go before nouns.',
    explanationEs: '"Esto" es el pronombre demostrativo neutro — se usa sin sustantivo. "Este/esta" son adjetivos que van antes de sustantivos.',
    contrast: 'Compare: "ESTE libro es interesante" — "este" modifies a masculine noun.',
  },
  // A2
  {
    id: 'mp-121',
    category: 'near_miss',
    level: 'A2',
    sentence: 'Vivo en el ___ piso del edificio.',
    answer: 'cuarto',
    wrongAnswer: 'cuatro',
    options: ['cuatro', 'cuarto', 'cuarta'],
    explanation: '"Cuarto" means fourth (ordinal, masc.) or room. "Cuatro" is the number 4. "Cuarta" is fourth (fem.).',
    explanationEs: '"Cuarto" es cuarto (ordinal, masc.) o habitación. "Cuatro" es el número 4. "Cuarta" es cuarto (fem.).',
    contrast: 'Compare: "Hay CUATRO pisos" (there are four floors) — cardinal number.',
  },
  {
    id: 'mp-122',
    category: 'near_miss',
    level: 'A2',
    sentence: 'La ___ del restaurante fue de cincuenta euros.',
    answer: 'cuenta',
    wrongAnswer: 'ciento',
    options: ['ciento', 'cuenta'],
    explanation: '"Cuenta" means bill/check or account. "Ciento" means one hundred. They look similar but are unrelated.',
    explanationEs: '"Cuenta" es la factura o una cuenta. "Ciento" es el número cien.',
    contrast: 'Compare: "CIENTO veinte personas asistieron" — 120 people.',
  },
  {
    id: 'mp-123',
    category: 'near_miss',
    level: 'A1',
    sentence: 'Quiero ir al parque, ___ está lloviendo.',
    answer: 'pero',
    wrongAnswer: 'pera',
    options: ['pero', 'pera', 'perro'],
    explanation: '"Pero" means but. "Pera" is a pear (fruit). "Perro" is a dog. Three very different words, one letter apart.',
    explanationEs: '"Pero" significa but. "Pera" es la fruta. "Perro" es el animal.',
    contrast: 'Compare: "Me comí una PERA" (I ate a pear) vs. "Mi PERRO es grande" (My dog is big).',
  },
  {
    id: 'mp-124',
    category: 'near_miss',
    level: 'A2',
    sentence: 'Este hotel es muy ___; cuesta 300 euros la noche.',
    answer: 'caro',
    wrongAnswer: 'carro',
    options: ['caro', 'cara', 'carro'],
    explanation: '"Caro" means expensive (masc.). "Cara" means face, or expensive (fem.). "Carro" means car (Latin America) or cart.',
    explanationEs: '"Caro" significa expensive (masc.). "Cara" es el rostro, o expensive (fem.). "Carro" es un automóvil o carreta.',
    contrast: 'Compare: "Lávate la CARA" (wash your face) vs. "Compré un CARRO nuevo" (I bought a new car).',
  },
  {
    id: 'mp-125',
    category: 'near_miss',
    level: 'A2',
    sentence: 'El primer ___ es cruzar la calle con cuidado.',
    answer: 'paso',
    wrongAnswer: 'pase',
    options: ['paso', 'pasa', 'pase'],
    explanation: '"Paso" is a step. "Pasa" is a raisin, or the verb form "happens/passes." "Pase" is a pass (ticket/permit) or subjunctive "pass."',
    explanationEs: '"Paso" es un paso. "Pasa" es una uva pasa o del verbo pasar. "Pase" es un permiso o subjuntivo de pasar.',
    contrast: 'Compare: "¿Qué PASA?" (What\'s happening?) vs. "Necesito un PASE de acceso" (I need an access pass).',
  },
  {
    id: 'mp-126',
    category: 'near_miss',
    level: 'A1',
    sentence: 'La temperatura es ___ grados.',
    answer: 'cero',
    wrongAnswer: 'cera',
    options: ['cero', 'cera'],
    explanation: '"Cero" is the number zero. "Cera" is wax.',
    explanationEs: '"Cero" es el número 0. "Cera" es la cera (de vela).',
    contrast: 'Compare: "La vela está hecha de CERA" — the candle is made of wax.',
  },
  {
    id: 'mp-127',
    category: 'near_miss',
    level: 'B1',
    sentence: 'La policía inició una ___ para encontrar al sospechoso.',
    answer: 'caza',
    wrongAnswer: 'casa',
    options: ['casa', 'caso', 'caza'],
    explanation: '"Caza" means hunt/chase. "Casa" means house. "Caso" means case/event. All one letter apart.',
    explanationEs: '"Caza" es la acción de cazar. "Casa" es el hogar. "Caso" es una situación.',
    contrast: 'Compare: "Vamos a CASA" (let\'s go home) vs. "En ese CASO, vamos" (in that case, let\'s go).',
  },

  // ──────────────────────────────────────
  //  DIPHTHONG vs HIATUS  (12 items)
  // ──────────────────────────────────────

  {
    id: 'mp-128',
    category: 'diphthong_hiatus',
    level: 'A1',
    sentence: 'En "aire," las vocales A-I forman un ___.',
    answer: 'diptongo',
    wrongAnswer: 'hiato',
    options: ['diptongo', 'hiato'],
    explanation: 'A (strong) + I (weak unstressed) combine in one syllable: ai-re (2 syllables). Strong + weak unstressed = diphthong.',
    explanationEs: 'A (fuerte) + I (débil átona) se unen en una sílaba: ai-re (2 sílabas). Fuerte + débil átona = diptongo.',
    contrast: 'Compare: "pa-ís" — the accent on the I breaks the diphthong into a hiatus.',
  },
  {
    id: 'mp-129',
    category: 'diphthong_hiatus',
    level: 'A1',
    sentence: 'En "país," las vocales A-Í forman un ___.',
    answer: 'hiato',
    wrongAnswer: 'diptongo',
    options: ['diptongo', 'hiato'],
    explanation: 'The accent on Í makes it stressed, breaking the diphthong: pa-ís (2 syllables). A written accent on a weak vowel always creates a hiatus.',
    explanationEs: 'La tilde sobre la Í la convierte en tónica, rompiendo el diptongo: pa-ís (2 sílabas). Una tilde sobre vocal débil siempre crea un hiato.',
    contrast: 'Compare: "ai-re" — the I is unstressed, so it stays a diphthong.',
  },
  {
    id: 'mp-130',
    category: 'diphthong_hiatus',
    level: 'A1',
    sentence: 'En "bueno," las vocales U-E forman un ___.',
    answer: 'diptongo',
    wrongAnswer: 'hiato',
    options: ['diptongo', 'hiato'],
    explanation: 'U (weak unstressed) + E (strong) combine in one syllable: bue-no (2 syllables). Weak unstressed + strong = diphthong.',
    explanationEs: 'U (débil átona) + E (fuerte) se unen en una sílaba: bue-no (2 sílabas). Débil átona + fuerte = diptongo.',
    contrast: 'Compare: "ba-úl" — an accent on the weak vowel U breaks it into a hiatus.',
  },
  {
    id: 'mp-131',
    category: 'diphthong_hiatus',
    level: 'A2',
    sentence: 'En "río," las vocales Í-O forman un ___.',
    answer: 'hiato',
    wrongAnswer: 'diptongo',
    options: ['diptongo', 'hiato'],
    explanation: 'The accent on Í makes it stressed, breaking the combination: rí-o (2 syllables). Accented weak vowel + strong vowel = hiatus.',
    explanationEs: 'La tilde sobre la Í la hace tónica, separando la combinación: rí-o (2 sílabas). Débil tónica + fuerte = hiato.',
    contrast: 'Compare: "vio" — the I is unstressed, so I-O stays a diphthong (1 syllable).',
  },
  {
    id: 'mp-132',
    category: 'diphthong_hiatus',
    level: 'A2',
    sentence: 'En "ciudad," las vocales I-U forman un ___.',
    answer: 'diptongo',
    wrongAnswer: 'hiato',
    options: ['diptongo', 'hiato'],
    explanation: 'I (weak) + U (weak), both unstressed, combine in one syllable: ciu-dad (2 syllables). Two weak vowels together always form a diphthong.',
    explanationEs: 'I (débil) + U (débil), ambas átonas, se unen en una sílaba: ciu-dad (2 sílabas). Dos vocales débiles juntas siempre forman diptongo.',
    contrast: 'Two weak vowels always form a diphthong unless one has an accent mark.',
  },
  {
    id: 'mp-133',
    category: 'diphthong_hiatus',
    level: 'A2',
    sentence: 'En "baúl," las vocales A-Ú forman un ___.',
    answer: 'hiato',
    wrongAnswer: 'diptongo',
    options: ['diptongo', 'hiato'],
    explanation: 'The accent on Ú makes it stressed, breaking the combination: ba-úl (2 syllables). Strong + accented weak = hiatus.',
    explanationEs: 'La tilde sobre la Ú la hace tónica, separando: ba-úl (2 sílabas). Fuerte + débil tónica = hiato.',
    contrast: 'Compare: "cau-sa" — the U is unstressed, so A-U stays a diphthong.',
  },
  {
    id: 'mp-134',
    category: 'diphthong_hiatus',
    level: 'A2',
    sentence: 'En "fuego," las vocales U-E forman un ___.',
    answer: 'diptongo',
    wrongAnswer: 'hiato',
    options: ['diptongo', 'hiato'],
    explanation: 'U (weak unstressed) + E (strong) combine in one syllable: fue-go (2 syllables). Same pattern as "bueno".',
    explanationEs: 'U (débil átona) + E (fuerte) se unen en una sílaba: fue-go (2 sílabas). Mismo patrón que "bueno".',
    contrast: 'Compare: "dú-o" — two vowels in hiatus because they are two strong vowels (U is weak, but here both are in separate syllables).',
  },
  {
    id: 'mp-135',
    category: 'diphthong_hiatus',
    level: 'B1',
    sentence: 'En "oído," las vocales O-Í forman un ___.',
    answer: 'hiato',
    wrongAnswer: 'diptongo',
    options: ['diptongo', 'hiato'],
    explanation: 'The accent on Í makes it stressed: o-í-do (3 syllables). Strong + accented weak = hiatus.',
    explanationEs: 'La tilde sobre la Í la hace tónica: o-í-do (3 sílabas). Fuerte + débil tónica = hiato.',
    contrast: 'Compare: "oi-ga" — no accent on the I, so O-I stays a diphthong.',
  },
  {
    id: 'mp-136',
    category: 'diphthong_hiatus',
    level: 'B1',
    sentence: 'En "viaje," las vocales I-A forman un ___.',
    answer: 'diptongo',
    wrongAnswer: 'hiato',
    options: ['diptongo', 'hiato'],
    explanation: 'I (weak unstressed) + A (strong) combine in one syllable: via-je (2 syllables). Weak unstressed + strong = diphthong.',
    explanationEs: 'I (débil átona) + A (fuerte) se unen en una sílaba: via-je (2 sílabas). Débil átona + fuerte = diptongo.',
    contrast: 'Compare: "dí-a" — the accent on I creates a hiatus.',
  },
  {
    id: 'mp-137',
    category: 'diphthong_hiatus',
    level: 'B1',
    sentence: 'En "poeta," las vocales O-E forman un ___.',
    answer: 'hiato',
    wrongAnswer: 'diptongo',
    options: ['diptongo', 'hiato'],
    explanation: 'O (strong) + E (strong) = two strong vowels always form a hiatus: po-e-ta (3 syllables). No exceptions.',
    explanationEs: 'O (fuerte) + E (fuerte) = dos vocales fuertes siempre forman hiato: po-e-ta (3 sílabas). Sin excepciones.',
    contrast: 'Rule: A+E, A+O, E+O (and reverse) are always hiatus.',
  },
  {
    id: 'mp-138',
    category: 'diphthong_hiatus',
    level: 'B1',
    sentence: 'En "causa," las vocales A-U forman un ___.',
    answer: 'diptongo',
    wrongAnswer: 'hiato',
    options: ['diptongo', 'hiato'],
    explanation: 'A (strong) + U (weak unstressed) combine in one syllable: cau-sa (2 syllables). Strong + weak unstressed = diphthong.',
    explanationEs: 'A (fuerte) + U (débil átona) se unen en una sílaba: cau-sa (2 sílabas). Fuerte + débil átona = diptongo.',
    contrast: 'Compare: "ba-úl" — the accent on U breaks it into a hiatus.',
  },
  {
    id: 'mp-139',
    category: 'diphthong_hiatus',
    level: 'B1',
    sentence: 'En "ahora," las vocales A-O forman un ___.',
    answer: 'hiato',
    wrongAnswer: 'diptongo',
    options: ['diptongo', 'hiato'],
    explanation: 'A (strong) + O (strong) = two strong vowels always form a hiatus: a-ho-ra (3 syllables). The silent H does not prevent the hiatus.',
    explanationEs: 'A (fuerte) + O (fuerte) = dos vocales fuertes siempre forman hiato: a-ho-ra (3 sílabas). La H muda no impide el hiato.',
    contrast: 'Rule: two strong vowels (A, E, O) are always in separate syllables, even with H between them.',
  },

  // ──────────────────────────────────────
  //  TILDE RULES  (12 items)
  // ──────────────────────────────────────

  {
    id: 'mp-140',
    category: 'stress_tilde',
    level: 'A1',
    sentence: '¿"Examen" necesita tilde?',
    answer: 'no necesita tilde',
    wrongAnswer: 'necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Examen" is stressed on the second-to-last syllable (e-XA-men) and ends in N. Words ending in vowel, N, or S with penultimate stress (llanas) do NOT need a tilde.',
    explanationEs: '"Examen" es llana (e-XA-men) y termina en N. Las palabras llanas terminadas en vocal, N o S NO llevan tilde.',
    contrast: 'Compare: "camión" also ends in N, but stress is on the LAST syllable (aguda), so it DOES need a tilde.',
  },
  {
    id: 'mp-141',
    category: 'stress_tilde',
    level: 'A1',
    sentence: '¿"Camión" necesita tilde?',
    answer: 'necesita tilde',
    wrongAnswer: 'no necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Camión" is stressed on the last syllable (ca-MIÓN) and ends in N. Words ending in vowel, N, or S with final stress (agudas) DO need a tilde.',
    explanationEs: '"Camión" es aguda (ca-MIÓN) y termina en N. Las palabras agudas terminadas en vocal, N o S SÍ llevan tilde.',
    contrast: 'Compare: "examen" also ends in N but stress is penultimate (llana), so no tilde.',
  },
  {
    id: 'mp-142',
    category: 'stress_tilde',
    level: 'A2',
    sentence: '¿"Fácil" necesita tilde?',
    answer: 'necesita tilde',
    wrongAnswer: 'no necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Fácil" is stressed on the second-to-last syllable (FÁ-cil) and ends in L. Words ending in a consonant other than N or S with penultimate stress (llanas) DO need a tilde.',
    explanationEs: '"Fácil" es llana (FÁ-cil) y termina en L. Las palabras llanas terminadas en consonante distinta de N o S SÍ llevan tilde.',
    contrast: 'Compare: "papel" ends in L with last-syllable stress (aguda), so it does NOT need a tilde.',
  },
  {
    id: 'mp-143',
    category: 'stress_tilde',
    level: 'A2',
    sentence: '¿"Papel" necesita tilde?',
    answer: 'no necesita tilde',
    wrongAnswer: 'necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Papel" is stressed on the last syllable (pa-PEL) and ends in L. Words ending in a consonant other than N or S with final stress (agudas) do NOT need a tilde.',
    explanationEs: '"Papel" es aguda (pa-PEL) y termina en L. Las palabras agudas terminadas en consonante distinta de N o S NO llevan tilde.',
    contrast: 'Compare: "fácil" also ends in L but stress is penultimate (llana), so it DOES need a tilde.',
  },
  {
    id: 'mp-144',
    category: 'stress_tilde',
    level: 'A2',
    sentence: '¿"Joven" necesita tilde?',
    answer: 'no necesita tilde',
    wrongAnswer: 'necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Joven" is stressed on the second-to-last syllable (JO-ven) and ends in N. Llana ending in N = no tilde needed.',
    explanationEs: '"Joven" es llana (JO-ven) y termina en N. Llana terminada en N = no necesita tilde.',
    contrast: 'Compare: "jardín" ends in N with last-syllable stress (aguda), so it needs a tilde.',
  },
  {
    id: 'mp-145',
    category: 'stress_tilde',
    level: 'A2',
    sentence: '¿"Jardín" necesita tilde?',
    answer: 'necesita tilde',
    wrongAnswer: 'no necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Jardín" is stressed on the last syllable (jar-DÍN) and ends in N. Aguda ending in N = needs a tilde.',
    explanationEs: '"Jardín" es aguda (jar-DÍN) y termina en N. Aguda terminada en N = necesita tilde.',
    contrast: 'Compare: "joven" ends in N with penultimate stress (llana), so no tilde needed.',
  },
  {
    id: 'mp-146',
    category: 'stress_tilde',
    level: 'B1',
    sentence: '¿"Árbol" necesita tilde?',
    answer: 'necesita tilde',
    wrongAnswer: 'no necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Árbol" is stressed on the second-to-last syllable (ÁR-bol) and ends in L. Llana ending in L (not N/S/vowel) = needs a tilde.',
    explanationEs: '"Árbol" es llana (ÁR-bol) y termina en L. Llana terminada en L (no N/S/vocal) = necesita tilde.',
    contrast: 'Compare: "reloj" ends in a consonant with last-syllable stress (aguda), so no tilde.',
  },
  {
    id: 'mp-147',
    category: 'stress_tilde',
    level: 'B1',
    sentence: '¿"Reloj" necesita tilde?',
    answer: 'no necesita tilde',
    wrongAnswer: 'necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Reloj" is stressed on the last syllable (re-LOJ) and ends in J. Aguda ending in a consonant other than N or S = no tilde.',
    explanationEs: '"Reloj" es aguda (re-LOJ) y termina en J. Aguda terminada en consonante distinta de N o S = no necesita tilde.',
    contrast: 'Compare: "árbol" ends in a consonant too, but with penultimate stress (llana), so it needs one.',
  },
  {
    id: 'mp-148',
    category: 'stress_tilde',
    level: 'B1',
    sentence: '¿"Música" necesita tilde?',
    answer: 'necesita tilde',
    wrongAnswer: 'no necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Música" is stressed on the third-to-last syllable (MÚ-si-ca). Words with antepenultimate stress (esdrújulas) ALWAYS need a tilde, no exceptions.',
    explanationEs: '"Música" es esdrújula (MÚ-si-ca). Las esdrújulas SIEMPRE llevan tilde, sin excepción.',
    contrast: 'Every esdrújula needs a tilde: pájaro, sábado, médico, teléfono.',
  },
  {
    id: 'mp-149',
    category: 'stress_tilde',
    level: 'B1',
    sentence: '¿"Teléfono" necesita tilde?',
    answer: 'necesita tilde',
    wrongAnswer: 'no necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Teléfono" is stressed on the third-to-last syllable (te-LÉ-fo-no). Esdrújula = always needs a tilde.',
    explanationEs: '"Teléfono" es esdrújula (te-LÉ-fo-no). Esdrújula = siempre lleva tilde.',
    contrast: 'All 4+ syllable words with antepenultimate stress follow this rule: pájaro, sábado, médico.',
  },
  {
    id: 'mp-150',
    category: 'stress_tilde',
    level: 'B1',
    sentence: '¿"También" necesita tilde?',
    answer: 'necesita tilde',
    wrongAnswer: 'no necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"También" is stressed on the last syllable (tam-BIÉN) and ends in N. Aguda ending in N = needs a tilde.',
    explanationEs: '"También" es aguda (tam-BIÉN) y termina en N. Aguda terminada en N = necesita tilde.',
    contrast: 'Note: "bien" alone is a monosyllable, so no tilde. "También" has two syllables, so the aguda rule applies.',
  },
  {
    id: 'mp-151',
    category: 'stress_tilde',
    level: 'B2',
    sentence: '¿"Caracteres" necesita tilde?',
    answer: 'no necesita tilde',
    wrongAnswer: 'necesita tilde',
    options: ['necesita tilde', 'no necesita tilde'],
    explanation: '"Caracteres" is stressed on the second-to-last syllable (ca-rac-TE-res) and ends in S. Llana ending in S = no tilde. Note: the singular "carácter" IS esdrújula and needs a tilde.',
    explanationEs: '"Caracteres" es llana (ca-rac-TE-res) y termina en S. Llana terminada en S = no necesita tilde. El singular "carácter" SÍ es esdrújula y lleva tilde.',
    contrast: 'This word shifts stress between singular (ca-RÁC-ter, esdrújula) and plural (ca-rac-TE-res, llana).',
  },
];
