'use strict';

// ════════════════════════════════════════
//  SPANISH PHONETIC PAIR DRILLS
//  R vs RR and other sound contrasts
// ════════════════════════════════════════

const PHONETIC_PAIR_CATEGORIES = {
  r_rr: {
    id: 'r_rr',
    label: 'R vs RR',
    labelEs: 'R contra RR',
    description: 'Single tap /ɾ/ versus rolled trill /r/. One letter changes the meaning.',
    descriptionEs: 'Vibrante simple /ɾ/ contra vibrante múltiple /r/. Una letra cambia el significado.',
    ipa: ['/ɾ/', '/r/'],
    tip: 'Single r: tongue taps the roof of the mouth once (like "tt" in American "butter"). Double rr: tongue trills with multiple taps.',
    tipEs: 'R simple: la lengua toca el paladar una vez. RR doble: la lengua vibra varias veces.',
  },
};

const PHONETIC_PAIRS = [

  // ──────────────────────────────────────
  //  R vs RR  (10 pairs)
  // ──────────────────────────────────────

  // A1 — Very common words
  {
    id: 'pp-1',
    category: 'r_rr',
    level: 'A1',
    wordA: 'caro',
    wordB: 'carro',
    ipaA: '/ˈka.ɾo/',
    ipaB: '/ˈka.ro/',
    meaningA: 'expensive',
    meaningAEs: 'costoso',
    meaningB: 'car',
    meaningBEs: 'automóvil',
    exampleA: 'Este restaurante es muy ___.',
    exampleAEn: 'This restaurant is very expensive.',
    exampleB: 'Mi ___ es rojo.',
    exampleBEn: 'My car is red.',
  },
  {
    id: 'pp-2',
    category: 'r_rr',
    level: 'A1',
    wordA: 'pero',
    wordB: 'perro',
    ipaA: '/ˈpe.ɾo/',
    ipaB: '/ˈpe.ro/',
    meaningA: 'but',
    meaningAEs: 'conjunción adversativa',
    meaningB: 'dog',
    meaningBEs: 'animal doméstico',
    exampleA: 'Quiero ir, ___ no puedo.',
    exampleAEn: 'I want to go, but I cannot.',
    exampleB: 'El ___ está en el jardín.',
    exampleBEn: 'The dog is in the garden.',
  },
  {
    id: 'pp-3',
    category: 'r_rr',
    level: 'A1',
    wordA: 'para',
    wordB: 'parra',
    ipaA: '/ˈpa.ɾa/',
    ipaB: '/ˈpa.ra/',
    meaningA: 'for / in order to',
    meaningAEs: 'preposición de finalidad',
    meaningB: 'grapevine',
    meaningBEs: 'planta de uva',
    exampleA: 'Este regalo es ___ ti.',
    exampleAEn: 'This gift is for you.',
    exampleB: 'La ___ da muchas uvas en verano.',
    exampleBEn: 'The grapevine produces many grapes in summer.',
  },

  // A2 — Common words, slightly less frequent
  {
    id: 'pp-4',
    category: 'r_rr',
    level: 'A2',
    wordA: 'coro',
    wordB: 'corro',
    ipaA: '/ˈko.ɾo/',
    ipaB: '/ˈko.ro/',
    meaningA: 'choir',
    meaningAEs: 'grupo que canta',
    meaningB: 'I run',
    meaningBEs: 'primera persona de correr',
    exampleA: 'Canto en el ___ de la iglesia.',
    exampleAEn: 'I sing in the church choir.',
    exampleB: 'Yo ___ todas las mañanas.',
    exampleBEn: 'I run every morning.',
  },
  {
    id: 'pp-5',
    category: 'r_rr',
    level: 'A2',
    wordA: 'cero',
    wordB: 'cerro',
    ipaA: '/ˈse.ɾo/',
    ipaB: '/ˈse.ro/',
    meaningA: 'zero',
    meaningAEs: 'el número 0',
    meaningB: 'hill',
    meaningBEs: 'elevación de terreno',
    exampleA: 'La temperatura bajó a ___ grados.',
    exampleAEn: 'The temperature dropped to zero degrees.',
    exampleB: 'Subimos al ___ para ver la ciudad.',
    exampleBEn: 'We climbed the hill to see the city.',
  },
  {
    id: 'pp-6',
    category: 'r_rr',
    level: 'A2',
    wordA: 'pera',
    wordB: 'perra',
    ipaA: '/ˈpe.ɾa/',
    ipaB: '/ˈpe.ra/',
    meaningA: 'pear',
    meaningAEs: 'fruta',
    meaningB: 'female dog',
    meaningBEs: 'hembra del perro',
    exampleA: 'Compré una ___ en el mercado.',
    exampleAEn: 'I bought a pear at the market.',
    exampleB: 'La ___ tuvo cinco cachorros.',
    exampleBEn: 'The female dog had five puppies.',
  },

  // B1 — Less frequent vocabulary
  {
    id: 'pp-7',
    category: 'r_rr',
    level: 'B1',
    wordA: 'coral',
    wordB: 'corral',
    ipaA: '/ko.ˈɾal/',
    ipaB: '/ko.ˈral/',
    meaningA: 'coral',
    meaningAEs: 'organismo marino',
    meaningB: 'pen / yard',
    meaningBEs: 'recinto para animales',
    exampleA: 'El arrecife de ___ es impresionante.',
    exampleAEn: 'The coral reef is impressive.',
    exampleB: 'Las gallinas están en el ___.',
    exampleBEn: 'The chickens are in the pen.',
  },
  {
    id: 'pp-8',
    category: 'r_rr',
    level: 'B1',
    wordA: 'foro',
    wordB: 'forro',
    ipaA: '/ˈfo.ɾo/',
    ipaB: '/ˈfo.ro/',
    meaningA: 'forum',
    meaningAEs: 'lugar de debate',
    meaningB: 'lining / cover',
    meaningBEs: 'revestimiento interior',
    exampleA: 'Publicó su pregunta en el ___.',
    exampleAEn: 'She posted her question on the forum.',
    exampleB: 'El ___ del abrigo es de seda.',
    exampleBEn: 'The lining of the coat is silk.',
  },
  {
    id: 'pp-9',
    category: 'r_rr',
    level: 'B1',
    wordA: 'moro',
    wordB: 'morro',
    ipaA: '/ˈmo.ɾo/',
    ipaB: '/ˈmo.ro/',
    meaningA: 'Moor',
    meaningAEs: 'habitante del norte de África',
    meaningB: 'snout / knoll',
    meaningBEs: 'hocico / colina',
    exampleA: 'La arquitectura ___ se ve en la Alhambra.',
    exampleAEn: 'Moorish architecture is seen in the Alhambra.',
    exampleB: 'El gato tiene el ___ mojado.',
    exampleBEn: 'The cat has a wet snout.',
  },
  {
    id: 'pp-10',
    category: 'r_rr',
    level: 'B1',
    wordA: 'vara',
    wordB: 'barra',
    ipaA: '/ˈba.ɾa/',
    ipaB: '/ˈba.ra/',
    meaningA: 'rod / stick',
    meaningAEs: 'palo delgado',
    meaningB: 'bar / rod',
    meaningBEs: 'pieza rígida alargada',
    exampleA: 'El pastor llevaba una ___ de madera.',
    exampleAEn: 'The shepherd carried a wooden rod.',
    exampleB: 'Nos sentamos en la ___ del café.',
    exampleBEn: 'We sat at the bar of the café.',
  },
];
