// phrases.js — Phrase database for Lección Diaria PWA
// 13 situations, 200+ phrases with replies, formality, and cultural notes

const PHRASES_SITUATIONS = [
  { slug: 'greetings', title: 'Saludos y Despedidas', titleEn: 'Greetings & Goodbyes', icon: '👋', desc: 'Say hello and goodbye' },
  { slug: 'politeness', title: 'Cortesía', titleEn: 'Politeness', icon: '🙏', desc: 'Please, thank you, sorry, and more' },
  { slug: 'introductions', title: 'Presentaciones', titleEn: 'Introductions', icon: '🤝', desc: 'Name, origin, and occupation' },
  { slug: 'directions', title: 'Direcciones', titleEn: 'Directions', icon: '🧭', desc: 'Where is it and how to get there' },
  { slug: 'food', title: 'Comida y Restaurante', titleEn: 'Food & Restaurant', icon: '🍽️', desc: 'Ordering, menus, and paying' },
  { slug: 'shopping', title: 'De Compras', titleEn: 'Shopping', icon: '🛍️', desc: 'Prices, sizes, and trying things on' },
  { slug: 'transport', title: 'Transporte', titleEn: 'Transport', icon: '🚌', desc: 'Bus, taxi, train, and airport' },
  { slug: 'health', title: 'Salud', titleEn: 'Health', icon: '🏥', desc: 'Doctor, pharmacy, and symptoms' },
  { slug: 'time', title: 'Hora y Fecha', titleEn: 'Time & Date', icon: '🕐', desc: 'Telling time, days, and appointments' },
  { slug: 'social', title: 'Conversación Social', titleEn: 'Social Chat', icon: '💬', desc: 'Small talk, hobbies, and weather' },
  { slug: 'emergency', title: 'Emergencias', titleEn: 'Emergencies', icon: '🚨', desc: 'Help, police, fire, and medical' },
  { slug: 'work', title: 'Trabajo', titleEn: 'Work', icon: '💼', desc: 'Office, meetings, and interviews' },
  { slug: 'romance', title: 'Romance', titleEn: 'Romance', icon: '❤️', desc: 'Compliments, dating, and feelings' },
];

const PHRASES_DATA = [

  // ============================================================
  // 1. GREETINGS — Saludos y Despedidas
  // ============================================================
  {
    id: 'greet-1',
    situation: 'greetings',
    spanish: '¡Hola! ¿Cómo estás?',
    english: 'Hello! How are you?',
    notes: 'Informal greeting, used with friends and family',
    formality: 'informal',
    reply: { spanish: 'Bien, gracias. ¿Y tú?', english: 'Good, thanks. And you?' },
  },
  {
    id: 'greet-2',
    situation: 'greetings',
    spanish: '¿Cómo está usted?',
    english: 'How are you? (formal)',
    notes: 'Use "usted" with elders, strangers, or in professional settings',
    formality: 'formal',
    reply: { spanish: 'Muy bien, gracias. ¿Y usted?', english: 'Very well, thank you. And you?' },
  },
  {
    id: 'greet-3',
    situation: 'greetings',
    spanish: 'Buenos días',
    english: 'Good morning',
    notes: 'Used until around noon; the most common daytime greeting',
    formality: 'neutral',
    reply: { spanish: 'Buenos días. ¿Cómo amaneciste?', english: 'Good morning. How did you wake up?' },
  },
  {
    id: 'greet-4',
    situation: 'greetings',
    spanish: 'Buenas tardes',
    english: 'Good afternoon',
    notes: 'Used roughly from noon until sunset',
    formality: 'neutral',
    reply: { spanish: 'Buenas tardes. ¿Qué tal?', english: 'Good afternoon. How\'s it going?' },
  },
  {
    id: 'greet-5',
    situation: 'greetings',
    spanish: 'Buenas noches',
    english: 'Good evening / Good night',
    notes: 'Used both as a greeting and a farewell after dark',
    formality: 'neutral',
    reply: { spanish: 'Buenas noches. ¡Que descanses!', english: 'Good night. Rest well!' },
  },
  {
    id: 'greet-6',
    situation: 'greetings',
    spanish: '¿Qué tal?',
    english: 'How\'s it going?',
    notes: 'Very common casual greeting across all Spanish-speaking countries',
    formality: 'informal',
    reply: { spanish: 'Todo bien, ¿y tú?', english: 'All good, and you?' },
  },
  {
    id: 'greet-7',
    situation: 'greetings',
    spanish: '¿Qué hay de nuevo?',
    english: 'What\'s new?',
    notes: 'Casual way to ask what someone has been up to',
    formality: 'informal',
    reply: { spanish: 'Nada en especial. ¿Y tú qué cuentas?', english: 'Nothing special. What about you?' },
  },
  {
    id: 'greet-8',
    situation: 'greetings',
    spanish: '¿Qué onda?',
    english: 'What\'s up?',
    notes: 'Very informal, popular in Mexico and Central America',
    formality: 'informal',
    reply: { spanish: 'Aquí andamos. ¿Qué onda contigo?', english: 'Just hanging around. What\'s up with you?' },
  },
  {
    id: 'greet-9',
    situation: 'greetings',
    spanish: '¡Tanto tiempo sin verte!',
    english: 'Long time no see!',
    notes: 'Warm expression when reuniting after a long time',
    formality: 'informal',
    reply: { spanish: '¡Sí! ¡Te he extrañado mucho!', english: 'Yes! I\'ve missed you a lot!' },
  },
  {
    id: 'greet-10',
    situation: 'greetings',
    spanish: '¡Adiós! ¡Cuídate!',
    english: 'Goodbye! Take care!',
    notes: 'Common farewell combination',
    formality: 'informal',
    reply: { spanish: '¡Tú también! ¡Nos vemos!', english: 'You too! See you!' },
  },
  {
    id: 'greet-11',
    situation: 'greetings',
    spanish: 'Hasta luego',
    english: 'See you later',
    notes: 'The most standard farewell, appropriate in any context',
    formality: 'neutral',
    reply: { spanish: 'Hasta luego. ¡Que te vaya bien!', english: 'See you later. Hope it goes well!' },
  },
  {
    id: 'greet-12',
    situation: 'greetings',
    spanish: 'Hasta mañana',
    english: 'See you tomorrow',
    notes: 'Used when you know you will see the person the next day',
    formality: 'neutral',
    reply: { spanish: 'Hasta mañana. ¡Descansa!', english: 'See you tomorrow. Rest up!' },
  },
  {
    id: 'greet-13',
    situation: 'greetings',
    spanish: 'Nos vemos pronto',
    english: 'See you soon',
    notes: 'Friendly and optimistic farewell',
    formality: 'informal',
    reply: { spanish: '¡Claro que sí! ¡Cuídate mucho!', english: 'Of course! Take good care!' },
  },
  {
    id: 'greet-14',
    situation: 'greetings',
    spanish: 'Fue un placer verle',
    english: 'It was a pleasure seeing you',
    notes: 'Formal farewell, often used in professional settings',
    formality: 'formal',
    reply: { spanish: 'El placer fue mío. Hasta pronto.', english: 'The pleasure was mine. See you soon.' },
  },
  {
    id: 'greet-15',
    situation: 'greetings',
    spanish: '¿Cómo te ha ido?',
    english: 'How have things been?',
    notes: 'Asking about someone\'s recent life, slightly deeper than "¿Qué tal?"',
    formality: 'informal',
    reply: { spanish: 'Me ha ido muy bien, gracias por preguntar.', english: 'Things have been great, thanks for asking.' },
  },
  {
    id: 'greet-16',
    situation: 'greetings',
    spanish: '¡Bienvenido! ¡Pasa, pasa!',
    english: 'Welcome! Come in, come in!',
    notes: 'Warm way to welcome someone into your home; repeating "pasa" adds warmth',
    formality: 'informal',
    reply: { spanish: '¡Gracias! ¡Qué bonita casa!', english: 'Thanks! What a beautiful house!' },
  },

  // ============================================================
  // 2. POLITENESS — Cortesía
  // ============================================================
  {
    id: 'polite-1',
    situation: 'politeness',
    spanish: 'Por favor',
    english: 'Please',
    notes: 'Essential word; can be placed at the beginning or end of a sentence',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'polite-2',
    situation: 'politeness',
    spanish: 'Muchas gracias',
    english: 'Thank you very much',
    notes: '"Muchas" intensifies the gratitude compared to a simple "gracias"',
    formality: 'neutral',
    reply: { spanish: 'De nada. Con mucho gusto.', english: 'You\'re welcome. With pleasure.' },
  },
  {
    id: 'polite-3',
    situation: 'politeness',
    spanish: 'Mil gracias',
    english: 'A thousand thanks',
    notes: 'Emphatic way to express deep gratitude',
    formality: 'informal',
    reply: { spanish: 'No hay de qué.', english: 'Don\'t mention it.' },
  },
  {
    id: 'polite-4',
    situation: 'politeness',
    spanish: 'Disculpe, ¿podría ayudarme?',
    english: 'Excuse me, could you help me?',
    notes: 'Polite way to approach a stranger for help',
    formality: 'formal',
    reply: { spanish: 'Claro, ¿en qué le puedo ayudar?', english: 'Of course, how can I help you?' },
  },
  {
    id: 'polite-5',
    situation: 'politeness',
    spanish: 'Lo siento mucho',
    english: 'I\'m very sorry',
    notes: 'Expresses genuine remorse or sympathy',
    formality: 'neutral',
    reply: { spanish: 'No te preocupes, está bien.', english: 'Don\'t worry, it\'s fine.' },
  },
  {
    id: 'polite-6',
    situation: 'politeness',
    spanish: 'Perdón, ¿me permite pasar?',
    english: 'Pardon me, may I pass?',
    notes: 'Used when navigating through a crowd or tight space',
    formality: 'formal',
    reply: { spanish: 'Sí, adelante.', english: 'Yes, go ahead.' },
  },
  {
    id: 'polite-7',
    situation: 'politeness',
    spanish: 'Con permiso',
    english: 'Excuse me / With your permission',
    notes: 'Used when passing by someone or entering a room',
    formality: 'neutral',
    reply: { spanish: 'Adelante, pase.', english: 'Go ahead, come in.' },
  },
  {
    id: 'polite-8',
    situation: 'politeness',
    spanish: 'No se preocupe',
    english: 'Don\'t worry about it',
    notes: 'Reassuring someone formally that all is well',
    formality: 'formal',
    reply: { spanish: 'Gracias, es usted muy amable.', english: 'Thank you, you are very kind.' },
  },
  {
    id: 'polite-9',
    situation: 'politeness',
    spanish: '¿Sería tan amable de repetir eso?',
    english: 'Would you be so kind as to repeat that?',
    notes: 'Very polite request, useful when learning Spanish',
    formality: 'formal',
    reply: { spanish: 'Por supuesto, con gusto.', english: 'Of course, with pleasure.' },
  },
  {
    id: 'polite-10',
    situation: 'politeness',
    spanish: '¡Que tenga un buen día!',
    english: 'Have a good day!',
    notes: 'Polite farewell often used in shops and offices',
    formality: 'formal',
    reply: { spanish: 'Igualmente, ¡gracias!', english: 'Likewise, thanks!' },
  },
  {
    id: 'polite-11',
    situation: 'politeness',
    spanish: 'Le agradezco mucho su ayuda',
    english: 'I really appreciate your help',
    notes: '"Agradecer" is more formal than "dar las gracias"',
    formality: 'formal',
    reply: { spanish: 'Ha sido un placer ayudarle.', english: 'It has been a pleasure to help you.' },
  },
  {
    id: 'polite-12',
    situation: 'politeness',
    spanish: '¡Salud!',
    english: 'Bless you! / Cheers!',
    notes: 'Said when someone sneezes or when making a toast',
    formality: 'neutral',
    reply: { spanish: '¡Gracias!', english: 'Thanks!' },
  },
  {
    id: 'polite-13',
    situation: 'politeness',
    spanish: '¡Buen provecho!',
    english: 'Enjoy your meal!',
    notes: 'Said to anyone who is eating, even strangers in a restaurant; very common culturally',
    formality: 'neutral',
    reply: { spanish: '¡Gracias! Igualmente.', english: 'Thanks! You too.' },
  },
  {
    id: 'polite-14',
    situation: 'politeness',
    spanish: 'Fue sin querer, lo siento',
    english: 'It was an accident, I\'m sorry',
    notes: '"Sin querer" literally means "without wanting to"',
    formality: 'neutral',
    reply: { spanish: 'No pasa nada, tranquilo.', english: 'It\'s nothing, relax.' },
  },
  {
    id: 'polite-15',
    situation: 'politeness',
    spanish: 'Muy amable de su parte',
    english: 'Very kind of you',
    notes: 'Formal expression of appreciation for a kindness',
    formality: 'formal',
    reply: { spanish: 'No es nada. Para eso estamos.', english: 'It\'s nothing. That\'s what we\'re here for.' },
  },
  {
    id: 'polite-16',
    situation: 'politeness',
    spanish: '¿Le importaría hablar más despacio?',
    english: 'Would you mind speaking more slowly?',
    notes: 'Essential phrase for language learners; very polite phrasing',
    formality: 'formal',
    reply: { spanish: 'Claro que no. Le repito...', english: 'Not at all. Let me repeat...' },
  },

  // ============================================================
  // 3. INTRODUCTIONS — Presentaciones
  // ============================================================
  {
    id: 'intro-1',
    situation: 'introductions',
    spanish: 'Me llamo María. ¿Y tú?',
    english: 'My name is María. And you?',
    notes: '"Me llamo" literally means "I call myself"',
    formality: 'informal',
    reply: { spanish: 'Mucho gusto, María. Yo soy Carlos.', english: 'Nice to meet you, María. I\'m Carlos.' },
  },
  {
    id: 'intro-2',
    situation: 'introductions',
    spanish: 'Mucho gusto en conocerle',
    english: 'Pleased to meet you',
    notes: 'Formal introduction; "conocerle" uses the usted form',
    formality: 'formal',
    reply: { spanish: 'El gusto es mío.', english: 'The pleasure is mine.' },
  },
  {
    id: 'intro-3',
    situation: 'introductions',
    spanish: '¿De dónde eres?',
    english: 'Where are you from?',
    notes: 'One of the most common questions when meeting someone new',
    formality: 'informal',
    reply: { spanish: 'Soy de Estados Unidos. ¿Y tú?', english: 'I\'m from the United States. And you?' },
  },
  {
    id: 'intro-4',
    situation: 'introductions',
    spanish: '¿A qué te dedicas?',
    english: 'What do you do for a living?',
    notes: 'More natural in Spanish than the literal "¿Cuál es tu trabajo?"',
    formality: 'informal',
    reply: { spanish: 'Soy profesor. ¿Y tú?', english: 'I\'m a teacher. And you?' },
  },
  {
    id: 'intro-5',
    situation: 'introductions',
    spanish: 'Te presento a mi amigo Juan',
    english: 'Let me introduce you to my friend Juan',
    notes: 'Informal third-party introduction',
    formality: 'informal',
    reply: { spanish: '¡Hola, Juan! Encantado de conocerte.', english: 'Hi, Juan! Delighted to meet you.' },
  },
  {
    id: 'intro-6',
    situation: 'introductions',
    spanish: 'Le presento al señor García',
    english: 'Allow me to introduce Mr. García',
    notes: 'Formal third-party introduction using "usted" form',
    formality: 'formal',
    reply: { spanish: 'Encantado, señor García. ¿Cómo está?', english: 'Delighted, Mr. García. How are you?' },
  },
  {
    id: 'intro-7',
    situation: 'introductions',
    spanish: '¿Cuántos años tienes?',
    english: 'How old are you?',
    notes: 'Literally "How many years do you have?" — Spanish uses "tener" (to have) for age',
    formality: 'informal',
    reply: { spanish: 'Tengo treinta años. ¿Y tú?', english: 'I\'m thirty. And you?' },
  },
  {
    id: 'intro-8',
    situation: 'introductions',
    spanish: '¿Hablas español?',
    english: 'Do you speak Spanish?',
    notes: 'A question you will hear often as a learner',
    formality: 'informal',
    reply: { spanish: 'Un poco. Estoy aprendiendo.', english: 'A little. I\'m learning.' },
  },
  {
    id: 'intro-9',
    situation: 'introductions',
    spanish: 'Hablo un poco de español',
    english: 'I speak a little Spanish',
    notes: 'Humble and endearing way to set expectations',
    formality: 'neutral',
    reply: { spanish: '¡Qué bien! Tu español es muy bueno.', english: 'How nice! Your Spanish is very good.' },
  },
  {
    id: 'intro-10',
    situation: 'introductions',
    spanish: '¿Cuánto tiempo llevas aquí?',
    english: 'How long have you been here?',
    notes: '"Llevar + time" is the Spanish way to express duration',
    formality: 'informal',
    reply: { spanish: 'Llevo dos semanas. Me encanta este lugar.', english: 'I\'ve been here two weeks. I love this place.' },
  },
  {
    id: 'intro-11',
    situation: 'introductions',
    spanish: 'Estoy aquí de vacaciones',
    english: 'I\'m here on vacation',
    notes: 'Common explanation for tourists',
    formality: 'neutral',
    reply: { spanish: '¡Genial! ¿Qué lugares has visitado?', english: 'Great! What places have you visited?' },
  },
  {
    id: 'intro-12',
    situation: 'introductions',
    spanish: '¿Estás casado o soltero?',
    english: 'Are you married or single?',
    notes: 'In Latin culture this is a common early question and is not considered rude',
    formality: 'informal',
    reply: { spanish: 'Soy soltero. ¿Y tú?', english: 'I\'m single. And you?' },
  },
  {
    id: 'intro-13',
    situation: 'introductions',
    spanish: '¿Tienes hermanos?',
    english: 'Do you have siblings?',
    notes: '"Hermanos" covers both brothers and sisters',
    formality: 'informal',
    reply: { spanish: 'Sí, tengo dos hermanas y un hermano.', english: 'Yes, I have two sisters and one brother.' },
  },
  {
    id: 'intro-14',
    situation: 'introductions',
    spanish: '¿Dónde vives?',
    english: 'Where do you live?',
    notes: 'Standard question for getting to know someone',
    formality: 'informal',
    reply: { spanish: 'Vivo en Madrid, en el centro.', english: 'I live in Madrid, in the center.' },
  },
  {
    id: 'intro-15',
    situation: 'introductions',
    spanish: 'Soy estudiante de intercambio',
    english: 'I\'m an exchange student',
    notes: 'Useful introduction for students abroad',
    formality: 'neutral',
    reply: { spanish: '¡Qué interesante! ¿Qué estudias?', english: 'How interesting! What do you study?' },
  },
  {
    id: 'intro-16',
    situation: 'introductions',
    spanish: 'Encantada de conocerte',
    english: 'Delighted to meet you (said by a woman)',
    notes: 'Women say "encantada", men say "encantado" — the adjective agrees with the speaker',
    formality: 'neutral',
    reply: { spanish: 'Igualmente. ¿De dónde eres?', english: 'Likewise. Where are you from?' },
  },

  // ============================================================
  // 4. DIRECTIONS — Direcciones
  // ============================================================
  {
    id: 'dir-1',
    situation: 'directions',
    spanish: 'Disculpe, ¿dónde está la estación de metro?',
    english: 'Excuse me, where is the metro station?',
    notes: 'Polite way to ask for directions from a stranger',
    formality: 'formal',
    reply: { spanish: 'Está a dos cuadras a la derecha.', english: 'It\'s two blocks to the right.' },
  },
  {
    id: 'dir-2',
    situation: 'directions',
    spanish: '¿Cómo llego al centro de la ciudad?',
    english: 'How do I get to the city center?',
    notes: '"Llegar" is the key verb for reaching a destination',
    formality: 'neutral',
    reply: { spanish: 'Siga derecho y luego gire a la izquierda.', english: 'Go straight and then turn left.' },
  },
  {
    id: 'dir-3',
    situation: 'directions',
    spanish: 'Gire a la derecha en el semáforo',
    english: 'Turn right at the traffic light',
    notes: '"Semáforo" is traffic light; essential navigation vocabulary',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'dir-4',
    situation: 'directions',
    spanish: 'Siga todo derecho hasta la plaza',
    english: 'Go straight ahead until the square',
    notes: '"Todo derecho" means straight ahead; don\'t confuse "derecho" (straight) with "derecha" (right)',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'dir-5',
    situation: 'directions',
    spanish: '¿Está lejos de aquí?',
    english: 'Is it far from here?',
    notes: 'Important follow-up question after getting directions',
    formality: 'neutral',
    reply: { spanish: 'No, está a unos diez minutos caminando.', english: 'No, it\'s about ten minutes walking.' },
  },
  {
    id: 'dir-6',
    situation: 'directions',
    spanish: '¿Puede mostrarme en el mapa?',
    english: 'Can you show me on the map?',
    notes: 'Useful when verbal directions are hard to follow',
    formality: 'formal',
    reply: { spanish: 'Claro, mire, estamos aquí...', english: 'Sure, look, we are here...' },
  },
  {
    id: 'dir-7',
    situation: 'directions',
    spanish: 'Está al lado de la farmacia',
    english: 'It\'s next to the pharmacy',
    notes: '"Al lado de" is one of the most useful location phrases',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'dir-8',
    situation: 'directions',
    spanish: 'Está enfrente del banco',
    english: 'It\'s across from the bank',
    notes: '"Enfrente de" means opposite or across from',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'dir-9',
    situation: 'directions',
    spanish: 'Creo que estoy perdido. ¿Me puede ayudar?',
    english: 'I think I\'m lost. Can you help me?',
    notes: 'Use "perdido" (masc.) or "perdida" (fem.) depending on speaker',
    formality: 'formal',
    reply: { spanish: 'Sí, ¿adónde quiere ir?', english: 'Yes, where do you want to go?' },
  },
  {
    id: 'dir-10',
    situation: 'directions',
    spanish: '¿Hay un cajero automático cerca?',
    english: 'Is there an ATM nearby?',
    notes: '"Cajero automático" is ATM; in some countries just "cajero"',
    formality: 'neutral',
    reply: { spanish: 'Sí, hay uno en la esquina.', english: 'Yes, there\'s one on the corner.' },
  },
  {
    id: 'dir-11',
    situation: 'directions',
    spanish: '¿Dónde está el baño, por favor?',
    english: 'Where is the bathroom, please?',
    notes: 'One of the most essential travel phrases; "baño" or "servicio" depending on the country',
    formality: 'neutral',
    reply: { spanish: 'Al fondo a la derecha.', english: 'At the back on the right.' },
  },
  {
    id: 'dir-12',
    situation: 'directions',
    spanish: 'Está entre la panadería y la librería',
    english: 'It\'s between the bakery and the bookstore',
    notes: '"Entre" is used for between two landmarks',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'dir-13',
    situation: 'directions',
    spanish: 'Cruce el puente y luego doble a la izquierda',
    english: 'Cross the bridge and then turn left',
    notes: '"Cruzar" means to cross; "doblar" is another word for turn',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'dir-14',
    situation: 'directions',
    spanish: '¿Es mejor ir en autobús o caminando?',
    english: 'Is it better to go by bus or on foot?',
    notes: 'Practical question for gauging distance',
    formality: 'neutral',
    reply: { spanish: 'Mejor en autobús, está bastante lejos.', english: 'Better by bus, it\'s quite far.' },
  },
  {
    id: 'dir-15',
    situation: 'directions',
    spanish: '¿Cuál es la dirección exacta?',
    english: 'What is the exact address?',
    notes: '"Dirección" means both direction and address in Spanish',
    formality: 'neutral',
    reply: { spanish: 'Es Calle Mayor, número quince.', english: 'It\'s Calle Mayor, number fifteen.' },
  },
  {
    id: 'dir-16',
    situation: 'directions',
    spanish: 'Busco la calle Cervantes',
    english: 'I\'m looking for Cervantes Street',
    notes: '"Buscar" means to look for; no preposition needed in Spanish',
    formality: 'neutral',
    reply: { spanish: 'Es la segunda calle a la izquierda.', english: 'It\'s the second street on the left.' },
  },

  // ============================================================
  // 5. FOOD — Comida y Restaurante
  // ============================================================
  {
    id: 'food-1',
    situation: 'food',
    spanish: '¿Tienen mesa para dos personas?',
    english: 'Do you have a table for two?',
    notes: 'Standard way to request seating at a restaurant',
    formality: 'neutral',
    reply: { spanish: 'Sí, síganme por favor.', english: 'Yes, follow me please.' },
  },
  {
    id: 'food-2',
    situation: 'food',
    spanish: '¿Me puede traer la carta, por favor?',
    english: 'Can you bring me the menu, please?',
    notes: '"La carta" is the menu; "el menú" often refers to a set meal deal',
    formality: 'formal',
    reply: { spanish: 'Aquí tiene. ¿Desean algo de beber?', english: 'Here you go. Would you like something to drink?' },
  },
  {
    id: 'food-3',
    situation: 'food',
    spanish: '¿Cuál es el plato del día?',
    english: 'What is the dish of the day?',
    notes: 'Many restaurants in Spain and Latin America offer a daily special at a good price',
    formality: 'neutral',
    reply: { spanish: 'Hoy tenemos paella de mariscos.', english: 'Today we have seafood paella.' },
  },
  {
    id: 'food-4',
    situation: 'food',
    spanish: '¿Qué me recomienda?',
    english: 'What do you recommend?',
    notes: 'Great way to try local specialties',
    formality: 'formal',
    reply: { spanish: 'Le recomiendo las enchiladas. Están deliciosas.', english: 'I recommend the enchiladas. They\'re delicious.' },
  },
  {
    id: 'food-5',
    situation: 'food',
    spanish: 'Soy alérgico a los mariscos',
    english: 'I\'m allergic to shellfish',
    notes: 'Critical safety phrase; use "alérgico" (masc.) or "alérgica" (fem.)',
    formality: 'neutral',
    reply: { spanish: 'Entendido. Le sugiero el pollo a la plancha.', english: 'Understood. I suggest the grilled chicken.' },
  },
  {
    id: 'food-6',
    situation: 'food',
    spanish: '¿Este plato es picante?',
    english: 'Is this dish spicy?',
    notes: 'Important question especially in Mexico and Central America',
    formality: 'neutral',
    reply: { spanish: 'Un poco, pero le podemos quitar el chile.', english: 'A little, but we can remove the chili.' },
  },
  {
    id: 'food-7',
    situation: 'food',
    spanish: 'Para mí, una cerveza, por favor',
    english: 'For me, a beer, please',
    notes: '"Para mí" is the standard way to order for yourself',
    formality: 'neutral',
    reply: { spanish: '¿Grande o pequeña?', english: 'Large or small?' },
  },
  {
    id: 'food-8',
    situation: 'food',
    spanish: 'La cuenta, por favor',
    english: 'The check, please',
    notes: 'In many Spanish-speaking countries, you must ask for the check; it won\'t come automatically',
    formality: 'neutral',
    reply: { spanish: 'Enseguida se la traigo.', english: 'I\'ll bring it right away.' },
  },
  {
    id: 'food-9',
    situation: 'food',
    spanish: '¿Aceptan tarjeta de crédito?',
    english: 'Do you accept credit cards?',
    notes: 'Many smaller restaurants are cash-only, so always ask',
    formality: 'neutral',
    reply: { spanish: 'Sí, aceptamos Visa y Mastercard.', english: 'Yes, we accept Visa and Mastercard.' },
  },
  {
    id: 'food-10',
    situation: 'food',
    spanish: '¡Está delicioso! ¿Cuál es la receta?',
    english: 'It\'s delicious! What\'s the recipe?',
    notes: 'A great compliment to the chef or host',
    formality: 'informal',
    reply: { spanish: '¡Gracias! Es una receta de mi abuela.', english: 'Thanks! It\'s my grandmother\'s recipe.' },
  },
  {
    id: 'food-11',
    situation: 'food',
    spanish: 'Quisiera un café con leche, por favor',
    english: 'I\'d like a coffee with milk, please',
    notes: '"Quisiera" is the polite conditional form of "querer" (to want)',
    formality: 'formal',
    reply: { spanish: '¿Con azúcar?', english: 'With sugar?' },
  },
  {
    id: 'food-12',
    situation: 'food',
    spanish: '¿Tienen opciones vegetarianas?',
    english: 'Do you have vegetarian options?',
    notes: 'Increasingly common question in Spanish-speaking countries',
    formality: 'neutral',
    reply: { spanish: 'Sí, tenemos ensaladas y una pasta de verduras.', english: 'Yes, we have salads and a vegetable pasta.' },
  },
  {
    id: 'food-13',
    situation: 'food',
    spanish: '¿Está incluida la propina?',
    english: 'Is the tip included?',
    notes: 'Tipping customs vary: in Spain, small tips are common; in Mexico, 10-15% is standard',
    formality: 'neutral',
    reply: { spanish: 'No, la propina no está incluida.', english: 'No, the tip is not included.' },
  },
  {
    id: 'food-14',
    situation: 'food',
    spanish: 'Me falta un tenedor, ¿me trae uno?',
    english: 'I\'m missing a fork, can you bring me one?',
    notes: 'Useful for requesting utensils: cuchillo (knife), cuchara (spoon), tenedor (fork)',
    formality: 'neutral',
    reply: { spanish: 'Disculpe, ahora mismo se lo traigo.', english: 'Sorry about that, I\'ll bring it right away.' },
  },
  {
    id: 'food-15',
    situation: 'food',
    spanish: '¿Puedo ver la carta de postres?',
    english: 'Can I see the dessert menu?',
    notes: '"Postre" is dessert; flan and churros are popular choices',
    formality: 'neutral',
    reply: { spanish: 'Claro, aquí tiene. Le recomiendo el flan.', english: 'Of course, here you go. I recommend the flan.' },
  },
  {
    id: 'food-16',
    situation: 'food',
    spanish: 'Yo invito. Esta cena va por mi cuenta.',
    english: 'My treat. This dinner is on me.',
    notes: '"Invitar" in this context means to pay for someone; a generous gesture',
    formality: 'informal',
    reply: { spanish: '¡Qué amable! La próxima vez invito yo.', english: 'How kind! Next time it\'s on me.' },
  },

  // ============================================================
  // 6. SHOPPING — De Compras
  // ============================================================
  {
    id: 'shop-1',
    situation: 'shopping',
    spanish: '¿Cuánto cuesta esto?',
    english: 'How much does this cost?',
    notes: 'The most essential shopping phrase',
    formality: 'neutral',
    reply: { spanish: 'Cuesta veinte euros.', english: 'It costs twenty euros.' },
  },
  {
    id: 'shop-2',
    situation: 'shopping',
    spanish: '¿Tienen esto en otra talla?',
    english: 'Do you have this in another size?',
    notes: '"Talla" is for clothing sizes; "número" for shoe sizes',
    formality: 'neutral',
    reply: { spanish: 'Voy a revisar. ¿Qué talla necesita?', english: 'Let me check. What size do you need?' },
  },
  {
    id: 'shop-3',
    situation: 'shopping',
    spanish: '¿Puedo probármelo?',
    english: 'Can I try it on?',
    notes: '"Probarse" is reflexive; the fitting room is "el probador"',
    formality: 'neutral',
    reply: { spanish: 'Sí, los probadores están al fondo.', english: 'Yes, the fitting rooms are in the back.' },
  },
  {
    id: 'shop-4',
    situation: 'shopping',
    spanish: '¿Tienen esto en color azul?',
    english: 'Do you have this in blue?',
    notes: 'Common colors: rojo (red), verde (green), negro (black), blanco (white)',
    formality: 'neutral',
    reply: { spanish: 'Solo nos queda en negro y gris.', english: 'We only have it left in black and gray.' },
  },
  {
    id: 'shop-5',
    situation: 'shopping',
    spanish: 'Me queda un poco grande. ¿Tiene una talla menos?',
    english: 'It\'s a bit big on me. Do you have one size smaller?',
    notes: '"Quedar" describes how something fits: grande (big), pequeño (small), bien (well)',
    formality: 'neutral',
    reply: { spanish: 'Sí, aquí tiene la talla mediana.', english: 'Yes, here\'s the medium size.' },
  },
  {
    id: 'shop-6',
    situation: 'shopping',
    spanish: '¿Hay descuento si pago en efectivo?',
    english: 'Is there a discount if I pay in cash?',
    notes: 'In many Latin American markets, cash payment can get you a better price',
    formality: 'neutral',
    reply: { spanish: 'Sí, le puedo hacer un diez por ciento.', english: 'Yes, I can give you ten percent off.' },
  },
  {
    id: 'shop-7',
    situation: 'shopping',
    spanish: '¿Cuál es el precio final?',
    english: 'What is the final price?',
    notes: 'Useful when negotiating or after discounts are applied',
    formality: 'neutral',
    reply: { spanish: 'Con el descuento, son cuarenta y cinco pesos.', english: 'With the discount, it\'s forty-five pesos.' },
  },
  {
    id: 'shop-8',
    situation: 'shopping',
    spanish: 'Solo estoy mirando, gracias',
    english: 'I\'m just looking, thanks',
    notes: 'Polite way to let a salesperson know you don\'t need help yet',
    formality: 'neutral',
    reply: { spanish: 'Muy bien, avíseme si necesita algo.', english: 'Very well, let me know if you need anything.' },
  },
  {
    id: 'shop-9',
    situation: 'shopping',
    spanish: '¿Tiene garantía este producto?',
    english: 'Does this product have a warranty?',
    notes: '"Garantía" is important for electronics and appliances',
    formality: 'neutral',
    reply: { spanish: 'Sí, tiene un año de garantía.', english: 'Yes, it has a one-year warranty.' },
  },
  {
    id: 'shop-10',
    situation: 'shopping',
    spanish: '¿Puedo devolver esto si no me queda bien?',
    english: 'Can I return this if it doesn\'t fit?',
    notes: '"Devolver" means to return an item; policies vary by country',
    formality: 'neutral',
    reply: { spanish: 'Sí, tiene quince días para devoluciones.', english: 'Yes, you have fifteen days for returns.' },
  },
  {
    id: 'shop-11',
    situation: 'shopping',
    spanish: 'Me lo llevo',
    english: 'I\'ll take it',
    notes: 'The phrase that seals the deal when you decide to buy',
    formality: 'neutral',
    reply: { spanish: '¡Perfecto! ¿Paga en efectivo o con tarjeta?', english: 'Perfect! Cash or card?' },
  },
  {
    id: 'shop-12',
    situation: 'shopping',
    spanish: 'Es demasiado caro. ¿No tiene algo más barato?',
    english: 'It\'s too expensive. Don\'t you have something cheaper?',
    notes: 'Direct but acceptable, especially in markets',
    formality: 'informal',
    reply: { spanish: 'Tengo estos que están en oferta.', english: 'I have these that are on sale.' },
  },
  {
    id: 'shop-13',
    situation: 'shopping',
    spanish: '¿A qué hora cierran?',
    english: 'What time do you close?',
    notes: 'In Spain, many shops close for siesta from 2-5 PM',
    formality: 'neutral',
    reply: { spanish: 'Cerramos a las nueve de la noche.', english: 'We close at nine in the evening.' },
  },
  {
    id: 'shop-14',
    situation: 'shopping',
    spanish: '¿Me puede envolver esto para regalo?',
    english: 'Can you gift-wrap this for me?',
    notes: 'Many shops offer free gift wrapping, especially during holidays',
    formality: 'formal',
    reply: { spanish: 'Con mucho gusto. ¿De qué color el papel?', english: 'With pleasure. What color paper?' },
  },
  {
    id: 'shop-15',
    situation: 'shopping',
    spanish: 'Necesito una bolsa, por favor',
    english: 'I need a bag, please',
    notes: 'In many countries, plastic bags now cost extra or are not available',
    formality: 'neutral',
    reply: { spanish: 'Las bolsas cuestan diez centavos.', english: 'Bags cost ten cents.' },
  },

  // ============================================================
  // 7. TRANSPORT — Transporte
  // ============================================================
  {
    id: 'trans-1',
    situation: 'transport',
    spanish: '¿Dónde está la parada de autobús?',
    english: 'Where is the bus stop?',
    notes: '"Parada" is the stop; "estación" is a larger station',
    formality: 'neutral',
    reply: { spanish: 'Está en la siguiente esquina.', english: 'It\'s on the next corner.' },
  },
  {
    id: 'trans-2',
    situation: 'transport',
    spanish: '¿Cuánto cuesta un boleto sencillo?',
    english: 'How much is a single ticket?',
    notes: '"Boleto" in Latin America, "billete" in Spain',
    formality: 'neutral',
    reply: { spanish: 'Son dos euros con cincuenta.', english: 'It\'s two euros fifty.' },
  },
  {
    id: 'trans-3',
    situation: 'transport',
    spanish: '¿Este autobús va al aeropuerto?',
    english: 'Does this bus go to the airport?',
    notes: 'Always confirm the route before boarding',
    formality: 'neutral',
    reply: { spanish: 'No, tiene que tomar el número cuarenta y dos.', english: 'No, you need to take number forty-two.' },
  },
  {
    id: 'trans-4',
    situation: 'transport',
    spanish: '¿Me puede llevar a esta dirección, por favor?',
    english: 'Can you take me to this address, please?',
    notes: 'Essential taxi phrase; showing the address on your phone helps',
    formality: 'formal',
    reply: { spanish: 'Sí, súbase. Llegaremos en quince minutos.', english: 'Yes, get in. We\'ll arrive in fifteen minutes.' },
  },
  {
    id: 'trans-5',
    situation: 'transport',
    spanish: '¿A qué hora sale el próximo tren?',
    english: 'What time does the next train leave?',
    notes: '"Salir" for departures; "llegar" for arrivals',
    formality: 'neutral',
    reply: { spanish: 'El próximo tren sale a las tres y media.', english: 'The next train leaves at three thirty.' },
  },
  {
    id: 'trans-6',
    situation: 'transport',
    spanish: '¿Dónde puedo comprar un abono de transporte?',
    english: 'Where can I buy a transit pass?',
    notes: '"Abono" is a multi-ride or monthly pass; much cheaper than individual tickets',
    formality: 'neutral',
    reply: { spanish: 'En la taquilla de la estación o en la máquina.', english: 'At the station ticket office or at the machine.' },
  },
  {
    id: 'trans-7',
    situation: 'transport',
    spanish: '¿Me avisa cuando lleguemos, por favor?',
    english: 'Can you let me know when we arrive, please?',
    notes: 'Useful request for bus drivers or taxi drivers',
    formality: 'formal',
    reply: { spanish: 'Claro, yo le aviso.', english: 'Sure, I\'ll let you know.' },
  },
  {
    id: 'trans-8',
    situation: 'transport',
    spanish: 'Necesito ir a la terminal de autobuses',
    english: 'I need to go to the bus terminal',
    notes: '"Terminal" is used for major intercity bus stations',
    formality: 'neutral',
    reply: { spanish: 'Puede tomar un taxi aquí enfrente.', english: 'You can take a taxi right across from here.' },
  },
  {
    id: 'trans-9',
    situation: 'transport',
    spanish: '¿Tiene taxímetro?',
    english: 'Do you have a meter?',
    notes: 'Always ask; in some cities, unmetered taxis may overcharge tourists',
    formality: 'neutral',
    reply: { spanish: 'Sí, el taxímetro ya está corriendo.', english: 'Yes, the meter is already running.' },
  },
  {
    id: 'trans-10',
    situation: 'transport',
    spanish: 'Pare aquí, por favor',
    english: 'Stop here, please',
    notes: '"Pare" is the formal imperative of "parar"; essential for taxis',
    formality: 'formal',
    reply: { spanish: 'Aquí es. Son doce euros.', english: 'Here we are. That\'s twelve euros.' },
  },
  {
    id: 'trans-11',
    situation: 'transport',
    spanish: '¿Hay conexión de wifi en el tren?',
    english: 'Is there wifi on the train?',
    notes: 'Modern trains often have wifi, especially high-speed ones like AVE in Spain',
    formality: 'neutral',
    reply: { spanish: 'Sí, la contraseña está en su asiento.', english: 'Yes, the password is on your seat.' },
  },
  {
    id: 'trans-12',
    situation: 'transport',
    spanish: '¿Dónde está la puerta de embarque?',
    english: 'Where is the boarding gate?',
    notes: 'Airport vocabulary: "embarque" (boarding), "facturación" (check-in)',
    formality: 'neutral',
    reply: { spanish: 'La puerta B12, al final del pasillo.', english: 'Gate B12, at the end of the hallway.' },
  },
  {
    id: 'trans-13',
    situation: 'transport',
    spanish: 'Mi vuelo tiene retraso. ¿Cuánto tiempo más?',
    english: 'My flight is delayed. How much longer?',
    notes: '"Retraso" means delay; very useful airport vocabulary',
    formality: 'neutral',
    reply: { spanish: 'Aproximadamente una hora más.', english: 'Approximately one more hour.' },
  },
  {
    id: 'trans-14',
    situation: 'transport',
    spanish: '¿Dónde puedo alquilar un coche?',
    english: 'Where can I rent a car?',
    notes: '"Alquilar" is to rent; "coche" in Spain, "carro" in Latin America',
    formality: 'neutral',
    reply: { spanish: 'Hay varias agencias en la planta baja.', english: 'There are several agencies on the ground floor.' },
  },
  {
    id: 'trans-15',
    situation: 'transport',
    spanish: '¿Es necesario hacer trasbordo?',
    english: 'Do I need to transfer?',
    notes: '"Trasbordo" or "transbordo" means a transfer between lines or vehicles',
    formality: 'neutral',
    reply: { spanish: 'Sí, tiene que cambiar en Sol.', english: 'Yes, you have to change at Sol.' },
  },
  {
    id: 'trans-16',
    situation: 'transport',
    spanish: '¿Cuánto se tarda en llegar al centro?',
    english: 'How long does it take to get to the center?',
    notes: '"Tardar" is the verb for how long something takes',
    formality: 'neutral',
    reply: { spanish: 'Unos cuarenta minutos con tráfico.', english: 'About forty minutes with traffic.' },
  },

  // ============================================================
  // 8. HEALTH — Salud
  // ============================================================
  {
    id: 'health-1',
    situation: 'health',
    spanish: 'No me siento bien. Necesito ver a un médico.',
    english: 'I don\'t feel well. I need to see a doctor.',
    notes: '"Médico" is the standard term; "doctor" is also widely used',
    formality: 'neutral',
    reply: { spanish: 'Hay un hospital a cinco minutos de aquí.', english: 'There\'s a hospital five minutes from here.' },
  },
  {
    id: 'health-2',
    situation: 'health',
    spanish: 'Me duele mucho la cabeza',
    english: 'I have a bad headache',
    notes: '"Doler" works like "gustar": the body part is the subject. Me duele la cabeza (singular), me duelen los pies (plural)',
    formality: 'neutral',
    reply: { spanish: '¿Quiere que le traiga un analgésico?', english: 'Would you like me to bring you a painkiller?' },
  },
  {
    id: 'health-3',
    situation: 'health',
    spanish: 'Tengo fiebre y escalofríos',
    english: 'I have a fever and chills',
    notes: '"Fiebre" is fever; "escalofríos" are chills',
    formality: 'neutral',
    reply: { spanish: '¿Desde cuándo tiene estos síntomas?', english: 'How long have you had these symptoms?' },
  },
  {
    id: 'health-4',
    situation: 'health',
    spanish: 'Soy alérgico a la penicilina',
    english: 'I\'m allergic to penicillin',
    notes: 'Critical medical information to communicate clearly',
    formality: 'neutral',
    reply: { spanish: 'Lo anotaré en su expediente.', english: 'I\'ll note it in your file.' },
  },
  {
    id: 'health-5',
    situation: 'health',
    spanish: '¿Dónde está la farmacia más cercana?',
    english: 'Where is the nearest pharmacy?',
    notes: 'In Spain and Latin America, pharmacists can recommend medications for minor ailments',
    formality: 'neutral',
    reply: { spanish: 'Hay una en la esquina, con la cruz verde.', english: 'There\'s one on the corner, with the green cross.' },
  },
  {
    id: 'health-6',
    situation: 'health',
    spanish: 'Necesito algo para el dolor de estómago',
    english: 'I need something for a stomachache',
    notes: '"Dolor de estómago" or "dolor de barriga" for stomachache',
    formality: 'neutral',
    reply: { spanish: 'Le recomiendo este antiácido.', english: 'I recommend this antacid.' },
  },
  {
    id: 'health-7',
    situation: 'health',
    spanish: '¿Necesito receta para comprar este medicamento?',
    english: 'Do I need a prescription to buy this medication?',
    notes: '"Receta" is prescription; many drugs available OTC in Latin America require prescriptions elsewhere',
    formality: 'neutral',
    reply: { spanish: 'No, este se vende sin receta.', english: 'No, this one is sold without a prescription.' },
  },
  {
    id: 'health-8',
    situation: 'health',
    spanish: 'Me torcí el tobillo',
    english: 'I twisted my ankle',
    notes: '"Torcer" is to twist or sprain; common travel injury',
    formality: 'neutral',
    reply: { spanish: 'Debería poner hielo y descansar.', english: 'You should put ice on it and rest.' },
  },
  {
    id: 'health-9',
    situation: 'health',
    spanish: 'Tengo tos y me duele la garganta',
    english: 'I have a cough and my throat hurts',
    notes: '"Tos" is cough; "garganta" is throat',
    formality: 'neutral',
    reply: { spanish: 'Tome estas pastillas tres veces al día.', english: 'Take these pills three times a day.' },
  },
  {
    id: 'health-10',
    situation: 'health',
    spanish: '¿Cada cuántas horas debo tomar la medicina?',
    english: 'How often should I take the medicine?',
    notes: 'Essential question at the pharmacy or doctor\'s office',
    formality: 'neutral',
    reply: { spanish: 'Una pastilla cada ocho horas, con comida.', english: 'One pill every eight hours, with food.' },
  },
  {
    id: 'health-11',
    situation: 'health',
    spanish: 'Creo que tengo una infección',
    english: 'I think I have an infection',
    notes: '"Infección" is pronounced with stress on the last syllable',
    formality: 'neutral',
    reply: { spanish: 'Vamos a hacerle unos análisis.', english: 'We\'re going to run some tests.' },
  },
  {
    id: 'health-12',
    situation: 'health',
    spanish: '¿Tiene seguro médico?',
    english: 'Do you have health insurance?',
    notes: '"Seguro médico" is health insurance; always carry your card when traveling',
    formality: 'formal',
    reply: { spanish: 'Sí, aquí tiene mi tarjeta de seguro.', english: 'Yes, here\'s my insurance card.' },
  },
  {
    id: 'health-13',
    situation: 'health',
    spanish: 'Me corté el dedo y no deja de sangrar',
    english: 'I cut my finger and it won\'t stop bleeding',
    notes: '"Sangrar" is to bleed; "cortar" is to cut',
    formality: 'neutral',
    reply: { spanish: 'Vamos a limpiar la herida y ponerle una venda.', english: 'Let\'s clean the wound and put a bandage on it.' },
  },
  {
    id: 'health-14',
    situation: 'health',
    spanish: 'Estoy embarazada de tres meses',
    english: 'I\'m three months pregnant',
    notes: 'Be careful: "embarazada" means pregnant, NOT embarrassed (a famous false friend)',
    formality: 'neutral',
    reply: { spanish: '¡Felicidades! ¿Es su primer bebé?', english: 'Congratulations! Is it your first baby?' },
  },
  {
    id: 'health-15',
    situation: 'health',
    spanish: 'Necesito renovar mi receta',
    english: 'I need to renew my prescription',
    notes: '"Renovar" means to renew or refill',
    formality: 'neutral',
    reply: { spanish: '¿Tiene la receta anterior?', english: 'Do you have the previous prescription?' },
  },
  {
    id: 'health-16',
    situation: 'health',
    spanish: 'Me siento mareado y con náuseas',
    english: 'I feel dizzy and nauseous',
    notes: '"Mareado" can mean dizzy or motion-sick',
    formality: 'neutral',
    reply: { spanish: 'Siéntese aquí y tome agua. ¿Comió algo hoy?', english: 'Sit here and drink water. Did you eat anything today?' },
  },

  // ============================================================
  // 9. TIME — Hora y Fecha
  // ============================================================
  {
    id: 'time-1',
    situation: 'time',
    spanish: '¿Qué hora es?',
    english: 'What time is it?',
    notes: 'The most basic time question; Spanish uses "ser" for telling time',
    formality: 'neutral',
    reply: { spanish: 'Son las tres y cuarto.', english: 'It\'s quarter past three.' },
  },
  {
    id: 'time-2',
    situation: 'time',
    spanish: 'Es la una y media',
    english: 'It\'s one thirty',
    notes: 'Only 1:00 uses "Es la una" (singular); all others use "Son las..."',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'time-3',
    situation: 'time',
    spanish: '¿A qué hora empieza la reunión?',
    english: 'What time does the meeting start?',
    notes: '"Empezar" or "comenzar" both mean to start',
    formality: 'neutral',
    reply: { spanish: 'A las diez en punto.', english: 'At ten o\'clock sharp.' },
  },
  {
    id: 'time-4',
    situation: 'time',
    spanish: 'Llego en quince minutos',
    english: 'I\'ll be there in fifteen minutes',
    notes: 'In many Latin cultures, time is more flexible than in the US or northern Europe',
    formality: 'neutral',
    reply: { spanish: 'Está bien, aquí te espero.', english: 'Okay, I\'ll wait for you here.' },
  },
  {
    id: 'time-5',
    situation: 'time',
    spanish: '¿Qué día es hoy?',
    english: 'What day is today?',
    notes: 'Days in Spanish are not capitalized: lunes, martes, miércoles...',
    formality: 'neutral',
    reply: { spanish: 'Hoy es miércoles.', english: 'Today is Wednesday.' },
  },
  {
    id: 'time-6',
    situation: 'time',
    spanish: '¿Cuál es la fecha de hoy?',
    english: 'What is today\'s date?',
    notes: 'Dates use day/month format: "el 15 de marzo" (March 15)',
    formality: 'neutral',
    reply: { spanish: 'Hoy es el veintisiete de febrero.', english: 'Today is February twenty-seventh.' },
  },
  {
    id: 'time-7',
    situation: 'time',
    spanish: 'Tengo una cita el lunes a las nueve',
    english: 'I have an appointment on Monday at nine',
    notes: '"Cita" means appointment or date depending on context',
    formality: 'neutral',
    reply: { spanish: 'Perfecto, lo apuntaré en la agenda.', english: 'Perfect, I\'ll note it in the calendar.' },
  },
  {
    id: 'time-8',
    situation: 'time',
    spanish: '¿Podemos cambiar la hora de la cita?',
    english: 'Can we change the appointment time?',
    notes: 'Useful for rescheduling',
    formality: 'neutral',
    reply: { spanish: '¿Le viene bien el jueves a las cuatro?', english: 'Does Thursday at four work for you?' },
  },
  {
    id: 'time-9',
    situation: 'time',
    spanish: 'Perdona, llego tarde. Había mucho tráfico.',
    english: 'Sorry, I\'m late. There was a lot of traffic.',
    notes: '"Llegar tarde" is to arrive late; a very common excuse in big cities',
    formality: 'informal',
    reply: { spanish: 'No te preocupes, acabo de llegar yo también.', english: 'Don\'t worry, I just arrived too.' },
  },
  {
    id: 'time-10',
    situation: 'time',
    spanish: 'El vuelo sale a las seis de la mañana',
    english: 'The flight leaves at six in the morning',
    notes: 'Spanish specifies "de la mañana" (AM), "de la tarde" (PM), "de la noche" (evening/night)',
    formality: 'neutral',
    reply: { spanish: '¡Qué temprano! Hay que madrugar.', english: 'So early! We have to get up at the crack of dawn.' },
  },
  {
    id: 'time-11',
    situation: 'time',
    spanish: 'La tienda abre de lunes a sábado',
    english: 'The store is open Monday through Saturday',
    notes: 'Many shops in Spain close on Sundays',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'time-12',
    situation: 'time',
    spanish: '¿Hasta qué hora están abiertos?',
    english: 'Until what time are you open?',
    notes: '"Hasta" means until; important for planning visits',
    formality: 'neutral',
    reply: { spanish: 'Hasta las ocho de la noche.', english: 'Until eight in the evening.' },
  },
  {
    id: 'time-13',
    situation: 'time',
    spanish: 'Faltan veinte minutos para las cinco',
    english: 'It\'s twenty minutes to five',
    notes: '"Faltar" is used to express how much time remains before the hour',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'time-14',
    situation: 'time',
    spanish: 'Mi cumpleaños es el doce de agosto',
    english: 'My birthday is August twelfth',
    notes: 'Months are not capitalized in Spanish: enero, febrero, marzo...',
    formality: 'neutral',
    reply: { spanish: '¡Qué bien! ¿Vas a hacer fiesta?', english: 'How nice! Are you going to have a party?' },
  },
  {
    id: 'time-15',
    situation: 'time',
    spanish: 'Nos vemos el próximo fin de semana',
    english: 'See you next weekend',
    notes: '"Fin de semana" is weekend; "entre semana" is weekdays',
    formality: 'neutral',
    reply: { spanish: '¡Perfecto! Ya quedamos entonces.', english: 'Perfect! It\'s a plan then.' },
  },

  // ============================================================
  // 10. SOCIAL — Conversación Social
  // ============================================================
  {
    id: 'social-1',
    situation: 'social',
    spanish: '¿Qué te gusta hacer en tu tiempo libre?',
    english: 'What do you like to do in your free time?',
    notes: '"Tiempo libre" is free time; "pasatiempos" or "hobbies" for hobbies',
    formality: 'informal',
    reply: { spanish: 'Me gusta leer y salir a caminar. ¿Y a ti?', english: 'I like reading and going for walks. And you?' },
  },
  {
    id: 'social-2',
    situation: 'social',
    spanish: '¡Qué buen tiempo hace hoy!',
    english: 'What nice weather today!',
    notes: '"Hacer" is used for weather: hace calor (it\'s hot), hace frío (it\'s cold)',
    formality: 'neutral',
    reply: { spanish: 'Sí, perfecto para dar un paseo.', english: 'Yes, perfect for a stroll.' },
  },
  {
    id: 'social-3',
    situation: 'social',
    spanish: '¿Has visto alguna buena película últimamente?',
    english: 'Have you seen any good movies lately?',
    notes: 'Great conversation starter',
    formality: 'informal',
    reply: { spanish: 'Sí, vi una española muy buena. Te la recomiendo.', english: 'Yes, I saw a really good Spanish one. I recommend it.' },
  },
  {
    id: 'social-4',
    situation: 'social',
    spanish: 'Me encanta la música latina',
    english: 'I love Latin music',
    notes: '"Encantar" is stronger than "gustar"; it works the same grammatically',
    formality: 'neutral',
    reply: { spanish: '¿En serio? ¿Cuál es tu artista favorito?', english: 'Really? Who\'s your favorite artist?' },
  },
  {
    id: 'social-5',
    situation: 'social',
    spanish: '¿Qué planes tienes para el fin de semana?',
    english: 'What are your plans for the weekend?',
    notes: 'Common way to suggest hanging out or making plans',
    formality: 'informal',
    reply: { spanish: 'Todavía nada. ¿Quieres hacer algo?', english: 'Nothing yet. Want to do something?' },
  },
  {
    id: 'social-6',
    situation: 'social',
    spanish: '¿Te apetece tomar un café?',
    english: 'Do you feel like having a coffee?',
    notes: '"Apetecer" is very common in Spain; in Latin America you might hear "¿Se te antoja?"',
    formality: 'informal',
    reply: { spanish: '¡Sí, claro! Conozco un sitio muy bueno.', english: 'Yes, of course! I know a really good place.' },
  },
  {
    id: 'social-7',
    situation: 'social',
    spanish: '¡Qué interesante! Cuéntame más.',
    english: 'How interesting! Tell me more.',
    notes: 'Shows genuine interest in the conversation',
    formality: 'informal',
    reply: { spanish: 'Pues resulta que...', english: 'Well, it turns out that...' },
  },
  {
    id: 'social-8',
    situation: 'social',
    spanish: '¿Conoces algún buen restaurante por aquí?',
    english: 'Do you know any good restaurants around here?',
    notes: '"Conocer" for knowing places or people; "saber" for knowing facts',
    formality: 'informal',
    reply: { spanish: 'Sí, hay uno mexicano buenísimo a dos calles.', english: 'Yes, there\'s an amazing Mexican one two streets away.' },
  },
  {
    id: 'social-9',
    situation: 'social',
    spanish: 'Parece que va a llover',
    english: 'It looks like it\'s going to rain',
    notes: 'Classic small talk; "llover" is to rain, "nevar" is to snow',
    formality: 'neutral',
    reply: { spanish: 'Sí, mejor llevo un paraguas.', english: 'Yes, better take an umbrella.' },
  },
  {
    id: 'social-10',
    situation: 'social',
    spanish: '¿Eres aficionado al fútbol?',
    english: 'Are you a soccer fan?',
    notes: 'Football (soccer) is by far the most popular sport in the Spanish-speaking world',
    formality: 'informal',
    reply: { spanish: '¡Sí! Soy del Real Madrid. ¿Y tú?', english: 'Yes! I\'m a Real Madrid fan. And you?' },
  },
  {
    id: 'social-11',
    situation: 'social',
    spanish: '¿Has viajado mucho por Latinoamérica?',
    english: 'Have you traveled much through Latin America?',
    notes: 'Great topic for connecting with other travelers',
    formality: 'informal',
    reply: { spanish: 'Sí, he estado en México, Colombia y Argentina.', english: 'Yes, I\'ve been to Mexico, Colombia, and Argentina.' },
  },
  {
    id: 'social-12',
    situation: 'social',
    spanish: '¿Quieres que salgamos a bailar esta noche?',
    english: 'Want to go out dancing tonight?',
    notes: 'Dancing is a huge part of social culture in Latin America',
    formality: 'informal',
    reply: { spanish: '¡Me encantaría! ¿Adónde vamos?', english: 'I\'d love to! Where are we going?' },
  },
  {
    id: 'social-13',
    situation: 'social',
    spanish: 'La verdad es que no me gusta mucho el calor',
    english: 'To be honest, I don\'t really like the heat',
    notes: '"La verdad es que..." is a natural way to express honest opinions',
    formality: 'informal',
    reply: { spanish: 'Te entiendo. A mí me gusta más el otoño.', english: 'I understand. I prefer autumn.' },
  },
  {
    id: 'social-14',
    situation: 'social',
    spanish: '¿Cómo se llama tu mascota?',
    english: 'What\'s your pet\'s name?',
    notes: '"Mascota" is pet; pets are beloved conversation topics everywhere',
    formality: 'informal',
    reply: { spanish: 'Se llama Luna. Es una gata muy cariñosa.', english: 'Her name is Luna. She\'s a very affectionate cat.' },
  },
  {
    id: 'social-15',
    situation: 'social',
    spanish: '¡Qué bonita foto! ¿Dónde la tomaste?',
    english: 'What a beautiful photo! Where did you take it?',
    notes: 'Great for social media conversations or looking at someone\'s phone gallery',
    formality: 'informal',
    reply: { spanish: 'En la playa de Cancún, el verano pasado.', english: 'At Cancún beach, last summer.' },
  },
  {
    id: 'social-16',
    situation: 'social',
    spanish: 'Me cae muy bien tu amigo. Es muy simpático.',
    english: 'I really like your friend. He\'s very nice.',
    notes: '"Caer bien" means to like someone (personality); not romantic',
    formality: 'informal',
    reply: { spanish: 'Sí, es muy buena persona. Se llevarían bien.', english: 'Yes, he\'s a great person. You two would get along.' },
  },

  // ============================================================
  // 11. EMERGENCY — Emergencias
  // ============================================================
  {
    id: 'emerg-1',
    situation: 'emergency',
    spanish: '¡Ayuda! ¡Necesito ayuda!',
    english: 'Help! I need help!',
    notes: 'The single most important emergency phrase to know',
    formality: 'neutral',
    reply: { spanish: '¿Qué pasó? ¿Está bien?', english: 'What happened? Are you okay?' },
  },
  {
    id: 'emerg-2',
    situation: 'emergency',
    spanish: '¡Llame a una ambulancia, por favor!',
    english: 'Call an ambulance, please!',
    notes: 'Emergency numbers vary by country: 112 in Spain, 911 in Mexico',
    formality: 'neutral',
    reply: { spanish: 'Ya estoy llamando. ¡Quédese tranquilo!', english: 'I\'m calling now. Stay calm!' },
  },
  {
    id: 'emerg-3',
    situation: 'emergency',
    spanish: 'Necesito llamar a la policía',
    english: 'I need to call the police',
    notes: '"Policía" is both the police force and an individual officer',
    formality: 'neutral',
    reply: { spanish: '¿Qué ha pasado? ¿Está en peligro?', english: 'What happened? Are you in danger?' },
  },
  {
    id: 'emerg-4',
    situation: 'emergency',
    spanish: '¡Fuego! ¡Hay un incendio!',
    english: 'Fire! There\'s a fire!',
    notes: '"Fuego" is fire; "incendio" is a fire (the event); "bomberos" are firefighters',
    formality: 'neutral',
    reply: { spanish: '¡Salgan todos! ¡Llamen a los bomberos!', english: 'Everyone get out! Call the firefighters!' },
  },
  {
    id: 'emerg-5',
    situation: 'emergency',
    spanish: 'Me han robado la cartera',
    english: 'My wallet has been stolen',
    notes: '"Robar" is to steal; you should file a "denuncia" (police report)',
    formality: 'neutral',
    reply: { spanish: 'Tiene que ir a la comisaría a poner una denuncia.', english: 'You need to go to the police station to file a report.' },
  },
  {
    id: 'emerg-6',
    situation: 'emergency',
    spanish: '¡Cuidado! ¡Es peligroso!',
    english: 'Watch out! It\'s dangerous!',
    notes: '"Cuidado" is the universal warning word',
    formality: 'neutral',
    reply: null,
  },
  {
    id: 'emerg-7',
    situation: 'emergency',
    spanish: 'He perdido mi pasaporte',
    english: 'I\'ve lost my passport',
    notes: 'Contact your embassy or consulate immediately: "embajada" (embassy), "consulado" (consulate)',
    formality: 'neutral',
    reply: { spanish: 'Debe contactar a su embajada lo antes posible.', english: 'You should contact your embassy as soon as possible.' },
  },
  {
    id: 'emerg-8',
    situation: 'emergency',
    spanish: '¿Dónde está la salida de emergencia?',
    english: 'Where is the emergency exit?',
    notes: 'Always locate emergency exits when entering buildings',
    formality: 'neutral',
    reply: { spanish: 'Al final del pasillo, la puerta roja.', english: 'At the end of the hallway, the red door.' },
  },
  {
    id: 'emerg-9',
    situation: 'emergency',
    spanish: 'Alguien se ha desmayado',
    english: 'Someone has fainted',
    notes: '"Desmayarse" is to faint; check if they are breathing',
    formality: 'neutral',
    reply: { spanish: 'No lo muevan. Voy a llamar al 112.', english: 'Don\'t move them. I\'m going to call 112.' },
  },
  {
    id: 'emerg-10',
    situation: 'emergency',
    spanish: '¿Alguien aquí sabe primeros auxilios?',
    english: 'Does anyone here know first aid?',
    notes: '"Primeros auxilios" is first aid',
    formality: 'neutral',
    reply: { spanish: 'Yo sé. ¿Qué ha pasado?', english: 'I do. What happened?' },
  },
  {
    id: 'emerg-11',
    situation: 'emergency',
    spanish: 'Hay un accidente de tráfico en la carretera',
    english: 'There\'s a traffic accident on the highway',
    notes: '"Accidente de tráfico" or "accidente de tránsito" depending on the country',
    formality: 'neutral',
    reply: { spanish: '¿Hay heridos? Voy a llamar a emergencias.', english: 'Are there injuries? I\'m going to call emergency services.' },
  },
  {
    id: 'emerg-12',
    situation: 'emergency',
    spanish: 'Mi hijo se ha perdido. Tiene cinco años.',
    english: 'My child is lost. He\'s five years old.',
    notes: 'Describe the child: clothing, hair color, name',
    formality: 'neutral',
    reply: { spanish: '¿Cómo se llama y qué ropa lleva?', english: 'What\'s his name and what is he wearing?' },
  },
  {
    id: 'emerg-13',
    situation: 'emergency',
    spanish: 'Necesito contactar a mi embajada',
    english: 'I need to contact my embassy',
    notes: 'Embassies can help with lost documents, legal issues, and emergencies abroad',
    formality: 'formal',
    reply: { spanish: '¿De qué país es usted? Le busco el número.', english: 'What country are you from? I\'ll look up the number.' },
  },
  {
    id: 'emerg-14',
    situation: 'emergency',
    spanish: 'Tengo una emergencia médica. ¿Hay un hospital cerca?',
    english: 'I have a medical emergency. Is there a hospital nearby?',
    notes: '"Urgencias" is the emergency room at a hospital',
    formality: 'neutral',
    reply: { spanish: 'Sí, el Hospital General está a tres calles.', english: 'Yes, the General Hospital is three blocks away.' },
  },
  {
    id: 'emerg-15',
    situation: 'emergency',
    spanish: '¡No se mueva! Ya viene la ayuda.',
    english: 'Don\'t move! Help is on the way.',
    notes: 'Important instruction if someone is injured',
    formality: 'neutral',
    reply: null,
  },

  // ============================================================
  // 12. WORK — Trabajo
  // ============================================================
  {
    id: 'work-1',
    situation: 'work',
    spanish: 'Buenos días. Vengo a la entrevista de trabajo.',
    english: 'Good morning. I\'m here for the job interview.',
    notes: '"Entrevista de trabajo" is job interview',
    formality: 'formal',
    reply: { spanish: 'Bienvenido. Tome asiento, por favor. Le atenderán en unos minutos.', english: 'Welcome. Please have a seat. Someone will be with you in a few minutes.' },
  },
  {
    id: 'work-2',
    situation: 'work',
    spanish: 'Tengo experiencia en atención al cliente',
    english: 'I have experience in customer service',
    notes: '"Atención al cliente" is customer service; a transferable skill everywhere',
    formality: 'formal',
    reply: { spanish: '¡Excelente! Eso es justo lo que buscamos.', english: 'Excellent! That\'s exactly what we\'re looking for.' },
  },
  {
    id: 'work-3',
    situation: 'work',
    spanish: '¿Cuál es el horario de trabajo?',
    english: 'What are the working hours?',
    notes: '"Horario" is schedule; "jornada completa" (full-time), "media jornada" (part-time)',
    formality: 'formal',
    reply: { spanish: 'De nueve a seis, de lunes a viernes.', english: 'Nine to six, Monday to Friday.' },
  },
  {
    id: 'work-4',
    situation: 'work',
    spanish: '¿Podemos programar una reunión para mañana?',
    english: 'Can we schedule a meeting for tomorrow?',
    notes: '"Programar" or "agendar" for scheduling',
    formality: 'formal',
    reply: { spanish: 'Sí, ¿le parece bien a las once?', english: 'Yes, does eleven work for you?' },
  },
  {
    id: 'work-5',
    situation: 'work',
    spanish: 'Le envío el informe por correo electrónico',
    english: 'I\'ll send you the report by email',
    notes: '"Informe" is report; "correo electrónico" is email',
    formality: 'formal',
    reply: { spanish: 'Perfecto, lo reviso y le doy mis comentarios.', english: 'Perfect, I\'ll review it and give you my feedback.' },
  },
  {
    id: 'work-6',
    situation: 'work',
    spanish: '¿Cuándo es la fecha límite del proyecto?',
    english: 'When is the project deadline?',
    notes: '"Fecha límite" or "plazo" for deadline',
    formality: 'formal',
    reply: { spanish: 'El viernes de la próxima semana.', english: 'Friday of next week.' },
  },
  {
    id: 'work-7',
    situation: 'work',
    spanish: 'Necesito unos días libres la próxima semana',
    english: 'I need a few days off next week',
    notes: '"Días libres" is days off; "vacaciones" for vacation',
    formality: 'formal',
    reply: { spanish: '¿Por algún motivo en particular?', english: 'For any particular reason?' },
  },
  {
    id: 'work-8',
    situation: 'work',
    spanish: '¿Podría explicar eso con más detalle?',
    english: 'Could you explain that in more detail?',
    notes: 'Polite way to ask for clarification in a meeting',
    formality: 'formal',
    reply: { spanish: 'Por supuesto. Lo que quiero decir es que...', english: 'Of course. What I mean is that...' },
  },
  {
    id: 'work-9',
    situation: 'work',
    spanish: 'Estoy de acuerdo con su propuesta',
    english: 'I agree with your proposal',
    notes: '"Estar de acuerdo" is to agree; very common in business',
    formality: 'formal',
    reply: { spanish: 'Me alegra. Entonces procedemos con el plan.', english: 'I\'m glad. Then we\'ll proceed with the plan.' },
  },
  {
    id: 'work-10',
    situation: 'work',
    spanish: '¿Cuál es el salario para este puesto?',
    english: 'What is the salary for this position?',
    notes: '"Puesto" is position; asking about salary in an interview is normal in Latin America',
    formality: 'formal',
    reply: { spanish: 'El rango está entre treinta y cuarenta mil anuales.', english: 'The range is between thirty and forty thousand annually.' },
  },
  {
    id: 'work-11',
    situation: 'work',
    spanish: 'Tengo una conferencia por videollamada a las tres',
    english: 'I have a video conference at three',
    notes: '"Videollamada" is video call; remote work vocabulary is increasingly common',
    formality: 'neutral',
    reply: { spanish: '¿Necesitas la sala de reuniones?', english: 'Do you need the meeting room?' },
  },
  {
    id: 'work-12',
    situation: 'work',
    spanish: 'El jefe quiere hablar con usted',
    english: 'The boss wants to speak with you',
    notes: '"Jefe" is boss; "gerente" is manager',
    formality: 'formal',
    reply: { spanish: '¿Sabe de qué se trata?', english: 'Do you know what it\'s about?' },
  },
  {
    id: 'work-13',
    situation: 'work',
    spanish: 'Trabajo desde casa los viernes',
    english: 'I work from home on Fridays',
    notes: '"Trabajo remoto" or "teletrabajo" for remote work',
    formality: 'neutral',
    reply: { spanish: 'Qué suerte. Nosotros tenemos que ir todos los días.', english: 'How lucky. We have to go in every day.' },
  },
  {
    id: 'work-14',
    situation: 'work',
    spanish: 'Aquí tiene mi currículum vitae',
    english: 'Here is my résumé',
    notes: '"Currículum vitae" or just "currículum" (CV) is used instead of "résumé"',
    formality: 'formal',
    reply: { spanish: 'Gracias. Veo que tiene mucha experiencia.', english: 'Thank you. I see you have a lot of experience.' },
  },
  {
    id: 'work-15',
    situation: 'work',
    spanish: '¿Ofrecen beneficios como seguro médico?',
    english: 'Do you offer benefits like health insurance?',
    notes: '"Beneficios" or "prestaciones" for benefits; important to ask in interviews',
    formality: 'formal',
    reply: { spanish: 'Sí, incluimos seguro médico, dental y vacaciones pagadas.', english: 'Yes, we include medical, dental, and paid vacation.' },
  },
  {
    id: 'work-16',
    situation: 'work',
    spanish: 'Ha sido un placer. Espero tener noticias suyas pronto.',
    english: 'It\'s been a pleasure. I hope to hear from you soon.',
    notes: 'Professional closing for a job interview',
    formality: 'formal',
    reply: { spanish: 'Igualmente. Le contactaremos la próxima semana.', english: 'Likewise. We\'ll contact you next week.' },
  },

  // ============================================================
  // 13. ROMANCE — Romance
  // ============================================================
  {
    id: 'romance-1',
    situation: 'romance',
    spanish: 'Tienes una sonrisa muy bonita',
    english: 'You have a very beautiful smile',
    notes: 'A sweet and respectful compliment to start with',
    formality: 'informal',
    reply: { spanish: '¡Qué lindo! Gracias, tú también.', english: 'How sweet! Thanks, you too.' },
  },
  {
    id: 'romance-2',
    situation: 'romance',
    spanish: '¿Te gustaría salir a cenar conmigo?',
    english: 'Would you like to go out to dinner with me?',
    notes: '"Salir a cenar" is to go out to dinner; a classic date invitation',
    formality: 'informal',
    reply: { spanish: 'Me encantaría. ¿Cuándo?', english: 'I\'d love to. When?' },
  },
  {
    id: 'romance-3',
    situation: 'romance',
    spanish: 'La pasé muy bien contigo',
    english: 'I had a great time with you',
    notes: '"Pasarla bien" means to have a good time; said after a date',
    formality: 'informal',
    reply: { spanish: 'Yo también. ¿Repetimos pronto?', english: 'Me too. Shall we do it again soon?' },
  },
  {
    id: 'romance-4',
    situation: 'romance',
    spanish: 'Me gustas mucho',
    english: 'I like you a lot',
    notes: '"Gustar" with people means romantic attraction; this is a big step in Spanish',
    formality: 'informal',
    reply: { spanish: 'Tú también me gustas.', english: 'I like you too.' },
  },
  {
    id: 'romance-5',
    situation: 'romance',
    spanish: 'Eres muy especial para mí',
    english: 'You are very special to me',
    notes: 'Expresses deep affection beyond initial attraction',
    formality: 'informal',
    reply: { spanish: 'Tú también eres muy especial para mí.', english: 'You are very special to me too.' },
  },
  {
    id: 'romance-6',
    situation: 'romance',
    spanish: '¿Quieres ser mi novio/novia?',
    english: 'Do you want to be my boyfriend/girlfriend?',
    notes: 'In Latin culture, making the relationship official is often done explicitly',
    formality: 'informal',
    reply: { spanish: '¡Sí! ¡Claro que sí!', english: 'Yes! Of course!' },
  },
  {
    id: 'romance-7',
    situation: 'romance',
    spanish: 'Te extraño mucho',
    english: 'I miss you a lot',
    notes: '"Extrañar" in Latin America; "echar de menos" in Spain',
    formality: 'informal',
    reply: { spanish: 'Yo también te extraño. Ojalá estuvieras aquí.', english: 'I miss you too. I wish you were here.' },
  },
  {
    id: 'romance-8',
    situation: 'romance',
    spanish: 'Te quiero',
    english: 'I love you',
    notes: '"Te quiero" is the most common way to say "I love you" in romantic contexts; "te amo" is even stronger and more intense',
    formality: 'informal',
    reply: { spanish: 'Yo también te quiero, mi amor.', english: 'I love you too, my love.' },
  },
  {
    id: 'romance-9',
    situation: 'romance',
    spanish: 'Eres la persona más guapa que he conocido',
    english: 'You\'re the most beautiful person I\'ve ever met',
    notes: '"Guapo/guapa" is handsome/beautiful; works for both genders',
    formality: 'informal',
    reply: { spanish: 'Eres muy dulce. Me haces sonreír.', english: 'You\'re very sweet. You make me smile.' },
  },
  {
    id: 'romance-10',
    situation: 'romance',
    spanish: '¿Puedo invitarte a un café?',
    english: 'Can I buy you a coffee?',
    notes: '"Invitar" means to treat someone; a low-pressure way to ask someone out',
    formality: 'informal',
    reply: { spanish: '¡Sí, me encantaría! Gracias.', english: 'Yes, I\'d love that! Thanks.' },
  },
  {
    id: 'romance-11',
    situation: 'romance',
    spanish: 'Contigo me siento muy a gusto',
    english: 'I feel very comfortable with you',
    notes: '"A gusto" means at ease, comfortable; a lovely thing to hear',
    formality: 'informal',
    reply: { spanish: 'Yo también. Me siento muy bien a tu lado.', english: 'Me too. I feel great by your side.' },
  },
  {
    id: 'romance-12',
    situation: 'romance',
    spanish: '¿Bailamos?',
    english: 'Shall we dance?',
    notes: 'Asking someone to dance at a party or club is very natural in Latin culture',
    formality: 'informal',
    reply: { spanish: '¡Claro! Me encanta esta canción.', english: 'Of course! I love this song.' },
  },
  {
    id: 'romance-13',
    situation: 'romance',
    spanish: 'Pienso en ti todo el tiempo',
    english: 'I think about you all the time',
    notes: '"Pensar en" means to think about; romantic and sincere',
    formality: 'informal',
    reply: { spanish: 'Yo también pienso mucho en ti.', english: 'I think about you a lot too.' },
  },
  {
    id: 'romance-14',
    situation: 'romance',
    spanish: 'Tienes unos ojos preciosos',
    english: 'You have beautiful eyes',
    notes: '"Precioso/preciosa" is a very romantic word for beautiful',
    formality: 'informal',
    reply: { spanish: '¡Ay, qué romántico! Gracias, cariño.', english: 'Oh, how romantic! Thanks, darling.' },
  },
  {
    id: 'romance-15',
    situation: 'romance',
    spanish: 'Me haces muy feliz',
    english: 'You make me very happy',
    notes: 'A heartfelt expression for an established relationship',
    formality: 'informal',
    reply: { spanish: 'Y tú a mí. Eres lo mejor que me ha pasado.', english: 'And you me. You\'re the best thing that\'s happened to me.' },
  },
  {
    id: 'romance-16',
    situation: 'romance',
    spanish: '¿Quieres conocer a mi familia?',
    english: 'Would you like to meet my family?',
    notes: 'Meeting the family is a significant step in Latin culture and shows serious commitment',
    formality: 'informal',
    reply: { spanish: '¡Sí! Estoy un poco nerviosa, pero sí.', english: 'Yes! I\'m a little nervous, but yes.' },
  },
];
