// ════════════════════════════════════════════════════════════
//  LECCION DIARIA — Placement Test Question Bank
//  ~120 hand-crafted questions, CEFR A1-C2
//  IRT difficulty scale: A1=1.0-1.8, A2=1.9-2.7,
//    B1=2.8-3.5, B2=3.6-4.3, C1=4.4-5.2, C2=5.3-6.5
// ════════════════════════════════════════════════════════════

'use strict';

const PLACEMENT_QUESTIONS = [

  // ──────────────────────────────────────────────────────────
  //  A1 — Beginner (difficulty 1.0–1.8)
  // ──────────────────────────────────────────────────────────

  {
    id: 'pq-a1-01',
    level: 'A1',
    difficulty: 1.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Yo ___ estudiante.',
    answer: 'soy',
    options: ['soy', 'estoy', 'es', 'ser'],
    explanation: '"Soy" is the first-person singular of "ser," used for identity and occupation.',
  },
  {
    id: 'pq-a1-02',
    level: 'A1',
    difficulty: 1.1,
    domain: 'vocab',
    type: 'mc',
    prompt: 'What does "gato" mean in English?',
    answer: 'cat',
    options: ['dog', 'cat', 'bird', 'fish'],
    explanation: '"Gato" means "cat" in Spanish.',
  },
  {
    id: 'pq-a1-03',
    level: 'A1',
    difficulty: 1.1,
    domain: 'grammar',
    type: 'mc',
    prompt: '"Necesito la ___." Which noun is feminine?',
    answer: 'mesa',
    options: ['libro', 'mesa', 'coche', 'zapato'],
    explanation: '"Mesa" is feminine (la mesa). The others are masculine: el libro, el coche, el zapato.',
  },
  {
    id: 'pq-a1-04',
    level: 'A1',
    difficulty: 1.2,
    domain: 'vocab',
    type: 'mc',
    prompt: 'How do you say "thank you" in Spanish?',
    answer: 'gracias',
    options: ['por favor', 'gracias', 'de nada', 'perdón'],
    explanation: '"Gracias" means "thank you."',
  },
  {
    id: 'pq-a1-05',
    level: 'A1',
    difficulty: 1.2,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Ella ___ profesora. (ser, present tense)',
    answer: 'es',
    options: null,
    explanation: '"Es" is the third-person singular of "ser."',
  },
  {
    id: 'pq-a1-06',
    level: 'A1',
    difficulty: 1.3,
    domain: 'vocab',
    type: 'mc',
    prompt: 'Which number is "quince"?',
    answer: '15',
    options: ['5', '14', '15', '50'],
    explanation: '"Quince" means 15.',
  },
  {
    id: 'pq-a1-07',
    level: 'A1',
    difficulty: 1.3,
    domain: 'usage',
    type: 'mc',
    prompt: 'How do you greet someone in the morning?',
    answer: 'Buenos días',
    options: ['Buenas noches', 'Buenos días', 'Buenas tardes', 'Hasta luego'],
    explanation: '"Buenos días" is the morning greeting.',
  },
  {
    id: 'pq-a1-08',
    level: 'A1',
    difficulty: 1.3,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Nosotros ___ en la escuela. (estar)',
    answer: 'estamos',
    options: ['estoy', 'estás', 'estamos', 'están'],
    explanation: '"Estamos" is the first-person plural of "estar."',
  },
  {
    id: 'pq-a1-09',
    level: 'A1',
    difficulty: 1.4,
    domain: 'grammar',
    type: 'mc',
    prompt: '___ libros son interesantes.',
    answer: 'Los',
    options: ['El', 'La', 'Los', 'Las'],
    explanation: '"Libros" is masculine plural, so the article is "los."',
  },
  {
    id: 'pq-a1-10',
    level: 'A1',
    difficulty: 1.4,
    domain: 'vocab',
    type: 'fib',
    prompt: 'The days of the week: lunes, martes, ___, jueves, viernes.',
    answer: 'miércoles',
    options: null,
    explanation: 'The missing day is "miércoles" (Wednesday).',
  },
  {
    id: 'pq-a1-11',
    level: 'A1',
    difficulty: 1.5,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Tú ___ agua. (beber, present tense)',
    answer: 'bebes',
    options: ['bebo', 'bebes', 'bebe', 'beben'],
    explanation: '"Bebes" is the second-person singular of "beber."',
  },
  {
    id: 'pq-a1-12',
    level: 'A1',
    difficulty: 1.5,
    domain: 'usage',
    type: 'mc',
    prompt: 'Someone says "¿Cómo te llamas?" — what are they asking?',
    answer: 'What is your name?',
    options: ['How old are you?', 'Where are you from?', 'What is your name?', 'How are you?'],
    explanation: '"¿Cómo te llamas?" means "What is your name?"',
  },
  {
    id: 'pq-a1-13',
    level: 'A1',
    difficulty: 1.5,
    domain: 'vocab',
    type: 'mc',
    prompt: 'Which color is "rojo"?',
    answer: 'red',
    options: ['blue', 'green', 'red', 'yellow'],
    explanation: '"Rojo" means "red."',
  },
  {
    id: 'pq-a1-14',
    level: 'A1',
    difficulty: 1.6,
    domain: 'grammar',
    type: 'fib',
    prompt: 'María y yo ___ amigos. (ser, present tense)',
    answer: 'somos',
    options: null,
    explanation: '"María y yo" = "nosotros," so the verb is "somos."',
  },
  {
    id: 'pq-a1-15',
    level: 'A1',
    difficulty: 1.6,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Ellos ___ en el parque. (vivir, present tense)',
    answer: 'viven',
    options: ['vivo', 'vives', 'vive', 'viven'],
    explanation: '"Viven" is the third-person plural of "vivir."',
  },
  {
    id: 'pq-a1-16',
    level: 'A1',
    difficulty: 1.6,
    domain: 'vocab',
    type: 'mc',
    prompt: 'What is "hermano" in English?',
    answer: 'brother',
    options: ['sister', 'brother', 'father', 'cousin'],
    explanation: '"Hermano" means "brother."',
  },
  {
    id: 'pq-a1-17',
    level: 'A1',
    difficulty: 1.7,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Mi casa es ___. (grande — agree with "casa")',
    answer: 'grande',
    options: ['gran', 'grande', 'grandes', 'grandísima'],
    explanation: '"Grande" does not change for gender; it stays "grande" with singular nouns after "ser." "Gran" is only used before a noun.',
  },
  {
    id: 'pq-a1-18',
    level: 'A1',
    difficulty: 1.7,
    domain: 'usage',
    type: 'mc',
    prompt: 'You want to order food. How do you say "I would like water"?',
    answer: 'Quisiera agua',
    options: ['Tengo agua', 'Quisiera agua', 'Soy agua', 'Hay agua'],
    explanation: '"Quisiera" means "I would like," used for polite requests.',
  },
  {
    id: 'pq-a1-19',
    level: 'A1',
    difficulty: 1.8,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Yo ___ veinte años. (How old are you?)',
    answer: 'tengo',
    options: ['soy', 'estoy', 'tengo', 'hago'],
    explanation: 'In Spanish, age uses "tener": "Tengo veinte años."',
  },
  {
    id: 'pq-a1-20',
    level: 'A1',
    difficulty: 1.8,
    domain: 'vocab',
    type: 'fib',
    prompt: 'Opposite of "caliente" (hot) is ___.',
    answer: 'frío',
    options: null,
    explanation: '"Frío" means "cold," the opposite of "caliente."',
  },

  // ──────────────────────────────────────────────────────────
  //  A2 — Elementary (difficulty 1.9–2.7)
  // ──────────────────────────────────────────────────────────

  {
    id: 'pq-a2-01',
    level: 'A2',
    difficulty: 1.9,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Ayer yo ___ al cine. (ir, past tense)',
    answer: 'fui',
    options: ['voy', 'fui', 'iba', 'iré'],
    explanation: '"Fui" is the preterite first-person singular of "ir."',
  },
  {
    id: 'pq-a2-02',
    level: 'A2',
    difficulty: 1.9,
    domain: 'vocab',
    type: 'mc',
    prompt: 'Where do you buy medicine?',
    answer: 'la farmacia',
    options: ['la biblioteca', 'la farmacia', 'la panadería', 'la carnicería'],
    explanation: '"La farmacia" is the pharmacy where you buy medicine.',
  },
  {
    id: 'pq-a2-03',
    level: 'A2',
    difficulty: 2.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'La comida ___ deliciosa. (ser or estar?)',
    answer: 'está',
    options: ['es', 'está', 'son', 'están'],
    explanation: '"Está" is used because the food tastes delicious right now (condition/state).',
  },
  {
    id: 'pq-a2-04',
    level: 'A2',
    difficulty: 2.1,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Ella ___ hablando por teléfono. (present progressive)',
    answer: 'está',
    options: null,
    explanation: 'The present progressive uses "estar" + gerund: "está hablando."',
  },
  {
    id: 'pq-a2-05',
    level: 'A2',
    difficulty: 2.1,
    domain: 'usage',
    type: 'mc',
    prompt: '¿___ hora es? — Son las tres.',
    answer: 'Qué',
    options: ['Cuál', 'Qué', 'Cómo', 'Cuándo'],
    explanation: '"¿Qué hora es?" is the standard way to ask the time.',
  },
  {
    id: 'pq-a2-06',
    level: 'A2',
    difficulty: 2.2,
    domain: 'grammar',
    type: 'mc',
    prompt: 'A mí ___ gusta el chocolate.',
    answer: 'me',
    options: ['me', 'te', 'le', 'se'],
    explanation: '"A mí me gusta" — "me" is the indirect object pronoun for "yo."',
  },
  {
    id: 'pq-a2-07',
    level: 'A2',
    difficulty: 2.2,
    domain: 'vocab',
    type: 'mc',
    prompt: 'What does "izquierda" mean?',
    answer: 'left',
    options: ['right', 'straight', 'left', 'behind'],
    explanation: '"Izquierda" means "left" (direction).',
  },
  {
    id: 'pq-a2-08',
    level: 'A2',
    difficulty: 2.3,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Yo ___ a la tienda todos los días. (ir, present)',
    answer: 'voy',
    options: ['voy', 'vas', 'va', 'van'],
    explanation: '"Voy" is the first-person singular of "ir" in the present tense.',
  },
  {
    id: 'pq-a2-09',
    level: 'A2',
    difficulty: 2.3,
    domain: 'usage',
    type: 'fib',
    prompt: 'Tengo ___ estudiar para el examen. ("I have to study")',
    answer: 'que',
    options: null,
    explanation: '"Tener que" + infinitive means "to have to."',
  },
  {
    id: 'pq-a2-10',
    level: 'A2',
    difficulty: 2.3,
    domain: 'vocab',
    type: 'mc',
    prompt: '¿Qué ___ hace hoy? — Hace sol. (What\'s the weather like today?)',
    answer: 'tiempo',
    options: ['tiempo', 'hora', 'fecha', 'día'],
    explanation: '"¿Qué tiempo hace?" is the standard phrase for asking about the weather.',
  },
  {
    id: 'pq-a2-11',
    level: 'A2',
    difficulty: 2.4,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Ella ___ más alta que su hermana.',
    answer: 'es',
    options: ['es', 'está', 'tiene', 'hay'],
    explanation: '"Ser" is used for inherent characteristics like height.',
  },
  {
    id: 'pq-a2-12',
    level: 'A2',
    difficulty: 2.4,
    domain: 'grammar',
    type: 'mc',
    prompt: '¿Dónde ___ mis llaves? — No sé.',
    answer: 'están',
    options: ['son', 'están', 'es', 'hay'],
    explanation: '"Estar" is used for location: "¿Dónde están mis llaves?"',
  },
  {
    id: 'pq-a2-13',
    level: 'A2',
    difficulty: 2.5,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Nosotros ___ la película anoche. (ver, preterite)',
    answer: 'vimos',
    options: null,
    explanation: '"Vimos" is the preterite first-person plural of "ver."',
  },
  {
    id: 'pq-a2-14',
    level: 'A2',
    difficulty: 2.5,
    domain: 'usage',
    type: 'mc',
    prompt: 'How do you say "I like to read"?',
    answer: 'Me gusta leer',
    options: ['Yo gusto leer', 'Me gusta leer', 'Me gusta leo', 'Yo me gusta leer'],
    explanation: '"Gustar" takes an indirect object pronoun + infinitive.',
  },
  {
    id: 'pq-a2-15',
    level: 'A2',
    difficulty: 2.5,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Ella tiene mucha sed." What does she need?',
    answer: 'something to drink',
    options: ['food', 'sleep', 'something to drink', 'a jacket'],
    explanation: '"Tener sed" means "to be thirsty."',
  },
  {
    id: 'pq-a2-16',
    level: 'A2',
    difficulty: 2.6,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Yo ___ a Juan ayer. (conocer vs. saber, preterite)',
    answer: 'conocí',
    options: ['sabía', 'conocí', 'supe', 'conocía'],
    explanation: '"Conocer" in the preterite means "met for the first time."',
  },
  {
    id: 'pq-a2-17',
    level: 'A2',
    difficulty: 2.6,
    domain: 'vocab',
    type: 'fib',
    prompt: 'El hijo de mi tía es mi ___.',
    answer: 'primo',
    options: null,
    explanation: 'Your aunt\'s son is your cousin — "primo."',
  },
  {
    id: 'pq-a2-18',
    level: 'A2',
    difficulty: 2.6,
    domain: 'grammar',
    type: 'mc',
    prompt: '___ un banco cerca de aquí? (there is)',
    answer: 'Hay',
    options: ['Es', 'Está', 'Hay', 'Tiene'],
    explanation: '"Hay" means "there is/there are."',
  },
  {
    id: 'pq-a2-19',
    level: 'A2',
    difficulty: 2.7,
    domain: 'usage',
    type: 'mc',
    prompt: '"Hace buen tiempo hoy." What does this mean?',
    answer: 'The weather is nice today.',
    options: ['It is late today.', 'The weather is nice today.', 'I made good time today.', 'It is a good time today.'],
    explanation: '"Hacer" is used for weather expressions: "hace buen tiempo" = nice weather.',
  },
  {
    id: 'pq-a2-20',
    level: 'A2',
    difficulty: 2.7,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Yo no ___ nada. (double negative)',
    answer: 'sé',
    options: ['sé', 'conozco', 'puedo', 'tengo'],
    explanation: '"Saber" means "to know (facts)." "No sé nada" = "I don\'t know anything."',
  },

  // ──────────────────────────────────────────────────────────
  //  B1 — Intermediate (difficulty 2.8–3.5)
  // ──────────────────────────────────────────────────────────

  {
    id: 'pq-b1-01',
    level: 'B1',
    difficulty: 2.8,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Cuando era niño, ___ al parque todos los días. (ir)',
    answer: 'iba',
    options: ['fui', 'iba', 'iré', 'voy'],
    explanation: 'The imperfect "iba" is used for habitual actions in the past.',
  },
  {
    id: 'pq-b1-02',
    level: 'B1',
    difficulty: 2.8,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Este regalo es ___ ti.',
    answer: 'para',
    options: ['por', 'para', 'a', 'de'],
    explanation: '"Para" indicates the recipient or destination: "for you."',
  },
  {
    id: 'pq-b1-03',
    level: 'B1',
    difficulty: 2.9,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Gracias ___ ayudarme ayer.',
    answer: 'por',
    options: ['por', 'para', 'de', 'a'],
    explanation: '"Por" is used to express gratitude for something done.',
  },
  {
    id: 'pq-b1-04',
    level: 'B1',
    difficulty: 2.9,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Echar de menos" means:',
    answer: 'to miss (someone)',
    options: ['to throw away', 'to miss (someone)', 'to blame', 'to lose'],
    explanation: '"Echar de menos" is an idiomatic expression meaning "to miss someone."',
  },
  {
    id: 'pq-b1-05',
    level: 'B1',
    difficulty: 3.0,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Ya ___ comido cuando llegaste. (haber, pluperfect, yo)',
    answer: 'había',
    options: null,
    explanation: 'The pluperfect uses "había" + past participle.',
  },
  {
    id: 'pq-b1-06',
    level: 'B1',
    difficulty: 3.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Yo ___ si tuviera tiempo. (hacer, conditional)',
    answer: 'lo haría',
    options: ['lo hacía', 'lo haría', 'lo hice', 'lo hago'],
    explanation: '"Haría" is the conditional of "hacer": "I would do it."',
  },
  {
    id: 'pq-b1-07',
    level: 'B1',
    difficulty: 3.0,
    domain: 'usage',
    type: 'mc',
    prompt: '"Acabar de" + infinitive means:',
    answer: 'to have just done something',
    options: ['to finish doing something', 'to have just done something', 'to stop doing something', 'to end up doing something'],
    explanation: '"Acabo de comer" = "I have just eaten."',
  },
  {
    id: 'pq-b1-08',
    level: 'B1',
    difficulty: 3.1,
    domain: 'grammar',
    type: 'mc',
    prompt: 'El libro ___ escribió mi padre es famoso.',
    answer: 'que',
    options: ['que', 'quien', 'cual', 'cuyo'],
    explanation: '"Que" is the most common relative pronoun, used for things and people.',
  },
  {
    id: 'pq-b1-09',
    level: 'B1',
    difficulty: 3.1,
    domain: 'grammar',
    type: 'mc',
    prompt: '¿___ diste el regalo? — A María.',
    answer: 'A quién le',
    options: ['Quién le', 'A quién le', 'A quién lo', 'Quién se'],
    explanation: '"A quién le" asks about the indirect object: "To whom did you give it?"',
  },
  {
    id: 'pq-b1-10',
    level: 'B1',
    difficulty: 3.2,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Quiero que tú ___ la verdad. (decir, present subjunctive)',
    answer: 'digas',
    options: ['dices', 'digas', 'diga', 'dijeras'],
    explanation: 'After "quiero que," the subjunctive is required: "digas."',
  },
  {
    id: 'pq-b1-11',
    level: 'B1',
    difficulty: 3.2,
    domain: 'vocab',
    type: 'fib',
    prompt: '"Tener en cuenta" means to take into ___.',
    answer: 'account',
    options: null,
    explanation: '"Tener en cuenta" = "to take into account / to bear in mind."',
  },
  {
    id: 'pq-b1-12',
    level: 'B1',
    difficulty: 3.2,
    domain: 'usage',
    type: 'mc',
    prompt: '"Se me olvidó el libro." This sentence emphasizes that:',
    answer: 'the forgetting was unintentional',
    options: ['the book was lost', 'someone else forgot it', 'the forgetting was unintentional', 'the book is not important'],
    explanation: 'The "se me" construction expresses unplanned/accidental events.',
  },
  {
    id: 'pq-b1-13',
    level: 'B1',
    difficulty: 3.3,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Mientras yo ___, empezó a llover. (caminar)',
    answer: 'caminaba',
    options: ['caminé', 'caminaba', 'camino', 'caminara'],
    explanation: 'The imperfect sets the background action interrupted by the preterite.',
  },
  {
    id: 'pq-b1-14',
    level: 'B1',
    difficulty: 3.3,
    domain: 'grammar',
    type: 'fib',
    prompt: 'El coche ___ reparado por el mecánico. (ser, preterite — passive voice)',
    answer: 'fue',
    options: null,
    explanation: 'Passive voice in the preterite: "fue reparado" (was repaired).',
  },
  {
    id: 'pq-b1-15',
    level: 'B1',
    difficulty: 3.3,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Darse cuenta de" means:',
    answer: 'to realize',
    options: ['to give an account', 'to take charge', 'to realize', 'to be careful'],
    explanation: '"Darse cuenta de" = "to realize / become aware of."',
  },
  {
    id: 'pq-b1-16',
    level: 'B1',
    difficulty: 3.4,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Le di el libro ___ ella. (direct + indirect object)',
    answer: 'a',
    options: ['a', 'para', 'por', 'con'],
    explanation: '"Dar algo a alguien" — "a" introduces the indirect object person.',
  },
  {
    id: 'pq-b1-17',
    level: 'B1',
    difficulty: 3.4,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Ya ___ he dicho muchas veces. (pronoun replacing "a ellos" + "eso")',
    answer: 'se lo',
    options: ['lo les', 'se lo', 'les lo', 'se le'],
    explanation: '"Se lo he dicho" — when le/les precedes lo/la, le becomes "se."',
  },
  {
    id: 'pq-b1-18',
    level: 'B1',
    difficulty: 3.4,
    domain: 'reading',
    type: 'mc',
    prompt: '"Pedro llegó tarde al trabajo porque se quedó dormido. Su jefe no estaba contento." Why was the boss unhappy?',
    answer: 'Pedro arrived late.',
    options: ['Pedro was sleeping at work.', 'Pedro arrived late.', 'Pedro quit his job.', 'Pedro was sick.'],
    explanation: 'Pedro was late because he overslept, which upset his boss.',
  },
  {
    id: 'pq-b1-19',
    level: 'B1',
    difficulty: 3.5,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Si tengo dinero, ___ un coche nuevo. (comprar)',
    answer: 'compraré',
    options: ['compraría', 'compraré', 'compre', 'comprara'],
    explanation: 'Real conditional (si + present, future): "Si tengo..., compraré."',
  },
  {
    id: 'pq-b1-20',
    level: 'B1',
    difficulty: 3.5,
    domain: 'usage',
    type: 'mc',
    prompt: '"Llevar" can mean many things. In "Llevo tres años aquí," it means:',
    answer: 'I have been here for three years.',
    options: ['I am carrying three years.', 'I took three years.', 'I have been here for three years.', 'I will be here for three years.'],
    explanation: '"Llevar" + time expression indicates duration: "I\'ve been here for..."',
  },

  // ──────────────────────────────────────────────────────────
  //  B2 — Upper Intermediate (difficulty 3.6–4.3)
  // ──────────────────────────────────────────────────────────

  {
    id: 'pq-b2-01',
    level: 'B2',
    difficulty: 3.6,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Si tuviera más tiempo, ___ al gimnasio. (ir)',
    answer: 'iría',
    options: ['voy', 'iré', 'iría', 'fuera'],
    explanation: 'Unreal conditional: si + imperfect subjunctive, conditional.',
  },
  {
    id: 'pq-b2-02',
    level: 'B2',
    difficulty: 3.6,
    domain: 'grammar',
    type: 'mc',
    prompt: 'No creo que él ___ razón. (tener)',
    answer: 'tenga',
    options: ['tiene', 'tenga', 'tuviera', 'tendrá'],
    explanation: '"No creer que" triggers the subjunctive: "tenga."',
  },
  {
    id: 'pq-b2-03',
    level: 'B2',
    difficulty: 3.7,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Busco una casa que ___ jardín. (tener, subjunctive)',
    answer: 'tenga',
    options: null,
    explanation: 'When the antecedent is indefinite/unknown, the subjunctive is used.',
  },
  {
    id: 'pq-b2-04',
    level: 'B2',
    difficulty: 3.7,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Aprovechar" most closely means:',
    answer: 'to take advantage of',
    options: ['to approve', 'to take advantage of', 'to approach', 'to appreciate'],
    explanation: '"Aprovechar" means "to make use of / take advantage of."',
  },
  {
    id: 'pq-b2-05',
    level: 'B2',
    difficulty: 3.8,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Te llamé para que ___ la noticia. (saber)',
    answer: 'supieras',
    options: ['sabes', 'sepas', 'supieras', 'sabrías'],
    explanation: '"Para que" + past context requires the imperfect subjunctive: "supieras."',
  },
  {
    id: 'pq-b2-06',
    level: 'B2',
    difficulty: 3.8,
    domain: 'usage',
    type: 'mc',
    prompt: '"Sino" vs. "si no": Ella no es doctora ___ enfermera.',
    answer: 'sino',
    options: ['si no', 'sino', 'pero', 'sin embargo'],
    explanation: '"Sino" is used after a negative to mean "but rather."',
  },
  {
    id: 'pq-b2-07',
    level: 'B2',
    difficulty: 3.8,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Cuando ___ a casa, te llamaré. (llegar)',
    answer: 'llegue',
    options: ['llego', 'llegue', 'llegaré', 'llegué'],
    explanation: '"Cuando" + future meaning requires the present subjunctive.',
  },
  {
    id: 'pq-b2-08',
    level: 'B2',
    difficulty: 3.9,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Ojalá ___ buen tiempo mañana. (hacer — él/ella, present subjunctive)',
    answer: 'haga',
    options: null,
    explanation: '"Ojalá" + present subjunctive for wishes about the future.',
  },
  {
    id: 'pq-b2-09',
    level: 'B2',
    difficulty: 3.9,
    domain: 'vocab',
    type: 'mc',
    prompt: '"No obstante" is closest in meaning to:',
    answer: 'nevertheless',
    options: ['as a result', 'in addition', 'nevertheless', 'for example'],
    explanation: '"No obstante" means "nevertheless / however."',
  },
  {
    id: 'pq-b2-10',
    level: 'B2',
    difficulty: 4.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Es importante que los estudiantes ___ sus tareas. (hacer)',
    answer: 'hagan',
    options: ['hacen', 'hagan', 'hicieran', 'harán'],
    explanation: '"Es importante que" requires the present subjunctive: "hagan."',
  },
  {
    id: 'pq-b2-11',
    level: 'B2',
    difficulty: 4.0,
    domain: 'reading',
    type: 'mc',
    prompt: '"A pesar de los avances tecnológicos, muchas comunidades rurales siguen sin acceso a internet de alta velocidad." The main idea is:',
    answer: 'Rural communities still lack high-speed internet despite technological progress.',
    options: ['Technology has solved rural connectivity.', 'Rural communities still lack high-speed internet despite technological progress.', 'High-speed internet is not important in rural areas.', 'Technological advances have been too slow.'],
    explanation: '"A pesar de" means "despite," and the sentence highlights a persistent gap.',
  },
  {
    id: 'pq-b2-12',
    level: 'B2',
    difficulty: 4.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'No me habría enterado de no ___ sido por tu mensaje. (haber — reduced conditional)',
    answer: 'haber',
    options: ['haber', 'haya', 'hubiera', 'habría'],
    explanation: '"De no haber sido" is a reduced conditional clause replacing "si no hubiera sido."',
  },
  {
    id: 'pq-b2-13',
    level: 'B2',
    difficulty: 4.1,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Ella habló como si ___ todo. (saber)',
    answer: 'supiera',
    options: ['sabe', 'sepa', 'supiera', 'sabría'],
    explanation: '"Como si" always requires the imperfect subjunctive: "supiera."',
  },
  {
    id: 'pq-b2-14',
    level: 'B2',
    difficulty: 4.1,
    domain: 'usage',
    type: 'fib',
    prompt: 'Estaba a punto de salir cuando ___ a llover. (empezar, preterite — perifrastic construction)',
    answer: 'empezó',
    options: null,
    explanation: '"Estar a punto de" + infinitive means "to be about to." The interrupting action uses the preterite.',
  },
  {
    id: 'pq-b2-15',
    level: 'B2',
    difficulty: 4.1,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Aportar" in the sentence "La investigación aportó datos nuevos" means:',
    answer: 'to contribute / to provide',
    options: ['to support', 'to contribute / to provide', 'to import', 'to report'],
    explanation: '"Aportar" means "to contribute" or "to provide."',
  },
  {
    id: 'pq-b2-16',
    level: 'B2',
    difficulty: 4.2,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Select the correct sentence:',
    answer: 'Le pedí que viniera a la fiesta.',
    options: ['Le pedí que viene a la fiesta.', 'Le pedí que venía a la fiesta.', 'Le pedí que viniera a la fiesta.', 'Le pedí que vendrá a la fiesta.'],
    explanation: '"Pedir que" in the past triggers the imperfect subjunctive: "viniera."',
  },
  {
    id: 'pq-b2-17',
    level: 'B2',
    difficulty: 4.2,
    domain: 'grammar',
    type: 'mc',
    prompt: 'La mujer ___ hijos estudian aquí es mi vecina. (relative pronoun)',
    answer: 'cuyos',
    options: ['que sus', 'cuyos', 'de quien', 'los cuales'],
    explanation: '"Cuyos" is the possessive relative pronoun agreeing with "hijos."',
  },
  {
    id: 'pq-b2-18',
    level: 'B2',
    difficulty: 4.2,
    domain: 'usage',
    type: 'mc',
    prompt: '"Tomar el pelo" means:',
    answer: 'to pull someone\'s leg / to joke with someone',
    options: ['to take hair', 'to pull someone\'s leg / to joke with someone', 'to grab someone', 'to bother someone'],
    explanation: '"Tomar el pelo" is an idiom meaning "to joke with / tease someone."',
  },
  {
    id: 'pq-b2-19',
    level: 'B2',
    difficulty: 4.3,
    domain: 'grammar',
    type: 'fib',
    prompt: 'No habría venido si lo ___ sabido. (haber, pluperfect subjunctive)',
    answer: 'hubiera',
    options: null,
    explanation: 'Conditional perfect + pluperfect subjunctive: "si lo hubiera sabido."',
  },
  {
    id: 'pq-b2-20',
    level: 'B2',
    difficulty: 4.3,
    domain: 'reading',
    type: 'mc',
    prompt: '"El profesor insistió en que los alumnos entregaran el trabajo antes del viernes, aunque varios protestaron alegando que el plazo era insuficiente." The students protested because:',
    answer: 'They felt the deadline was too short.',
    options: ['They did not want to do the assignment.', 'They felt the deadline was too short.', 'The professor was unfair to them.', 'They had already submitted the work.'],
    explanation: '"Alegando que el plazo era insuficiente" = claiming the deadline was insufficient.',
  },

  // ──────────────────────────────────────────────────────────
  //  C1 — Advanced (difficulty 4.4–5.2)
  // ──────────────────────────────────────────────────────────

  {
    id: 'pq-c1-01',
    level: 'C1',
    difficulty: 4.4,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Si hubiera estudiado más, ___ el examen. (aprobar)',
    answer: 'habría aprobado',
    options: ['aprobé', 'habría aprobado', 'haya aprobado', 'aprobaría'],
    explanation: 'Contrary-to-fact past: si + pluperfect subjunctive, conditional perfect ("habría aprobado").',
  },
  {
    id: 'pq-c1-02',
    level: 'C1',
    difficulty: 4.4,
    domain: 'grammar',
    type: 'mc',
    prompt: 'No es que no ___ ayudarte, es que no puedo. (querer)',
    answer: 'quiera',
    options: ['quiero', 'quiera', 'quisiera', 'querré'],
    explanation: '"No es que" triggers the subjunctive: "No es que no quiera."',
  },
  {
    id: 'pq-c1-03',
    level: 'C1',
    difficulty: 4.5,
    domain: 'grammar',
    type: 'mc',
    prompt: 'El edificio, ___ fachada fue restaurada el año pasado, es del siglo XVIII.',
    answer: 'cuya',
    options: ['que su', 'cuya', 'la cual', 'de quien'],
    explanation: '"Cuya" agrees with "fachada" (feminine singular), not with "edificio."',
  },
  {
    id: 'pq-c1-04',
    level: 'C1',
    difficulty: 4.5,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Soslayar" means:',
    answer: 'to avoid or sidestep (an issue)',
    options: ['to support', 'to undermine', 'to avoid or sidestep (an issue)', 'to observe carefully'],
    explanation: '"Soslayar" means to dodge, avoid, or sidestep a problem or topic.',
  },
  {
    id: 'pq-c1-05',
    level: 'C1',
    difficulty: 4.6,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Dudo que ellos ___ llegado a tiempo ayer. (haber, perfect subjunctive)',
    answer: 'hayan',
    options: null,
    explanation: '"Dudar que" + present perfect subjunctive: "hayan llegado."',
  },
  {
    id: 'pq-c1-06',
    level: 'C1',
    difficulty: 4.6,
    domain: 'usage',
    type: 'mc',
    prompt: 'Which register is appropriate for addressing a judge in a formal Spanish letter?',
    answer: 'Su Señoría',
    options: ['Estimado señor', 'Su Señoría', 'Querido juez', 'Hola, juez'],
    explanation: '"Su Señoría" is the formal form of address for a judge in Spanish.',
  },
  {
    id: 'pq-c1-07',
    level: 'C1',
    difficulty: 4.7,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Identify the error: "Ojalá que tuviera más tiempo ayer para terminar el proyecto."',
    answer: '"tuviera" should be "hubiera tenido" (past unrealized wish)',
    options: ['"Ojalá" should not be followed by "que"', '"tuviera" should be "hubiera tenido" (past unrealized wish)', '"ayer" should be "el día anterior"', 'There is no error.'],
    explanation: 'For a past unrealized wish, the pluperfect subjunctive is needed.',
  },
  {
    id: 'pq-c1-08',
    level: 'C1',
    difficulty: 4.7,
    domain: 'grammar',
    type: 'mc',
    prompt: 'El artículo, según ___ el autor explica su teoría, fue publicado en 2020.',
    answer: 'el cual',
    options: ['que', 'el cual', 'quien', 'cuyo'],
    explanation: 'After prepositions like "según," the pronoun "el cual" is preferred.',
  },
  {
    id: 'pq-c1-09',
    level: 'C1',
    difficulty: 4.8,
    domain: 'vocab',
    type: 'mc',
    prompt: '"La ponencia abordó cuestiones acuciantes." "Acuciantes" means:',
    answer: 'pressing / urgent',
    options: ['interesting', 'irrelevant', 'pressing / urgent', 'controversial'],
    explanation: '"Acuciante" means pressing, urgent, requiring immediate attention.',
  },
  {
    id: 'pq-c1-10',
    level: 'C1',
    difficulty: 4.8,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Por mucho que ___, no lograrás convencerlo. (insistir)',
    answer: 'insistas',
    options: ['insistes', 'insistas', 'insistieras', 'insistirás'],
    explanation: '"Por mucho que" + present subjunctive for concessive clauses about the present.',
  },
  {
    id: 'pq-c1-11',
    level: 'C1',
    difficulty: 4.8,
    domain: 'usage',
    type: 'mc',
    prompt: '"No dar pie con bola" means:',
    answer: 'to get everything wrong / to be unable to do anything right',
    options: ['to not kick a ball', 'to get everything wrong / to be unable to do anything right', 'to not have a leg to stand on', 'to not find what you are looking for'],
    explanation: '"No dar pie con bola" is an idiom meaning to be unable to do anything right.',
  },
  {
    id: 'pq-c1-12',
    level: 'C1',
    difficulty: 4.9,
    domain: 'grammar',
    type: 'fib',
    prompt: 'De ___ sabido la verdad, no habría aceptado. (complete the reduced conditional clause)',
    answer: 'haber',
    options: null,
    explanation: '"De haber sabido" replaces "Si hubiera sabido" in formal register.',
  },
  {
    id: 'pq-c1-13',
    level: 'C1',
    difficulty: 4.9,
    domain: 'reading',
    type: 'mc',
    prompt: '"Si bien es cierto que la globalización ha traído beneficios económicos, no se pueden soslayar las consecuencias medioambientales que conlleva." The author\'s stance is:',
    answer: 'Globalization has economic benefits but also environmental costs that must not be ignored.',
    options: ['Globalization is entirely positive.', 'Globalization has economic benefits but also environmental costs that must not be ignored.', 'Environmental consequences outweigh all benefits.', 'The economic benefits are uncertain.'],
    explanation: '"Si bien" introduces a concession; "no se pueden soslayar" stresses unavoidable consequences.',
  },
  {
    id: 'pq-c1-14',
    level: 'C1',
    difficulty: 5.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Select the correct sentence:',
    answer: 'Le rogué que no se lo dijera a nadie.',
    options: ['Le rogué que no se lo dice a nadie.', 'Le rogué que no se lo dijera a nadie.', 'Le rogué que no se lo dijo a nadie.', 'Le rogué que no se lo diría a nadie.'],
    explanation: '"Rogar que" in the past requires the imperfect subjunctive: "dijera."',
  },
  {
    id: 'pq-c1-15',
    level: 'C1',
    difficulty: 5.0,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Escueto" means:',
    answer: 'brief / concise / terse',
    options: ['hidden', 'elaborate', 'brief / concise / terse', 'skeptical'],
    explanation: '"Escueto" describes something brief and to the point, without detail.',
  },
  {
    id: 'pq-c1-16',
    level: 'C1',
    difficulty: 5.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Quienquiera que ___ responsable, deberá pagar los daños.',
    answer: 'sea',
    options: ['es', 'sea', 'fuera', 'será'],
    explanation: '"Quienquiera que" requires the subjunctive: "sea."',
  },
  {
    id: 'pq-c1-17',
    level: 'C1',
    difficulty: 5.1,
    domain: 'usage',
    type: 'mc',
    prompt: 'In formal academic writing, which connector best introduces a direct counterargument to the preceding claim?',
    answer: 'Sin embargo',
    options: ['No obstante', 'Sin embargo', 'Ahora bien', 'En cambio'],
    explanation: '"Sin embargo" directly counters the prior claim. "No obstante" concedes then continues; "ahora bien" shifts focus; "en cambio" contrasts two different items.',
  },
  {
    id: 'pq-c1-18',
    level: 'C1',
    difficulty: 5.1,
    domain: 'grammar',
    type: 'fib',
    prompt: 'A menos que ___ una solución pronto, el proyecto fracasará. (encontrar, nosotros)',
    answer: 'encontremos',
    options: null,
    explanation: '"A menos que" requires the present subjunctive: "encontremos."',
  },
  {
    id: 'pq-c1-19',
    level: 'C1',
    difficulty: 5.2,
    domain: 'reading',
    type: 'mc',
    prompt: '"En aras de fomentar una convivencia pacífica, resulta imprescindible que los ciudadanos asuman un compromiso activo con el diálogo intercultural." "En aras de" means:',
    answer: 'for the sake of / in pursuit of',
    options: ['because of', 'in spite of', 'for the sake of / in pursuit of', 'instead of'],
    explanation: '"En aras de" is a formal expression meaning "for the sake of."',
  },
  {
    id: 'pq-c1-20',
    level: 'C1',
    difficulty: 5.2,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Identify the error: "Me alegro de que hayas podido venir y que pasaste un buen rato."',
    answer: '"pasaste" should be "pasaras" or "hayas pasado" (subjunctive must continue)',
    options: ['"hayas" should be "has"', '"pasaste" should be "pasaras" or "hayas pasado" (subjunctive must continue)', '"de que" should be just "que"', 'There is no error.'],
    explanation: 'After "alegrarse de que," both clauses need the subjunctive.',
  },

  // ──────────────────────────────────────────────────────────
  //  C2 — Mastery (difficulty 5.3–6.5)
  // ──────────────────────────────────────────────────────────

  {
    id: 'pq-c2-01',
    level: 'C2',
    difficulty: 5.3,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Si no hubiera sido por tu ayuda, no ___ sobrevivido. Which option is ONLY acceptable in the main clause (apódosis), not the si-clause?',
    answer: 'habría',
    options: ['habría', 'hubiera', 'hubiese', 'habiendo'],
    explanation: '"Habría" (conditional) can only appear in the main clause. "Hubiera/hubiese" can appear in either clause, making "habría" the unique apódosis marker.',
  },
  {
    id: 'pq-c2-02',
    level: 'C2',
    difficulty: 5.3,
    domain: 'vocab',
    type: 'mc',
    prompt: '"Desdeñar" means:',
    answer: 'to scorn / to disdain',
    options: ['to untangle', 'to desire', 'to scorn / to disdain', 'to dismiss from a job'],
    explanation: '"Desdeñar" means to treat with contempt, to scorn.',
  },
  {
    id: 'pq-c2-03',
    level: 'C2',
    difficulty: 5.4,
    domain: 'grammar',
    type: 'mc',
    prompt: '"Comoquiera que se analice el problema, la conclusión es la misma." "Comoquiera que" here means:',
    answer: 'However / No matter how',
    options: ['Because', 'However / No matter how', 'As if', 'Whenever'],
    explanation: '"Comoquiera que" + subjunctive means "however" or "no matter how."',
  },
  {
    id: 'pq-c2-04',
    level: 'C2',
    difficulty: 5.4,
    domain: 'usage',
    type: 'mc',
    prompt: 'The proverb "En boca cerrada no entran moscas" advises:',
    answer: 'It is better to keep quiet than to say something you will regret.',
    options: ['Good hygiene is important.', 'Silence is not always golden.', 'It is better to keep quiet than to say something you will regret.', 'Actions speak louder than words.'],
    explanation: 'This proverb literally says "flies don\'t enter a closed mouth" — advising prudent silence.',
  },
  {
    id: 'pq-c2-05',
    level: 'C2',
    difficulty: 5.5,
    domain: 'grammar',
    type: 'fib',
    prompt: 'El contrato será válido siempre y cuando ambas partes lo ___ firmado antes del plazo. (haber)',
    answer: 'hayan',
    options: null,
    explanation: '"Siempre y cuando" requires the subjunctive; perfect subjunctive for completed action: "hayan firmado."',
  },
  {
    id: 'pq-c2-06',
    level: 'C2',
    difficulty: 5.5,
    domain: 'vocab',
    type: 'mc',
    prompt: '"El discurso del político estaba plagado de circunloquios." "Circunloquios" are:',
    answer: 'roundabout or evasive expressions',
    options: ['circular arguments', 'roundabout or evasive expressions', 'logical fallacies', 'rhetorical questions'],
    explanation: '"Circunloquio" means circumlocution — using many words to avoid directness.',
  },
  {
    id: 'pq-c2-07',
    level: 'C2',
    difficulty: 5.6,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Identify the error: "El diputado, quien discurso fue interrumpido varias veces, exigió orden en la sala."',
    answer: '"quien" should be "cuyo" (possessive relative pronoun needed)',
    options: ['"fue" should be "fuera"', '"quien" should be "cuyo" (possessive relative pronoun needed)', '"exigió" should be "exigiera"', 'There is no error.'],
    explanation: '"Cuyo" is the possessive relative pronoun: "cuyo discurso" (whose speech).',
  },
  {
    id: 'pq-c2-08',
    level: 'C2',
    difficulty: 5.6,
    domain: 'reading',
    type: 'mc',
    prompt: '"La disyuntiva entre el crecimiento económico y la preservación del patrimonio cultural no debería plantearse en términos excluyentes, sino más bien como un binomio indisoluble cuya gestión requiere voluntad política y sensibilidad social." The author argues that:',
    answer: 'Economic growth and cultural preservation should be treated as inseparable, not as mutually exclusive.',
    options: ['Economic growth must always come first.', 'Cultural preservation should override economics.', 'Economic growth and cultural preservation should be treated as inseparable, not as mutually exclusive.', 'Neither economic growth nor cultural preservation is possible without foreign aid.'],
    explanation: '"Binomio indisoluble" = inseparable pair; "no en términos excluyentes" = not mutually exclusive.',
  },
  {
    id: 'pq-c2-09',
    level: 'C2',
    difficulty: 5.7,
    domain: 'grammar',
    type: 'mc',
    prompt: '"Hubiere lo que hubiere, seguiremos adelante." This use of the future subjunctive indicates:',
    answer: 'An archaic/legal/literary form meaning "whatever there may be"',
    options: ['A grammatical error that should use the present subjunctive', 'An archaic/legal/literary form meaning "whatever there may be"', 'A regional dialectal form', 'The conditional perfect tense'],
    explanation: 'The future subjunctive ("hubiere") survives in legal texts, proverbs, and some fixed expressions.',
  },
  {
    id: 'pq-c2-10',
    level: 'C2',
    difficulty: 5.7,
    domain: 'vocab',
    type: 'fib',
    prompt: '"Hablaba con gran ___ sobre temas de los que sabía muy poco." (word meaning "nerve / audacity," starts with "d")',
    answer: 'desparpajo',
    options: null,
    explanation: '"Desparpajo" means nerve, brazenness, or audacious ease.',
  },
  {
    id: 'pq-c2-11',
    level: 'C2',
    difficulty: 5.8,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Complete: "No bien ___ la puerta, sonó el teléfono." (abrir, yo)',
    answer: 'hube abierto',
    options: ['abrí', 'había abierto', 'hube abierto', 'abriera'],
    explanation: '"No bien" + preterite anterior ("hube abierto") indicates immediate succession in literary register.',
  },
  {
    id: 'pq-c2-12',
    level: 'C2',
    difficulty: 5.8,
    domain: 'usage',
    type: 'mc',
    prompt: 'Which sentence correctly uses "de" before "que"? (dequeísmo vs. correct usage)',
    answer: 'Me alegro de que hayas venido.',
    options: ['Pienso de que es correcto.', 'Me alegro de que hayas venido.', 'Creo de que tiene razón.', 'Dice de que no puede venir.'],
    explanation: '"Alegrarse de que" requires "de" (it governs a prepositional complement). The others are dequeísmo errors.',
  },
  {
    id: 'pq-c2-13',
    level: 'C2',
    difficulty: 5.9,
    domain: 'grammar',
    type: 'mc',
    prompt: '"Dicho sea de paso, el informe adolece de rigor científico." "Adolecer de" means:',
    answer: 'to suffer from / to lack',
    options: ['to be adolescent about', 'to mature toward', 'to suffer from / to lack', 'to be grieved by'],
    explanation: '"Adolecer de" means "to suffer from a deficiency" — often confused with "carecer."',
  },
  {
    id: 'pq-c2-14',
    level: 'C2',
    difficulty: 5.9,
    domain: 'grammar',
    type: 'fib',
    prompt: 'Sea cual ___ su decisión, la respetaremos. (ser)',
    answer: 'fuere',
    options: null,
    explanation: '"Sea cual fuere" is the literary form of "whatever it may be," using the future subjunctive.',
  },
  {
    id: 'pq-c2-15',
    level: 'C2',
    difficulty: 6.0,
    domain: 'reading',
    type: 'mc',
    prompt: '"La hermenéutica del texto requiere que el lector no solo descodifique el significado literal, sino que también aprehenda las connotaciones implícitas que subyacen en el discurso." "Aprehender" here means:',
    answer: 'to grasp intellectually / to comprehend',
    options: ['to arrest', 'to fear', 'to grasp intellectually / to comprehend', 'to memorize'],
    explanation: '"Aprehender" (not "aprender") means to grasp or seize mentally — a literary/academic word.',
  },
  {
    id: 'pq-c2-16',
    level: 'C2',
    difficulty: 6.0,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Identify the error: "Habrían habido muchas quejas si no hubiéramos actuado a tiempo."',
    answer: '"Habrían habido" should be "Habría habido" (haber is impersonal, always singular)',
    options: ['"hubiéramos" should be "habríamos"', '"Habrían habido" should be "Habría habido" (haber is impersonal, always singular)', '"muchas" should be "mucho"', 'There is no error.'],
    explanation: 'Impersonal "haber" is always singular: "habría habido," never "habrían habido."',
  },
  {
    id: 'pq-c2-17',
    level: 'C2',
    difficulty: 6.1,
    domain: 'usage',
    type: 'mc',
    prompt: '"Dar gato por liebre" means:',
    answer: 'to deceive someone by passing off something inferior as something better',
    options: ['to give a cat instead of a rabbit', 'to make a poor exchange', 'to deceive someone by passing off something inferior as something better', 'to make an honest mistake'],
    explanation: 'This idiom means to cheat someone by substituting something inferior.',
  },
  {
    id: 'pq-c2-18',
    level: 'C2',
    difficulty: 6.2,
    domain: 'grammar',
    type: 'mc',
    prompt: '"Con ser tan inteligente, no supo resolver el problema." "Con" + infinitive here expresses:',
    answer: 'concession (despite being so intelligent)',
    options: ['cause (because of being intelligent)', 'concession (despite being so intelligent)', 'condition (if he were intelligent)', 'manner (by being intelligent)'],
    explanation: '"Con" + infinitive in this construction expresses concession: "despite."',
  },
  {
    id: 'pq-c2-19',
    level: 'C2',
    difficulty: 6.3,
    domain: 'reading',
    type: 'mc',
    prompt: '"La obsolescencia programada, lejos de ser un mero artilugio mercantil, se erige como un paradigma que cuestiona los cimientos mismos de la sostenibilidad. Empero, las voces disonantes que abogan por una economía circular van cobrando una relevancia inusitada." "Empero" functions as:',
    answer: 'a formal/literary synonym of "sin embargo" (however)',
    options: ['a causal conjunction (therefore)', 'a formal/literary synonym of "sin embargo" (however)', 'a temporal conjunction (meanwhile)', 'an emphatic particle (indeed)'],
    explanation: '"Empero" is an archaic/literary word meaning "however" or "nevertheless."',
  },
  {
    id: 'pq-c2-20',
    level: 'C2',
    difficulty: 6.5,
    domain: 'grammar',
    type: 'mc',
    prompt: 'Which sentence is grammatically impeccable?',
    answer: 'De haberlo sabido, no me habría comprometido a asistir a la reunión, cuya fecha, dicho sea de paso, aún no se ha confirmado.',
    options: [
      'Si lo habría sabido, no me comprometía a asistir a la reunión, que su fecha aún no se ha confirmado.',
      'De haberlo sabido, no me habría comprometido a asistir a la reunión, cuya fecha, dicho sea de paso, aún no se ha confirmado.',
      'Si lo hubiera sabido, no me hubiera comprometido a asistir a la reunión, quien fecha aún no se ha confirmado.',
      'De haberlo sabido, no me habría comprometido a asistir la reunión, cuya fecha, dicho sea de paso, aún no se ha confirmado.',
    ],
    explanation: 'Only this option uses correct conditional structure, possessive relative "cuya," and the preposition "a" with "asistir."',
  },
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PLACEMENT_QUESTIONS };
}
