// Vocabulary Database — Lección Diaria
// Categories and 500+ initial vocabulary words

const VOCAB_CATEGORIES = {
  greetings: { title: 'Saludos', titleEn: 'Greetings', icon: '👋' },
  family: { title: 'Familia', titleEn: 'Family', icon: '👨‍👩‍👧‍👦' },
  food: { title: 'Comida', titleEn: 'Food', icon: '🍽️' },
  animals: { title: 'Animales', titleEn: 'Animals', icon: '🐾' },
  places: { title: 'Lugares', titleEn: 'Places', icon: '🏘️' },
  body: { title: 'Cuerpo', titleEn: 'Body', icon: '🦴' },
  clothing: { title: 'Ropa', titleEn: 'Clothing', icon: '👕' },
  professions: { title: 'Profesiones', titleEn: 'Professions', icon: '👷' },
  nature: { title: 'Naturaleza', titleEn: 'Nature', icon: '🌿' },
  emotions: { title: 'Emociones', titleEn: 'Emotions', icon: '😊' },
  colors: { title: 'Colores', titleEn: 'Colors', icon: '🎨' },
  numbers: { title: 'Números', titleEn: 'Numbers', icon: '🔢' },
  time: { title: 'Tiempo', titleEn: 'Time', icon: '🕐' },
  weather: { title: 'Clima', titleEn: 'Weather', icon: '🌤️' },
  travel: { title: 'Viajes', titleEn: 'Travel', icon: '✈️' },
  technology: { title: 'Tecnología', titleEn: 'Technology', icon: '💻' },
  house: { title: 'Hogar', titleEn: 'House', icon: '🏠' },
  school: { title: 'Escuela', titleEn: 'School', icon: '📚' },
  health: { title: 'Salud', titleEn: 'Health', icon: '🏥' },
  sports: { title: 'Deportes', titleEn: 'Sports', icon: '⚽' },
  adjectives: { title: 'Adjetivos', titleEn: 'Adjectives', icon: '📝' },
  adverbs: { title: 'Adverbios', titleEn: 'Adverbs', icon: '⏩' },
  prepositions: { title: 'Preposiciones', titleEn: 'Prepositions', icon: '↔️' },
  conjunctions: { title: 'Conjunciones', titleEn: 'Conjunctions', icon: '🔗' },
  pronouns: { title: 'Pronombres', titleEn: 'Pronouns', icon: '👤' },
};

const VOCAB_DATA = [
  // ── GREETINGS ──
  { word: 'hola', english: 'hello', category: 'greetings', pos: 'interjection', gender: null, example: '¡Hola! ¿Cómo estás?', exampleEn: 'Hello! How are you?', level: 'A1', freq: 1 },
  { word: 'adiós', english: 'goodbye', category: 'greetings', pos: 'interjection', gender: null, example: '¡Adiós! Nos vemos mañana.', exampleEn: 'Goodbye! See you tomorrow.', level: 'A1', freq: 1 },
  { word: 'buenos días', english: 'good morning', category: 'greetings', pos: 'phrase', gender: null, example: 'Buenos días, señora López.', exampleEn: 'Good morning, Mrs. López.', level: 'A1', freq: 1 },
  { word: 'buenas tardes', english: 'good afternoon', category: 'greetings', pos: 'phrase', gender: null, example: 'Buenas tardes a todos.', exampleEn: 'Good afternoon everyone.', level: 'A1', freq: 1 },
  { word: 'buenas noches', english: 'good evening, good night', category: 'greetings', pos: 'phrase', gender: null, example: 'Buenas noches, que descanses.', exampleEn: 'Good night, rest well.', level: 'A1', freq: 1 },
  { word: 'por favor', english: 'please', category: 'greetings', pos: 'phrase', gender: null, example: 'Un café, por favor.', exampleEn: 'A coffee, please.', level: 'A1', freq: 1 },
  { word: 'gracias', english: 'thank you', category: 'greetings', pos: 'interjection', gender: null, example: 'Muchas gracias por tu ayuda.', exampleEn: 'Thank you very much for your help.', level: 'A1', freq: 1 },
  { word: 'de nada', english: "you're welcome", category: 'greetings', pos: 'phrase', gender: null, example: '—Gracias. —De nada.', exampleEn: "—Thank you. —You're welcome.", level: 'A1', freq: 1 },
  { word: 'perdón', english: 'excuse me, sorry', category: 'greetings', pos: 'interjection', gender: null, example: 'Perdón, ¿puede repetir?', exampleEn: 'Excuse me, can you repeat?', level: 'A1', freq: 2 },
  { word: 'lo siento', english: "I'm sorry", category: 'greetings', pos: 'phrase', gender: null, example: 'Lo siento mucho.', exampleEn: "I'm very sorry.", level: 'A1', freq: 2 },
  { word: 'mucho gusto', english: 'nice to meet you', category: 'greetings', pos: 'phrase', gender: null, example: 'Mucho gusto, soy Carlos.', exampleEn: "Nice to meet you, I'm Carlos.", level: 'A1', freq: 1 },
  { word: 'hasta luego', english: 'see you later', category: 'greetings', pos: 'phrase', gender: null, example: 'Hasta luego, amigo.', exampleEn: 'See you later, friend.', level: 'A1', freq: 1 },
  { word: 'hasta mañana', english: 'see you tomorrow', category: 'greetings', pos: 'phrase', gender: null, example: 'Hasta mañana en clase.', exampleEn: 'See you tomorrow in class.', level: 'A1', freq: 1 },
  { word: '¿cómo estás?', english: 'how are you? (informal)', category: 'greetings', pos: 'phrase', gender: null, example: '¡Hola! ¿Cómo estás?', exampleEn: 'Hi! How are you?', level: 'A1', freq: 1 },
  { word: '¿qué tal?', english: "how's it going?", category: 'greetings', pos: 'phrase', gender: null, example: '¡Hola! ¿Qué tal?', exampleEn: "Hello! How's it going?", level: 'A1', freq: 1 },
  { word: 'bien', english: 'well, fine', category: 'greetings', pos: 'adverb', gender: null, example: 'Estoy bien, gracias.', exampleEn: "I'm fine, thanks.", level: 'A1', freq: 1 },
  { word: 'señor', english: 'Mr., sir', category: 'greetings', pos: 'noun', gender: 'm', example: 'Buenos días, señor García.', exampleEn: 'Good morning, Mr. García.', level: 'A1', freq: 1 },
  { word: 'señora', english: "Mrs., ma'am", category: 'greetings', pos: 'noun', gender: 'f', example: 'La señora está aquí.', exampleEn: 'The lady is here.', level: 'A1', freq: 1 },

  // ── FAMILY ──
  { word: 'madre', english: 'mother', category: 'family', pos: 'noun', gender: 'f', example: 'Mi madre cocina muy bien.', exampleEn: 'My mother cooks very well.', level: 'A1', freq: 1 },
  { word: 'padre', english: 'father', category: 'family', pos: 'noun', gender: 'm', example: 'Mi padre trabaja en un banco.', exampleEn: 'My father works in a bank.', level: 'A1', freq: 1 },
  { word: 'hijo', english: 'son', category: 'family', pos: 'noun', gender: 'm', example: 'Tengo un hijo de cinco años.', exampleEn: 'I have a five-year-old son.', level: 'A1', freq: 1 },
  { word: 'hija', english: 'daughter', category: 'family', pos: 'noun', gender: 'f', example: 'Mi hija estudia medicina.', exampleEn: 'My daughter studies medicine.', level: 'A1', freq: 1 },
  { word: 'hermano', english: 'brother', category: 'family', pos: 'noun', gender: 'm', example: 'Mi hermano vive en Madrid.', exampleEn: 'My brother lives in Madrid.', level: 'A1', freq: 1 },
  { word: 'hermana', english: 'sister', category: 'family', pos: 'noun', gender: 'f', example: 'Mi hermana es profesora.', exampleEn: 'My sister is a teacher.', level: 'A1', freq: 1 },
  { word: 'abuelo', english: 'grandfather', category: 'family', pos: 'noun', gender: 'm', example: 'Mi abuelo tiene ochenta años.', exampleEn: 'My grandfather is eighty years old.', level: 'A1', freq: 2 },
  { word: 'abuela', english: 'grandmother', category: 'family', pos: 'noun', gender: 'f', example: 'Mi abuela hace el mejor pastel.', exampleEn: 'My grandmother makes the best cake.', level: 'A1', freq: 2 },
  { word: 'tío', english: 'uncle', category: 'family', pos: 'noun', gender: 'm', example: 'Mi tío vive en Barcelona.', exampleEn: 'My uncle lives in Barcelona.', level: 'A1', freq: 2 },
  { word: 'tía', english: 'aunt', category: 'family', pos: 'noun', gender: 'f', example: 'Mi tía nos visita cada verano.', exampleEn: 'My aunt visits us every summer.', level: 'A1', freq: 2 },
  { word: 'primo', english: 'cousin (male)', category: 'family', pos: 'noun', gender: 'm', example: 'Mi primo juega al fútbol.', exampleEn: 'My cousin plays soccer.', level: 'A1', freq: 2 },
  { word: 'esposo', english: 'husband', category: 'family', pos: 'noun', gender: 'm', example: 'Mi esposo trabaja desde casa.', exampleEn: 'My husband works from home.', level: 'A1', freq: 2 },
  { word: 'esposa', english: 'wife', category: 'family', pos: 'noun', gender: 'f', example: 'Mi esposa es doctora.', exampleEn: 'My wife is a doctor.', level: 'A1', freq: 2 },
  { word: 'bebé', english: 'baby', category: 'family', pos: 'noun', gender: 'm', example: 'El bebé está durmiendo.', exampleEn: 'The baby is sleeping.', level: 'A1', freq: 2 },
  { word: 'familia', english: 'family', category: 'family', pos: 'noun', gender: 'f', example: 'Mi familia es muy grande.', exampleEn: 'My family is very big.', level: 'A1', freq: 1 },
  { word: 'niño', english: 'boy, child', category: 'family', pos: 'noun', gender: 'm', example: 'El niño juega en el parque.', exampleEn: 'The boy plays in the park.', level: 'A1', freq: 1 },
  { word: 'niña', english: 'girl', category: 'family', pos: 'noun', gender: 'f', example: 'La niña lee un libro.', exampleEn: 'The girl reads a book.', level: 'A1', freq: 1 },
  { word: 'hombre', english: 'man', category: 'family', pos: 'noun', gender: 'm', example: 'El hombre camina por la calle.', exampleEn: 'The man walks down the street.', level: 'A1', freq: 1 },
  { word: 'mujer', english: 'woman', category: 'family', pos: 'noun', gender: 'f', example: 'La mujer trabaja en el hospital.', exampleEn: 'The woman works at the hospital.', level: 'A1', freq: 1 },
  { word: 'novio', english: 'boyfriend', category: 'family', pos: 'noun', gender: 'm', example: 'Mi novio me invitó a cenar.', exampleEn: 'My boyfriend invited me to dinner.', level: 'A2', freq: 2 },
  { word: 'novia', english: 'girlfriend', category: 'family', pos: 'noun', gender: 'f', example: 'Su novia es muy simpática.', exampleEn: 'His girlfriend is very nice.', level: 'A2', freq: 2 },

  // ── FOOD ──
  { word: 'agua', english: 'water', category: 'food', pos: 'noun', gender: 'f', example: 'Un vaso de agua, por favor.', exampleEn: 'A glass of water, please.', level: 'A1', freq: 1 },
  { word: 'pan', english: 'bread', category: 'food', pos: 'noun', gender: 'm', example: 'Compré pan fresco.', exampleEn: 'I bought fresh bread.', level: 'A1', freq: 1 },
  { word: 'leche', english: 'milk', category: 'food', pos: 'noun', gender: 'f', example: 'Me gusta la leche con café.', exampleEn: 'I like milk with coffee.', level: 'A1', freq: 1 },
  { word: 'arroz', english: 'rice', category: 'food', pos: 'noun', gender: 'm', example: 'El arroz con pollo es delicioso.', exampleEn: 'Rice with chicken is delicious.', level: 'A1', freq: 2 },
  { word: 'carne', english: 'meat', category: 'food', pos: 'noun', gender: 'f', example: 'No como carne.', exampleEn: "I don't eat meat.", level: 'A1', freq: 1 },
  { word: 'pollo', english: 'chicken', category: 'food', pos: 'noun', gender: 'm', example: 'El pollo asado está listo.', exampleEn: 'The roasted chicken is ready.', level: 'A1', freq: 1 },
  { word: 'pescado', english: 'fish', category: 'food', pos: 'noun', gender: 'm', example: 'El pescado es muy fresco.', exampleEn: 'The fish is very fresh.', level: 'A1', freq: 2 },
  { word: 'huevo', english: 'egg', category: 'food', pos: 'noun', gender: 'm', example: 'Quiero dos huevos fritos.', exampleEn: 'I want two fried eggs.', level: 'A1', freq: 1 },
  { word: 'queso', english: 'cheese', category: 'food', pos: 'noun', gender: 'm', example: 'Me encanta el queso manchego.', exampleEn: 'I love manchego cheese.', level: 'A1', freq: 2 },
  { word: 'fruta', english: 'fruit', category: 'food', pos: 'noun', gender: 'f', example: 'Como fruta todos los días.', exampleEn: 'I eat fruit every day.', level: 'A1', freq: 1 },
  { word: 'manzana', english: 'apple', category: 'food', pos: 'noun', gender: 'f', example: 'La manzana es roja.', exampleEn: 'The apple is red.', level: 'A1', freq: 2 },
  { word: 'naranja', english: 'orange', category: 'food', pos: 'noun', gender: 'f', example: 'Quiero jugo de naranja.', exampleEn: 'I want orange juice.', level: 'A1', freq: 2 },
  { word: 'plátano', english: 'banana', category: 'food', pos: 'noun', gender: 'm', example: 'El plátano es amarillo.', exampleEn: 'The banana is yellow.', level: 'A1', freq: 2 },
  { word: 'verdura', english: 'vegetable', category: 'food', pos: 'noun', gender: 'f', example: 'Las verduras son buenas para la salud.', exampleEn: 'Vegetables are good for health.', level: 'A1', freq: 2 },
  { word: 'tomate', english: 'tomato', category: 'food', pos: 'noun', gender: 'm', example: 'Necesito tomates para la ensalada.', exampleEn: 'I need tomatoes for the salad.', level: 'A1', freq: 2 },
  { word: 'ensalada', english: 'salad', category: 'food', pos: 'noun', gender: 'f', example: 'Una ensalada mixta, por favor.', exampleEn: 'A mixed salad, please.', level: 'A1', freq: 2 },
  { word: 'sopa', english: 'soup', category: 'food', pos: 'noun', gender: 'f', example: 'La sopa está caliente.', exampleEn: 'The soup is hot.', level: 'A1', freq: 2 },
  { word: 'café', english: 'coffee', category: 'food', pos: 'noun', gender: 'm', example: 'Tomo café por la mañana.', exampleEn: 'I drink coffee in the morning.', level: 'A1', freq: 1 },
  { word: 'cerveza', english: 'beer', category: 'food', pos: 'noun', gender: 'f', example: 'Una cerveza fría, por favor.', exampleEn: 'A cold beer, please.', level: 'A1', freq: 2 },
  { word: 'vino', english: 'wine', category: 'food', pos: 'noun', gender: 'm', example: 'El vino tinto es de España.', exampleEn: 'The red wine is from Spain.', level: 'A1', freq: 2 },
  { word: 'azúcar', english: 'sugar', category: 'food', pos: 'noun', gender: 'm', example: '¿Quieres azúcar en el café?', exampleEn: 'Do you want sugar in your coffee?', level: 'A1', freq: 2 },
  { word: 'sal', english: 'salt', category: 'food', pos: 'noun', gender: 'f', example: 'Pásame la sal, por favor.', exampleEn: 'Pass me the salt, please.', level: 'A1', freq: 2 },
  { word: 'pimienta', english: 'pepper', category: 'food', pos: 'noun', gender: 'f', example: '¿Quieres pimienta?', exampleEn: 'Do you want pepper?', level: 'A2', freq: 3 },
  { word: 'postre', english: 'dessert', category: 'food', pos: 'noun', gender: 'm', example: '¿Qué hay de postre?', exampleEn: 'What is for dessert?', level: 'A2', freq: 3 },
  { word: 'helado', english: 'ice cream', category: 'food', pos: 'noun', gender: 'm', example: 'Quiero un helado de chocolate.', exampleEn: 'I want a chocolate ice cream.', level: 'A1', freq: 2 },
  { word: 'cebolla', english: 'onion', category: 'food', pos: 'noun', gender: 'f', example: 'La cebolla me hace llorar.', exampleEn: 'The onion makes me cry.', level: 'A2', freq: 3 },
  { word: 'ajo', english: 'garlic', category: 'food', pos: 'noun', gender: 'm', example: 'El ajo da mucho sabor.', exampleEn: 'Garlic gives a lot of flavor.', level: 'A2', freq: 3 },
  { word: 'papa', english: 'potato', category: 'food', pos: 'noun', gender: 'f', example: 'Las papas fritas son ricas.', exampleEn: 'French fries are tasty.', level: 'A1', freq: 2 },
  { word: 'frijol', english: 'bean', category: 'food', pos: 'noun', gender: 'm', example: 'Los frijoles negros son típicos.', exampleEn: 'Black beans are typical.', level: 'A2', freq: 3 },
  { word: 'maíz', english: 'corn', category: 'food', pos: 'noun', gender: 'm', example: 'Las tortillas son de maíz.', exampleEn: 'The tortillas are made of corn.', level: 'A2', freq: 3 },

  // ── ANIMALS ──
  { word: 'perro', english: 'dog', category: 'animals', pos: 'noun', gender: 'm', example: 'El perro corre en el parque.', exampleEn: 'The dog runs in the park.', level: 'A1', freq: 1 },
  { word: 'gato', english: 'cat', category: 'animals', pos: 'noun', gender: 'm', example: 'El gato duerme en el sofá.', exampleEn: 'The cat sleeps on the sofa.', level: 'A1', freq: 1 },
  { word: 'pájaro', english: 'bird', category: 'animals', pos: 'noun', gender: 'm', example: 'El pájaro canta por la mañana.', exampleEn: 'The bird sings in the morning.', level: 'A1', freq: 2 },
  { word: 'pez', english: 'fish (live)', category: 'animals', pos: 'noun', gender: 'm', example: 'El pez nada en el río.', exampleEn: 'The fish swims in the river.', level: 'A1', freq: 2 },
  { word: 'caballo', english: 'horse', category: 'animals', pos: 'noun', gender: 'm', example: 'El caballo corre rápido.', exampleEn: 'The horse runs fast.', level: 'A1', freq: 2 },
  { word: 'vaca', english: 'cow', category: 'animals', pos: 'noun', gender: 'f', example: 'La vaca produce leche.', exampleEn: 'The cow produces milk.', level: 'A1', freq: 2 },
  { word: 'cerdo', english: 'pig', category: 'animals', pos: 'noun', gender: 'm', example: 'El cerdo vive en la granja.', exampleEn: 'The pig lives on the farm.', level: 'A2', freq: 3 },
  { word: 'gallina', english: 'hen', category: 'animals', pos: 'noun', gender: 'f', example: 'La gallina puso un huevo.', exampleEn: 'The hen laid an egg.', level: 'A2', freq: 3 },
  { word: 'oveja', english: 'sheep', category: 'animals', pos: 'noun', gender: 'f', example: 'Las ovejas están en el campo.', exampleEn: 'The sheep are in the field.', level: 'A2', freq: 3 },
  { word: 'mariposa', english: 'butterfly', category: 'animals', pos: 'noun', gender: 'f', example: 'La mariposa es de colores.', exampleEn: 'The butterfly is colorful.', level: 'A2', freq: 3 },
  { word: 'tortuga', english: 'turtle', category: 'animals', pos: 'noun', gender: 'f', example: 'La tortuga camina lento.', exampleEn: 'The turtle walks slowly.', level: 'A2', freq: 3 },
  { word: 'león', english: 'lion', category: 'animals', pos: 'noun', gender: 'm', example: 'El león es el rey de la selva.', exampleEn: 'The lion is the king of the jungle.', level: 'A2', freq: 3 },
  { word: 'mono', english: 'monkey', category: 'animals', pos: 'noun', gender: 'm', example: 'El mono come plátanos.', exampleEn: 'The monkey eats bananas.', level: 'A2', freq: 3 },
  { word: 'serpiente', english: 'snake', category: 'animals', pos: 'noun', gender: 'f', example: 'La serpiente es peligrosa.', exampleEn: 'The snake is dangerous.', level: 'A2', freq: 3 },
  { word: 'elefante', english: 'elephant', category: 'animals', pos: 'noun', gender: 'm', example: 'El elefante es muy grande.', exampleEn: 'The elephant is very big.', level: 'A2', freq: 3 },

  // ── PLACES ──
  { word: 'casa', english: 'house, home', category: 'places', pos: 'noun', gender: 'f', example: 'Vivo en una casa grande.', exampleEn: 'I live in a big house.', level: 'A1', freq: 1 },
  { word: 'escuela', english: 'school', category: 'places', pos: 'noun', gender: 'f', example: 'Los niños van a la escuela.', exampleEn: 'The children go to school.', level: 'A1', freq: 1 },
  { word: 'hospital', english: 'hospital', category: 'places', pos: 'noun', gender: 'm', example: 'El hospital está cerca.', exampleEn: 'The hospital is nearby.', level: 'A1', freq: 2 },
  { word: 'banco', english: 'bank', category: 'places', pos: 'noun', gender: 'm', example: 'Voy al banco a sacar dinero.', exampleEn: "I'm going to the bank to withdraw money.", level: 'A1', freq: 2 },
  { word: 'restaurante', english: 'restaurant', category: 'places', pos: 'noun', gender: 'm', example: 'El restaurante es muy bueno.', exampleEn: 'The restaurant is very good.', level: 'A1', freq: 1 },
  { word: 'tienda', english: 'store, shop', category: 'places', pos: 'noun', gender: 'f', example: 'La tienda abre a las nueve.', exampleEn: 'The store opens at nine.', level: 'A1', freq: 1 },
  { word: 'mercado', english: 'market', category: 'places', pos: 'noun', gender: 'm', example: 'Compro frutas en el mercado.', exampleEn: 'I buy fruit at the market.', level: 'A1', freq: 2 },
  { word: 'iglesia', english: 'church', category: 'places', pos: 'noun', gender: 'f', example: 'La iglesia es muy antigua.', exampleEn: 'The church is very old.', level: 'A2', freq: 3 },
  { word: 'parque', english: 'park', category: 'places', pos: 'noun', gender: 'm', example: 'Caminamos por el parque.', exampleEn: 'We walk through the park.', level: 'A1', freq: 1 },
  { word: 'playa', english: 'beach', category: 'places', pos: 'noun', gender: 'f', example: 'Vamos a la playa mañana.', exampleEn: "We're going to the beach tomorrow.", level: 'A1', freq: 2 },
  { word: 'museo', english: 'museum', category: 'places', pos: 'noun', gender: 'm', example: 'El museo de arte es excelente.', exampleEn: 'The art museum is excellent.', level: 'A2', freq: 3 },
  { word: 'biblioteca', english: 'library', category: 'places', pos: 'noun', gender: 'f', example: 'Estudio en la biblioteca.', exampleEn: 'I study at the library.', level: 'A2', freq: 3 },
  { word: 'aeropuerto', english: 'airport', category: 'places', pos: 'noun', gender: 'm', example: 'Llegamos al aeropuerto a tiempo.', exampleEn: 'We arrived at the airport on time.', level: 'A2', freq: 2 },
  { word: 'estación', english: 'station', category: 'places', pos: 'noun', gender: 'f', example: 'La estación de tren está lejos.', exampleEn: 'The train station is far away.', level: 'A2', freq: 2 },
  { word: 'calle', english: 'street', category: 'places', pos: 'noun', gender: 'f', example: 'Camino por la calle principal.', exampleEn: 'I walk down the main street.', level: 'A1', freq: 1 },
  { word: 'ciudad', english: 'city', category: 'places', pos: 'noun', gender: 'f', example: 'La ciudad es muy grande.', exampleEn: 'The city is very big.', level: 'A1', freq: 1 },
  { word: 'país', english: 'country', category: 'places', pos: 'noun', gender: 'm', example: 'México es un país hermoso.', exampleEn: 'Mexico is a beautiful country.', level: 'A1', freq: 1 },
  { word: 'hotel', english: 'hotel', category: 'places', pos: 'noun', gender: 'm', example: 'El hotel tiene piscina.', exampleEn: 'The hotel has a pool.', level: 'A1', freq: 2 },
  { word: 'oficina', english: 'office', category: 'places', pos: 'noun', gender: 'f', example: 'Trabajo en una oficina.', exampleEn: 'I work in an office.', level: 'A1', freq: 2 },
  { word: 'farmacia', english: 'pharmacy', category: 'places', pos: 'noun', gender: 'f', example: 'La farmacia está abierta.', exampleEn: 'The pharmacy is open.', level: 'A2', freq: 3 },

  // ── BODY ──
  { word: 'cabeza', english: 'head', category: 'body', pos: 'noun', gender: 'f', example: 'Me duele la cabeza.', exampleEn: 'My head hurts.', level: 'A1', freq: 1 },
  { word: 'ojo', english: 'eye', category: 'body', pos: 'noun', gender: 'm', example: 'Tiene los ojos azules.', exampleEn: 'He/She has blue eyes.', level: 'A1', freq: 1 },
  { word: 'nariz', english: 'nose', category: 'body', pos: 'noun', gender: 'f', example: 'Tiene la nariz pequeña.', exampleEn: 'He/She has a small nose.', level: 'A1', freq: 2 },
  { word: 'boca', english: 'mouth', category: 'body', pos: 'noun', gender: 'f', example: 'Abre la boca.', exampleEn: 'Open your mouth.', level: 'A1', freq: 2 },
  { word: 'oreja', english: 'ear', category: 'body', pos: 'noun', gender: 'f', example: 'Me duele la oreja.', exampleEn: 'My ear hurts.', level: 'A1', freq: 2 },
  { word: 'mano', english: 'hand', category: 'body', pos: 'noun', gender: 'f', example: 'Dame la mano.', exampleEn: 'Give me your hand.', level: 'A1', freq: 1 },
  { word: 'brazo', english: 'arm', category: 'body', pos: 'noun', gender: 'm', example: 'Me rompí el brazo.', exampleEn: 'I broke my arm.', level: 'A1', freq: 2 },
  { word: 'pierna', english: 'leg', category: 'body', pos: 'noun', gender: 'f', example: 'Me duele la pierna.', exampleEn: 'My leg hurts.', level: 'A1', freq: 2 },
  { word: 'pie', english: 'foot', category: 'body', pos: 'noun', gender: 'm', example: 'Tengo los pies cansados.', exampleEn: 'My feet are tired.', level: 'A1', freq: 2 },
  { word: 'corazón', english: 'heart', category: 'body', pos: 'noun', gender: 'm', example: 'Mi corazón late rápido.', exampleEn: 'My heart beats fast.', level: 'A1', freq: 2 },
  { word: 'dedo', english: 'finger, toe', category: 'body', pos: 'noun', gender: 'm', example: 'Me corté el dedo.', exampleEn: 'I cut my finger.', level: 'A2', freq: 3 },
  { word: 'espalda', english: 'back', category: 'body', pos: 'noun', gender: 'f', example: 'Me duele la espalda.', exampleEn: 'My back hurts.', level: 'A2', freq: 3 },
  { word: 'estómago', english: 'stomach', category: 'body', pos: 'noun', gender: 'm', example: 'Tengo dolor de estómago.', exampleEn: 'I have a stomachache.', level: 'A2', freq: 3 },
  { word: 'pelo', english: 'hair', category: 'body', pos: 'noun', gender: 'm', example: 'Tiene el pelo largo.', exampleEn: 'He/She has long hair.', level: 'A1', freq: 2 },
  { word: 'diente', english: 'tooth', category: 'body', pos: 'noun', gender: 'm', example: 'Me duele un diente.', exampleEn: 'A tooth hurts.', level: 'A2', freq: 3 },

  // ── CLOTHING ──
  { word: 'camisa', english: 'shirt', category: 'clothing', pos: 'noun', gender: 'f', example: 'La camisa es azul.', exampleEn: 'The shirt is blue.', level: 'A1', freq: 2 },
  { word: 'pantalón', english: 'pants', category: 'clothing', pos: 'noun', gender: 'm', example: 'Necesito un pantalón nuevo.', exampleEn: 'I need new pants.', level: 'A1', freq: 2 },
  { word: 'zapato', english: 'shoe', category: 'clothing', pos: 'noun', gender: 'm', example: 'Estos zapatos son cómodos.', exampleEn: 'These shoes are comfortable.', level: 'A1', freq: 2 },
  { word: 'vestido', english: 'dress', category: 'clothing', pos: 'noun', gender: 'm', example: 'El vestido es muy bonito.', exampleEn: 'The dress is very pretty.', level: 'A1', freq: 2 },
  { word: 'falda', english: 'skirt', category: 'clothing', pos: 'noun', gender: 'f', example: 'La falda es corta.', exampleEn: 'The skirt is short.', level: 'A2', freq: 3 },
  { word: 'chaqueta', english: 'jacket', category: 'clothing', pos: 'noun', gender: 'f', example: 'Ponte la chaqueta, hace frío.', exampleEn: "Put on your jacket, it's cold.", level: 'A2', freq: 3 },
  { word: 'sombrero', english: 'hat', category: 'clothing', pos: 'noun', gender: 'm', example: 'Lleva un sombrero grande.', exampleEn: 'He/She wears a big hat.', level: 'A2', freq: 3 },
  { word: 'calcetín', english: 'sock', category: 'clothing', pos: 'noun', gender: 'm', example: '¿Dónde están mis calcetines?', exampleEn: 'Where are my socks?', level: 'A2', freq: 3 },
  { word: 'abrigo', english: 'coat', category: 'clothing', pos: 'noun', gender: 'm', example: 'Necesitas un abrigo de invierno.', exampleEn: 'You need a winter coat.', level: 'A2', freq: 3 },
  { word: 'corbata', english: 'tie', category: 'clothing', pos: 'noun', gender: 'f', example: 'La corbata es de seda.', exampleEn: 'The tie is made of silk.', level: 'B1', freq: 4 },

  // ── COLORS ──
  { word: 'rojo', english: 'red', category: 'colors', pos: 'adjective', gender: null, example: 'La rosa es roja.', exampleEn: 'The rose is red.', level: 'A1', freq: 1 },
  { word: 'azul', english: 'blue', category: 'colors', pos: 'adjective', gender: null, example: 'El cielo es azul.', exampleEn: 'The sky is blue.', level: 'A1', freq: 1 },
  { word: 'verde', english: 'green', category: 'colors', pos: 'adjective', gender: null, example: 'La hierba es verde.', exampleEn: 'The grass is green.', level: 'A1', freq: 1 },
  { word: 'amarillo', english: 'yellow', category: 'colors', pos: 'adjective', gender: null, example: 'El sol es amarillo.', exampleEn: 'The sun is yellow.', level: 'A1', freq: 2 },
  { word: 'blanco', english: 'white', category: 'colors', pos: 'adjective', gender: null, example: 'La nieve es blanca.', exampleEn: 'The snow is white.', level: 'A1', freq: 1 },
  { word: 'negro', english: 'black', category: 'colors', pos: 'adjective', gender: null, example: 'El gato es negro.', exampleEn: 'The cat is black.', level: 'A1', freq: 1 },
  { word: 'marrón', english: 'brown', category: 'colors', pos: 'adjective', gender: null, example: 'El chocolate es marrón.', exampleEn: 'Chocolate is brown.', level: 'A1', freq: 2 },
  { word: 'naranja', english: 'orange (color)', category: 'colors', pos: 'adjective', gender: null, example: 'La camiseta es naranja.', exampleEn: 'The T-shirt is orange.', level: 'A1', freq: 2 },
  { word: 'rosa', english: 'pink', category: 'colors', pos: 'adjective', gender: null, example: 'Las flores son rosas.', exampleEn: 'The flowers are pink.', level: 'A1', freq: 2 },
  { word: 'morado', english: 'purple', category: 'colors', pos: 'adjective', gender: null, example: 'La uva es morada.', exampleEn: 'The grape is purple.', level: 'A2', freq: 3 },
  { word: 'gris', english: 'gray', category: 'colors', pos: 'adjective', gender: null, example: 'El día está gris.', exampleEn: 'The day is gray.', level: 'A1', freq: 2 },
  { word: 'dorado', english: 'golden', category: 'colors', pos: 'adjective', gender: null, example: 'El anillo es dorado.', exampleEn: 'The ring is golden.', level: 'A2', freq: 3 },
  { word: 'plateado', english: 'silver', category: 'colors', pos: 'adjective', gender: null, example: 'El coche es plateado.', exampleEn: 'The car is silver.', level: 'A2', freq: 3 },

  // ── NUMBERS ──
  { word: 'uno', english: 'one', category: 'numbers', pos: 'number', gender: null, example: 'Tengo un hermano.', exampleEn: 'I have one brother.', level: 'A1', freq: 1 },
  { word: 'dos', english: 'two', category: 'numbers', pos: 'number', gender: null, example: 'Quiero dos cafés.', exampleEn: 'I want two coffees.', level: 'A1', freq: 1 },
  { word: 'tres', english: 'three', category: 'numbers', pos: 'number', gender: null, example: 'Son las tres de la tarde.', exampleEn: "It's three in the afternoon.", level: 'A1', freq: 1 },
  { word: 'cuatro', english: 'four', category: 'numbers', pos: 'number', gender: null, example: 'Hay cuatro estaciones.', exampleEn: 'There are four seasons.', level: 'A1', freq: 1 },
  { word: 'cinco', english: 'five', category: 'numbers', pos: 'number', gender: null, example: 'Tengo cinco dedos en cada mano.', exampleEn: 'I have five fingers on each hand.', level: 'A1', freq: 1 },
  { word: 'diez', english: 'ten', category: 'numbers', pos: 'number', gender: null, example: 'Son las diez de la mañana.', exampleEn: "It's ten in the morning.", level: 'A1', freq: 1 },
  { word: 'veinte', english: 'twenty', category: 'numbers', pos: 'number', gender: null, example: 'Tengo veinte años.', exampleEn: "I'm twenty years old.", level: 'A1', freq: 1 },
  { word: 'cien', english: 'one hundred', category: 'numbers', pos: 'number', gender: null, example: 'Cuesta cien dólares.', exampleEn: 'It costs one hundred dollars.', level: 'A1', freq: 2 },
  { word: 'mil', english: 'one thousand', category: 'numbers', pos: 'number', gender: null, example: 'La casa cuesta cien mil dólares.', exampleEn: 'The house costs one hundred thousand dollars.', level: 'A2', freq: 2 },
  { word: 'millón', english: 'one million', category: 'numbers', pos: 'noun', gender: 'm', example: 'La ciudad tiene un millón de habitantes.', exampleEn: 'The city has one million inhabitants.', level: 'A2', freq: 3 },
  { word: 'primero', english: 'first', category: 'numbers', pos: 'adjective', gender: null, example: 'Es mi primer día.', exampleEn: "It's my first day.", level: 'A1', freq: 1 },
  { word: 'segundo', english: 'second', category: 'numbers', pos: 'adjective', gender: null, example: 'Vivo en el segundo piso.', exampleEn: 'I live on the second floor.', level: 'A1', freq: 2 },

  // ── TIME ──
  { word: 'hora', english: 'hour, time', category: 'time', pos: 'noun', gender: 'f', example: '¿Qué hora es?', exampleEn: 'What time is it?', level: 'A1', freq: 1 },
  { word: 'minuto', english: 'minute', category: 'time', pos: 'noun', gender: 'm', example: 'Espera un minuto.', exampleEn: 'Wait a minute.', level: 'A1', freq: 1 },
  { word: 'día', english: 'day', category: 'time', pos: 'noun', gender: 'm', example: 'Hoy es un buen día.', exampleEn: 'Today is a good day.', level: 'A1', freq: 1 },
  { word: 'semana', english: 'week', category: 'time', pos: 'noun', gender: 'f', example: 'La próxima semana viajo.', exampleEn: "I'm traveling next week.", level: 'A1', freq: 1 },
  { word: 'mes', english: 'month', category: 'time', pos: 'noun', gender: 'm', example: 'Enero es el primer mes del año.', exampleEn: 'January is the first month of the year.', level: 'A1', freq: 1 },
  { word: 'año', english: 'year', category: 'time', pos: 'noun', gender: 'm', example: 'El año tiene doce meses.', exampleEn: 'The year has twelve months.', level: 'A1', freq: 1 },
  { word: 'lunes', english: 'Monday', category: 'time', pos: 'noun', gender: 'm', example: 'El lunes tengo clase.', exampleEn: 'On Monday I have class.', level: 'A1', freq: 1 },
  { word: 'martes', english: 'Tuesday', category: 'time', pos: 'noun', gender: 'm', example: 'Nos vemos el martes.', exampleEn: "We'll see each other on Tuesday.", level: 'A1', freq: 2 },
  { word: 'miércoles', english: 'Wednesday', category: 'time', pos: 'noun', gender: 'm', example: 'El miércoles es feriado.', exampleEn: 'Wednesday is a holiday.', level: 'A1', freq: 2 },
  { word: 'jueves', english: 'Thursday', category: 'time', pos: 'noun', gender: 'm', example: 'El jueves hay reunión.', exampleEn: "There's a meeting on Thursday.", level: 'A1', freq: 2 },
  { word: 'viernes', english: 'Friday', category: 'time', pos: 'noun', gender: 'm', example: '¡Por fin es viernes!', exampleEn: "It's finally Friday!", level: 'A1', freq: 2 },
  { word: 'sábado', english: 'Saturday', category: 'time', pos: 'noun', gender: 'm', example: 'El sábado vamos al cine.', exampleEn: "On Saturday we're going to the movies.", level: 'A1', freq: 2 },
  { word: 'domingo', english: 'Sunday', category: 'time', pos: 'noun', gender: 'm', example: 'El domingo descanso.', exampleEn: 'On Sunday I rest.', level: 'A1', freq: 2 },
  { word: 'hoy', english: 'today', category: 'time', pos: 'adverb', gender: null, example: 'Hoy hace buen tiempo.', exampleEn: 'Today the weather is nice.', level: 'A1', freq: 1 },
  { word: 'mañana', english: 'tomorrow, morning', category: 'time', pos: 'adverb', gender: null, example: 'Mañana voy al médico.', exampleEn: "Tomorrow I'm going to the doctor.", level: 'A1', freq: 1 },
  { word: 'ayer', english: 'yesterday', category: 'time', pos: 'adverb', gender: null, example: 'Ayer llovió mucho.', exampleEn: 'Yesterday it rained a lot.', level: 'A1', freq: 1 },
  { word: 'ahora', english: 'now', category: 'time', pos: 'adverb', gender: null, example: 'Ahora estoy ocupado.', exampleEn: "I'm busy right now.", level: 'A1', freq: 1 },
  { word: 'siempre', english: 'always', category: 'time', pos: 'adverb', gender: null, example: 'Siempre llega tarde.', exampleEn: 'He/She always arrives late.', level: 'A1', freq: 1 },
  { word: 'nunca', english: 'never', category: 'time', pos: 'adverb', gender: null, example: 'Nunca he ido a España.', exampleEn: "I've never been to Spain.", level: 'A1', freq: 1 },

  // ── EMOTIONS ──
  { word: 'feliz', english: 'happy', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy muy feliz hoy.', exampleEn: "I'm very happy today.", level: 'A1', freq: 1 },
  { word: 'triste', english: 'sad', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy triste porque se fue.', exampleEn: "I'm sad because he/she left.", level: 'A1', freq: 1 },
  { word: 'enojado', english: 'angry', category: 'emotions', pos: 'adjective', gender: null, example: 'Está enojado conmigo.', exampleEn: "He's angry with me.", level: 'A1', freq: 2 },
  { word: 'cansado', english: 'tired', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy muy cansado.', exampleEn: "I'm very tired.", level: 'A1', freq: 1 },
  { word: 'contento', english: 'content, pleased', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy contento con los resultados.', exampleEn: "I'm pleased with the results.", level: 'A1', freq: 2 },
  { word: 'nervioso', english: 'nervous', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy nervioso por el examen.', exampleEn: "I'm nervous about the exam.", level: 'A2', freq: 2 },
  { word: 'preocupado', english: 'worried', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy preocupado por mi madre.', exampleEn: "I'm worried about my mother.", level: 'A2', freq: 2 },
  { word: 'sorprendido', english: 'surprised', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy sorprendido por la noticia.', exampleEn: "I'm surprised by the news.", level: 'A2', freq: 3 },
  { word: 'aburrido', english: 'bored', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy aburrido en casa.', exampleEn: "I'm bored at home.", level: 'A2', freq: 2 },
  { word: 'asustado', english: 'scared', category: 'emotions', pos: 'adjective', gender: null, example: 'El niño está asustado.', exampleEn: 'The boy is scared.', level: 'A2', freq: 3 },
  { word: 'orgulloso', english: 'proud', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy orgulloso de mi hijo.', exampleEn: "I'm proud of my son.", level: 'A2', freq: 3 },
  { word: 'emocionado', english: 'excited', category: 'emotions', pos: 'adjective', gender: null, example: 'Estoy emocionado por el viaje.', exampleEn: "I'm excited about the trip.", level: 'A2', freq: 2 },

  // ── ADJECTIVES ──
  { word: 'grande', english: 'big, large', category: 'adjectives', pos: 'adjective', gender: null, example: 'La casa es muy grande.', exampleEn: 'The house is very big.', level: 'A1', freq: 1 },
  { word: 'pequeño', english: 'small, little', category: 'adjectives', pos: 'adjective', gender: null, example: 'El perro es pequeño.', exampleEn: 'The dog is small.', level: 'A1', freq: 1 },
  { word: 'bueno', english: 'good', category: 'adjectives', pos: 'adjective', gender: null, example: 'El libro es bueno.', exampleEn: 'The book is good.', level: 'A1', freq: 1 },
  { word: 'malo', english: 'bad', category: 'adjectives', pos: 'adjective', gender: null, example: 'El tiempo está malo.', exampleEn: 'The weather is bad.', level: 'A1', freq: 1 },
  { word: 'nuevo', english: 'new', category: 'adjectives', pos: 'adjective', gender: null, example: 'Compré un coche nuevo.', exampleEn: 'I bought a new car.', level: 'A1', freq: 1 },
  { word: 'viejo', english: 'old', category: 'adjectives', pos: 'adjective', gender: null, example: 'El edificio es muy viejo.', exampleEn: 'The building is very old.', level: 'A1', freq: 1 },
  { word: 'bonito', english: 'pretty, nice', category: 'adjectives', pos: 'adjective', gender: null, example: 'El vestido es muy bonito.', exampleEn: 'The dress is very pretty.', level: 'A1', freq: 1 },
  { word: 'feo', english: 'ugly', category: 'adjectives', pos: 'adjective', gender: null, example: 'El cuadro es feo.', exampleEn: 'The painting is ugly.', level: 'A2', freq: 3 },
  { word: 'fácil', english: 'easy', category: 'adjectives', pos: 'adjective', gender: null, example: 'El examen es fácil.', exampleEn: 'The exam is easy.', level: 'A1', freq: 1 },
  { word: 'difícil', english: 'difficult', category: 'adjectives', pos: 'adjective', gender: null, example: 'El español no es difícil.', exampleEn: 'Spanish is not difficult.', level: 'A1', freq: 1 },
  { word: 'rápido', english: 'fast', category: 'adjectives', pos: 'adjective', gender: null, example: 'El tren es rápido.', exampleEn: 'The train is fast.', level: 'A1', freq: 1 },
  { word: 'lento', english: 'slow', category: 'adjectives', pos: 'adjective', gender: null, example: 'El autobús es lento.', exampleEn: 'The bus is slow.', level: 'A1', freq: 2 },
  { word: 'caliente', english: 'hot', category: 'adjectives', pos: 'adjective', gender: null, example: 'La sopa está caliente.', exampleEn: 'The soup is hot.', level: 'A1', freq: 1 },
  { word: 'frío', english: 'cold', category: 'adjectives', pos: 'adjective', gender: null, example: 'El agua está fría.', exampleEn: 'The water is cold.', level: 'A1', freq: 1 },
  { word: 'importante', english: 'important', category: 'adjectives', pos: 'adjective', gender: null, example: 'Es una decisión importante.', exampleEn: "It's an important decision.", level: 'A1', freq: 1 },
  { word: 'interesante', english: 'interesting', category: 'adjectives', pos: 'adjective', gender: null, example: 'El libro es interesante.', exampleEn: 'The book is interesting.', level: 'A1', freq: 1 },
  { word: 'necesario', english: 'necessary', category: 'adjectives', pos: 'adjective', gender: null, example: 'Es necesario estudiar.', exampleEn: "It's necessary to study.", level: 'A2', freq: 2 },
  { word: 'posible', english: 'possible', category: 'adjectives', pos: 'adjective', gender: null, example: '¿Es posible cambiar la fecha?', exampleEn: 'Is it possible to change the date?', level: 'A2', freq: 2 },
  { word: 'barato', english: 'cheap', category: 'adjectives', pos: 'adjective', gender: null, example: 'El restaurante es barato.', exampleEn: 'The restaurant is cheap.', level: 'A1', freq: 2 },
  { word: 'caro', english: 'expensive', category: 'adjectives', pos: 'adjective', gender: null, example: 'El hotel es muy caro.', exampleEn: 'The hotel is very expensive.', level: 'A1', freq: 2 },
  { word: 'largo', english: 'long', category: 'adjectives', pos: 'adjective', gender: null, example: 'El camino es largo.', exampleEn: 'The road is long.', level: 'A1', freq: 2 },
  { word: 'corto', english: 'short', category: 'adjectives', pos: 'adjective', gender: null, example: 'La película es corta.', exampleEn: 'The movie is short.', level: 'A1', freq: 2 },
  { word: 'joven', english: 'young', category: 'adjectives', pos: 'adjective', gender: null, example: 'Es una mujer joven.', exampleEn: "She's a young woman.", level: 'A1', freq: 1 },
  { word: 'rico', english: 'rich, delicious', category: 'adjectives', pos: 'adjective', gender: null, example: 'La comida está rica.', exampleEn: 'The food is delicious.', level: 'A1', freq: 2 },
  { word: 'pobre', english: 'poor', category: 'adjectives', pos: 'adjective', gender: null, example: 'Es un país pobre.', exampleEn: "It's a poor country.", level: 'A2', freq: 2 },
  { word: 'limpio', english: 'clean', category: 'adjectives', pos: 'adjective', gender: null, example: 'La casa está limpia.', exampleEn: 'The house is clean.', level: 'A2', freq: 2 },
  { word: 'sucio', english: 'dirty', category: 'adjectives', pos: 'adjective', gender: null, example: 'La camisa está sucia.', exampleEn: 'The shirt is dirty.', level: 'A2', freq: 3 },

  // ── PREPOSITIONS ──
  { word: 'en', english: 'in, on, at', category: 'prepositions', pos: 'preposition', gender: null, example: 'Estoy en casa.', exampleEn: "I'm at home.", level: 'A1', freq: 1 },
  { word: 'de', english: 'of, from', category: 'prepositions', pos: 'preposition', gender: null, example: 'Soy de México.', exampleEn: "I'm from Mexico.", level: 'A1', freq: 1 },
  { word: 'a', english: 'to, at', category: 'prepositions', pos: 'preposition', gender: null, example: 'Voy a la escuela.', exampleEn: "I'm going to school.", level: 'A1', freq: 1 },
  { word: 'con', english: 'with', category: 'prepositions', pos: 'preposition', gender: null, example: 'Voy con mi amigo.', exampleEn: "I'm going with my friend.", level: 'A1', freq: 1 },
  { word: 'sin', english: 'without', category: 'prepositions', pos: 'preposition', gender: null, example: 'Café sin azúcar.', exampleEn: 'Coffee without sugar.', level: 'A1', freq: 1 },
  { word: 'para', english: 'for, in order to', category: 'prepositions', pos: 'preposition', gender: null, example: 'Este regalo es para ti.', exampleEn: 'This gift is for you.', level: 'A1', freq: 1 },
  { word: 'por', english: 'for, by, through', category: 'prepositions', pos: 'preposition', gender: null, example: 'Gracias por todo.', exampleEn: 'Thanks for everything.', level: 'A1', freq: 1 },
  { word: 'sobre', english: 'on, about, over', category: 'prepositions', pos: 'preposition', gender: null, example: 'El libro está sobre la mesa.', exampleEn: 'The book is on the table.', level: 'A1', freq: 2 },
  { word: 'entre', english: 'between, among', category: 'prepositions', pos: 'preposition', gender: null, example: 'La tienda está entre el banco y la farmacia.', exampleEn: 'The store is between the bank and the pharmacy.', level: 'A2', freq: 2 },
  { word: 'hasta', english: 'until, up to', category: 'prepositions', pos: 'preposition', gender: null, example: 'Trabajo hasta las cinco.', exampleEn: 'I work until five.', level: 'A1', freq: 1 },
  { word: 'desde', english: 'from, since', category: 'prepositions', pos: 'preposition', gender: null, example: 'Vivo aquí desde 2020.', exampleEn: "I've lived here since 2020.", level: 'A2', freq: 2 },
  { word: 'durante', english: 'during', category: 'prepositions', pos: 'preposition', gender: null, example: 'Estudié durante dos horas.', exampleEn: 'I studied for two hours.', level: 'A2', freq: 2 },

  // ── CONJUNCTIONS ──
  { word: 'y', english: 'and', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Tengo un perro y un gato.', exampleEn: 'I have a dog and a cat.', level: 'A1', freq: 1 },
  { word: 'o', english: 'or', category: 'conjunctions', pos: 'conjunction', gender: null, example: '¿Quieres café o té?', exampleEn: 'Do you want coffee or tea?', level: 'A1', freq: 1 },
  { word: 'pero', english: 'but', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Es difícil pero interesante.', exampleEn: "It's difficult but interesting.", level: 'A1', freq: 1 },
  { word: 'porque', english: 'because', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Estudio porque quiero aprender.', exampleEn: 'I study because I want to learn.', level: 'A1', freq: 1 },
  { word: 'si', english: 'if', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Si llueve, no voy.', exampleEn: "If it rains, I won't go.", level: 'A1', freq: 1 },
  { word: 'cuando', english: 'when', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Cuando llego a casa, descanso.', exampleEn: 'When I get home, I rest.', level: 'A1', freq: 1 },
  { word: 'que', english: 'that, which', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Creo que es verdad.', exampleEn: "I think that it's true.", level: 'A1', freq: 1 },
  { word: 'aunque', english: 'although, even though', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Salí aunque llovía.', exampleEn: 'I went out although it was raining.', level: 'A2', freq: 2 },
  { word: 'mientras', english: 'while', category: 'conjunctions', pos: 'conjunction', gender: null, example: 'Leo mientras espero.', exampleEn: 'I read while I wait.', level: 'A2', freq: 2 },
  { word: 'también', english: 'also, too', category: 'conjunctions', pos: 'adverb', gender: null, example: 'Yo también quiero ir.', exampleEn: 'I also want to go.', level: 'A1', freq: 1 },

  // ── PRONOUNS ──
  { word: 'yo', english: 'I', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Yo soy estudiante.', exampleEn: "I'm a student.", level: 'A1', freq: 1 },
  { word: 'tú', english: 'you (informal)', category: 'pronouns', pos: 'pronoun', gender: null, example: '¿Tú hablas español?', exampleEn: 'Do you speak Spanish?', level: 'A1', freq: 1 },
  { word: 'él', english: 'he', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Él es mi amigo.', exampleEn: "He's my friend.", level: 'A1', freq: 1 },
  { word: 'ella', english: 'she', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Ella es doctora.', exampleEn: "She's a doctor.", level: 'A1', freq: 1 },
  { word: 'usted', english: 'you (formal)', category: 'pronouns', pos: 'pronoun', gender: null, example: '¿Usted habla inglés?', exampleEn: 'Do you speak English?', level: 'A1', freq: 1 },
  { word: 'nosotros', english: 'we', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Nosotros estudiamos español.', exampleEn: 'We study Spanish.', level: 'A1', freq: 1 },
  { word: 'ellos', english: 'they (masc.)', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Ellos viven en Buenos Aires.', exampleEn: 'They live in Buenos Aires.', level: 'A1', freq: 1 },
  { word: 'ellas', english: 'they (fem.)', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Ellas son mis hermanas.', exampleEn: 'They are my sisters.', level: 'A1', freq: 2 },
  { word: 'esto', english: 'this', category: 'pronouns', pos: 'pronoun', gender: null, example: '¿Qué es esto?', exampleEn: 'What is this?', level: 'A1', freq: 1 },
  { word: 'eso', english: 'that', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Eso no es verdad.', exampleEn: "That's not true.", level: 'A1', freq: 1 },
  { word: 'algo', english: 'something', category: 'pronouns', pos: 'pronoun', gender: null, example: '¿Quieres algo de comer?', exampleEn: 'Do you want something to eat?', level: 'A1', freq: 1 },
  { word: 'nada', english: 'nothing', category: 'pronouns', pos: 'pronoun', gender: null, example: 'No quiero nada.', exampleEn: "I don't want anything.", level: 'A1', freq: 1 },
  { word: 'todo', english: 'everything, all', category: 'pronouns', pos: 'pronoun', gender: null, example: 'Todo está bien.', exampleEn: 'Everything is fine.', level: 'A1', freq: 1 },
  { word: 'alguien', english: 'someone', category: 'pronouns', pos: 'pronoun', gender: null, example: '¿Hay alguien en casa?', exampleEn: 'Is someone home?', level: 'A2', freq: 2 },
  { word: 'nadie', english: 'nobody', category: 'pronouns', pos: 'pronoun', gender: null, example: 'No hay nadie aquí.', exampleEn: "There's nobody here.", level: 'A2', freq: 2 },
];
